"use strict";
(function(root){
  const MODEL={roles:{customer:'مشتری',supplier:'تأمین‌کننده',partner:'شریک',other:'سایر'},tabs:[['dashboard','داشبورد'],['people','اشخاص'],['sales','فروش'],['saleReturns','برگشت فروش'],['receipts','دریافت'],['checksIn','چک دریافتی'],['statement','حساب جاری'],['products','کالا و موجودی'],['purchases','خرید'],['purchaseReturns','برگشت خرید'],['payments','پرداخت'],['checksOut','چک پرداختی'],['cashbank','صندوق و بانک'],['expenses','هزینه'],['incomes','درآمد'],['prices','قیمت‌ها'],['reports','گزارش‌ها'],['settings','تنظیمات'],['backup','پشتیبان'],['audit','رویدادها']]};
  const $=id=>document.getElementById(id), num=v=>Number(String(v??'').replace(/[٬,\s]/g,''))||0, esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), today=()=>todayJ(), fmt=n=>String(Math.round(num(n))).replace(/\B(?=(\d{3})+(?!\d))/g,','), uid=p=>(p||'R-')+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const btn=(id,label,cls='')=>`<button class="btn ${cls}" id="${id}">${label}</button>`, input=(id,label,type='text',value='')=>`<div><label>${label}</label><input id="${id}" type="${type}" value="${esc(value)}"></div>`;
  const select=(id,items,placeholder,filter)=>`<select id="${id}"><option value="">${placeholder||'انتخاب کنید'}</option>${items.filter(filter||(()=>true)).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`;
  const table=(heads,rows)=>`<div class="tbl-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}" class="em">رکوردی وجود ندارد</td></tr>`}</tbody></table></div>`;
  const box=(title,body,actions='')=>`<div class="bx"><h3>${title}</h3>${body}${actions?`<div class="actions">${actions}</div>`:''}</div>`;
  const peopleList=()=>DB.people||[], productsList=()=>DB.products||[];
  function record(table,r,note){const rec=Object.assign({id:uid(table+'-'),createdAt:new Date().toISOString()},r);DB[table].push(rec);DB.auditLog('create',table,rec.id,note);DB.save(table);return rec}
  function dashboard(){const cs=peopleList().filter(p=>p.role==='customer');let s=0,r=0,b=0;cs.forEach(c=>{const x=Finance.customerSummary({customerId:c.id,calcDate:today(),settings:DB.settings,sales:DB.sales,receipts:DB.receipts,checks:DB.checks,saleReturns:DB.saleReturns});s+=x.totalSales;r+=x.totalReceipts;b+=x.settlement});const future=(DB.checks||[]).filter(x=>x.direction!=='out'&&x.status!=='وصول شده'&&x.status!=='برگشتی'&&x.status!=='باطل').reduce((n,x)=>n+num(x.amount),0);return `<div class="kpi"><div class="k"><div class="l">فروش خالص</div><div class="v">${fmt(s)}</div></div><div class="k"><div class="l">دریافت مؤثر</div><div class="v">${fmt(r)}</div></div><div class="k"><div class="l">مانده تسویه</div><div class="v">${fmt(b)}</div></div><div class="k"><div class="l">چک آینده</div><div class="v">${fmt(future)}</div></div></div>`+box('چرخه مالی اصلی','فروش → حساب مشتری → دریافت نقد/کارت/چک → تخصیص FIFO → سود روزشمار → مانده قابل تسویه. خرید و پرداخت نیز چرخه مستقل طرف حساب و موجودی هستند.');}
  function people(){const role=window._role||'customer',rows=peopleList().filter(p=>p.role===role).map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.code||'—')}</td><td>${esc(p.company||'—')}</td><td>${esc(p.phone||'—')}</td><td>${fmt(p.openingBalance||0)}</td><td>${btn('delperson-'+p.id,'حذف','r ic')}</td></tr>`).join('');return box('اشخاص',`<div class="tabs-l2">${Object.entries(MODEL.roles).map(([k,v])=>`<button data-role="${k}" class="${role===k?'on':''}">${v}</button>`).join('')}</div><div class="row">${input('pName','نام *')}${input('pCode','کد شخص')}${input('pCompany','شرکت')}${input('pPhone','تلفن')}${input('pOpening','مانده افتتاحیه','number','0')}</div>`,btn('addPerson','ثبت شخص','s'))+box('فهرست',table(['نام','کد','شرکت','تلفن','افتتاحیه',''],rows));}
  function products(){const rows=productsList().map(p=>`<tr><td>${esc(p.code||'')}</td><td><b>${esc(p.name)}</b></td><td>${esc(p.kind||'')}</td><td>${esc(p.unit||'عدد')}</td><td>${fmt(Inventory.stock(DB,p.id,today()))}</td><td>${btn('delproduct-'+p.id,'حذف','r ic')}</td></tr>`).join('');return box('کالا و موجودی',`<div class="row">${input('prCode','کد کالا')}${input('prName','نام کالا *')}${input('prCat','گروه کالا')}${input('prUnit','واحد','text','عدد')}${input('prPkg','واحد بسته','text','کارتن')}${input('prPpp','تعداد در بسته','number','1')}<div><label>نوع</label><select id="prKind"><option>مواد اولیه</option><option>محصول نهایی</option><option>کالای تجاری</option></select></div></div>`,btn('addProduct','ثبت کالا','s'))+box('موجودی فعلی',table(['کد','کالا','نوع','واحد','موجودی',''],rows));}
  function sales(){const rows=(DB.sales||[]).slice().reverse().map(s=>`<tr><td>${esc(s.jDate)}</td><td>${esc(s.invoiceNo||s.id)}</td><td>${esc(DB.getCustomer(s.customerId)?.name||'—')}</td><td>${esc(DB.getProduct(s.productId)?.name||'—')}</td><td>${fmt(s.qty)}</td><td>${fmt(s.grossAmount??s.amount)}</td><td>${fmt(s.discount||0)}</td><td>${fmt(s.netAmount??s.amount)}</td><td>${btn('delsale-'+s.id,'حذف','r ic')}</td></tr>`).join('');return box('فروش / فاکتور',`<div class="row">${select('saleCustomer',peopleList(),'مشتری',p=>p.role==='customer')}${input('saleNo','شماره فاکتور')}${input('saleDate','تاریخ','text',today())}${input('saleDue','سررسید')}${select('saleProduct',productsList(),'کالا')}${input('saleQty','تعداد','number','1')}${input('salePrice','قیمت واحد','number')}${input('saleDiscount','تخفیف','number','0')}</div>`,btn('addSale','ثبت فاکتور','s'))+box('فاکتورهای فروش',table(['تاریخ','شماره','مشتری','کالا','تعداد','ناخالص','تخفیف','خالص',''],rows));}
  function saleReturns(){return box('برگشت فروش',`<div class="row">${select('srCustomer',peopleList(),'مشتری',p=>p.role==='customer')}${select('srProduct',productsList(),'کالا')}${input('srQty','تعداد','number','1')}${input('srAmount','مبلغ برگشت','number')}${input('srDate','تاریخ','text',today())}${input('srRef','مرجع فاکتور')}</div>`,btn('addSaleReturn','ثبت برگشت فروش','s'))+box('سوابق',table(['تاریخ','مشتری','کالا','تعداد','مبلغ'],(DB.saleReturns||[]).slice().reverse().map(x=>`<tr><td>${esc(x.jDate)}</td><td>${esc(DB.getCustomer(x.customerId)?.name||'—')}</td><td>${esc(DB.getProduct(x.productId)?.name||'—')}</td><td>${fmt(x.qty)}</td><td>${fmt(x.amount)}</td></tr>`).join('')));}
  function receipts(){const rows=(DB.receipts||[]).slice().reverse().map(r=>`<tr><td>${esc(r.jDate)}</td><td>${esc(DB.getCustomer(r.customerId)?.name||'—')}</td><td>${esc(r.type)}</td><td>${fmt(r.amount)}</td><td>${esc(r.status)}</td><td>${esc(r.dueDate||'—')}</td><td>${esc(r.accountId||'—')}</td><td>${btn('delreceipt-'+r.id,'حذف','r ic')}</td></tr>`).join('');return box('دریافت از مشتری',`<div class="row">${select('recCustomer',peopleList(),'مشتری',p=>p.role==='customer')}${input('recDate','تاریخ','text',today())}<div><label>نوع</label><select id="recType"><option>نقد</option><option>کارت</option><option>چک</option></select></div>${input('recAmount','مبلغ','number')}${input('recDue','سررسید چک')}${input('recBank','بانک/حساب') }<div><label>وضعیت</label><select id="recStatus"><option>وصول شده</option><option>نزد ما</option><option>تودیع‌شده</option><option>برگشتی</option><option>باطل</option></select></div>${input('recDesc','شرح')}</div>`,btn('addReceipt','ثبت دریافت','s'))+box('دفتر دریافت',table(['تاریخ','مشتری','نوع','مبلغ','وضعیت','سررسید','حساب',''],rows));}
  function checksIn(){const rows=(DB.checks||[]).filter(x=>x.direction!=='out').slice().reverse().map(x=>`<tr><td>${esc(x.checkNo||'—')}</td><td>${esc(DB.getCustomer(x.customerId)?.name||'—')}</td><td>${fmt(x.amount)}</td><td>${esc(x.issueDate||x.jDate)}</td><td>${esc(x.dueDate)}</td><td>${esc(x.bank||'—')}</td><td>${esc(x.status)}</td><td>${btn('delcheck-'+x.id,'حذف','r ic')}</td></tr>`).join('');return box('چک دریافتی',`<div class="row">${select('ciCustomer',peopleList(),'مشتری',p=>p.role==='customer')}${input('ciNo','شماره چک')}${input('ciAmount','مبلغ','number')}${input('ciIssue','تاریخ صدور','text',today())}${input('ciDue','سررسید')}${input('ciBank','بانک')}${input('ciAccount','شعبه/حساب')}<div><label>وضعیت</label><select id="ciStatus"><option>نزد ما</option><option>تودیع‌شده</option><option>وصول شده</option><option>برگشتی</option><option>باطل</option></select></div></div>`,btn('addCheckIn','ثبت چک','s'))+box('دفتر چک دریافتی',table(['شماره','مشتری','مبلغ','صدور','سررسید','بانک','وضعیت',''],rows));}
  function statement(){const d=window._statementDate||today(),rows=peopleList().filter(p=>p.role==='customer').map(c=>{const x=Finance.customerSummary({customerId:c.id,calcDate:d,settings:DB.settings,sales:DB.sales,receipts:DB.receipts,checks:DB.checks,saleReturns:DB.saleReturns});return `<tr><td><b>${esc(c.name)}</b></td><td>${fmt(x.totalSales)}</td><td>${fmt(x.totalReceipts)}</td><td>${fmt(x.futureChecks)}</td><td>${fmt(x.returnedChecks)}</td><td>${fmt(x.principal)}</td><td>${fmt(x.interest)}</td><td>${fmt(x.settlement)}</td><td>${fmt(x.credit)}</td></tr>`}).join('');return box('حساب جاری مشتریان',`<div class="row">${input('stmtDate','تاریخ محاسبه','text',d)}</div><div class="hint">چک آینده در ستون جداگانه نمایش داده می‌شود؛ چک برگشتی از دریافت مؤثر حذف می‌شود تا بدهی دوباره قابل مشاهده باشد. تأخیر چک برگشتی طبق سیاست تنظیمات مستقل است.</div>`,btn('calcStatement','محاسبه','s'))+box('مانده‌ها',table(['مشتری','فروش خالص','دریافت مؤثر','چک آینده','چک برگشتی','اصل مانده','سود روزشمار','مانده تسویه','بستانکاری'],rows));}
  function purchases(){const rows=(DB.purchases||[]).slice().reverse().map(x=>`<tr><td>${esc(x.jDate)}</td><td>${esc(x.invoiceNo||x.id)}</td><td>${esc(DB.people.find(p=>p.id===x.supplierId)?.name||'—')}</td><td>${esc(DB.getProduct(x.productId)?.name||'—')}</td><td>${fmt(x.qty)}</td><td>${fmt(x.amount)}</td></tr>`).join('');return box('خرید',`<div class="row">${select('puSupplier',peopleList(),'تأمین‌کننده',p=>p.role==='supplier')}${input('puNo','شماره فاکتور')}${input('puDate','تاریخ','text',today())}${select('puProduct',productsList(),'کالا')}${input('puQty','تعداد','number','1')}${input('puPrice','قیمت واحد','number')}${input('puDiscount','تخفیف','number','0')}</div>`,btn('addPurchase','ثبت خرید','s'))+box('خریدهای ثبت‌شده',table(['تاریخ','شماره','تأمین‌کننده','کالا','تعداد','مبلغ'],rows));}
  function purchaseReturns(){return box('برگشت خرید',`<div class="row">${select('purSupplier',peopleList(),'تأمین‌کننده',p=>p.role==='supplier')}${select('purProduct',productsList(),'کالا')}${input('purQty','تعداد','number','1')}${input('purAmount','مبلغ','number')}${input('purDate','تاریخ','text',today())}${input('purRef','مرجع فاکتور')}</div>`,btn('addPurchaseReturn','ثبت برگشت خرید','s'))}
  function payments(){return box('پرداخت',`<div class="row">${select('pmtPayee',peopleList(),'طرف حساب')}${input('pmtDate','تاریخ','text',today())}<div><label>نوع</label><select id="pmtType"><option>نقد</option><option>کارت</option><option>چک</option></select></div>${input('pmtAmount','مبلغ','number')}${input('pmtDue','سررسید چک')}${input('pmtBank','بانک/حساب')}${input('pmtDesc','شرح')}</div>`,btn('addPayment','ثبت پرداخت','s'))+box('سوابق پرداخت',table(['تاریخ','طرف حساب','نوع','مبلغ'],(DB.payments||[]).slice().reverse().map(x=>`<tr><td>${esc(x.jDate)}</td><td>${esc(DB.people.find(p=>p.id===x.payeeId)?.name||'—')}</td><td>${esc(x.type)}</td><td>${fmt(x.amount)}</td></tr>`).join('')));}
  function checksOut(){const rows=(DB.checks||[]).filter(x=>x.direction==='out').slice().reverse().map(x=>`<tr><td>${esc(x.checkNo)}</td><td>${esc(DB.people.find(p=>p.id===x.payeeId)?.name||'—')}</td><td>${fmt(x.amount)}</td><td>${esc(x.issueDate)}</td><td>${esc(x.dueDate)}</td><td>${esc(x.bank||'—')}</td><td>${esc(x.status)}</td></tr>`).join('');return box('چک پرداختی',`<div class="row">${select('coPayee',peopleList(),'طرف حساب')}${input('coNo','شماره چک')}${input('coAmount','مبلغ','number')}${input('coIssue','تاریخ صدور','text',today())}${input('coDue','سررسید')}${input('coBank','بانک')}${input('coAccount','حساب')}<div><label>وضعیت</label><select id="coStatus"><option>صادر شده</option><option>وصول شده</option><option>برگشتی</option><option>باطل</option></select></div></div>`,btn('addCheckOut','ثبت چک پرداختی','s'))+box('دفتر چک پرداختی',table(['شماره','طرف حساب','مبلغ','صدور','سررسید','بانک','وضعیت'],rows));}
  function cashbank(){const rows=(DB.accounts||[]).map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${fmt(a.openingBalance||0)}</td><td>${fmt(accountBalance(a.id))}</td></tr>`).join('');return box('صندوق و بانک',`<div class="row">${input('accName','نام حساب')}${input('accCode','کد حساب')}<div><label>نوع</label><select id="accType"><option>صندوق</option><option>بانک</option><option>کارتخوان</option><option>حساب داخلی</option></select></div>${input('accOpening','مانده افتتاحیه','number','0')}</div>`,btn('addAccount','ثبت حساب','s'))+box('مانده حساب‌ها',table(['نام','نوع','افتتاحیه','مانده'],rows));}
  function accountBalance(id){const a=(DB.accounts||[]).find(x=>x.id===id);let b=num(a?.openingBalance);(DB.receipts||[]).filter(x=>x.accountId===id&&x.status!=='باطل'&&x.type!=='چک').forEach(x=>b+=num(x.amount));(DB.incomes||[]).filter(x=>x.accountId===id).forEach(x=>b+=num(x.amount));(DB.payments||[]).filter(x=>x.accountId===id&&x.type!=='چک').forEach(x=>b-=num(x.amount));(DB.expenses||[]).filter(x=>x.accountId===id).forEach(x=>b-=num(x.amount));return b}
  function ledger(k,title,label){const rows=(DB[k]||[]).slice().reverse().map(x=>`<tr><td>${esc(x.jDate)}</td><td>${esc(x.title||x.description||'—')}</td><td>${fmt(x.amount)}</td><td>${esc(x.accountId||'—')}</td></tr>`).join('');return box(title,`<div class="row">${input(k+'Date','تاریخ','text',today())}${input(k+'Title',label)}${input(k+'Amount','مبلغ','number')}${select(k+'Account',DB.accounts||[],'حساب')}</div>`,btn('add-'+k,'ثبت','s'))+box('سوابق',table(['تاریخ','شرح','مبلغ','حساب'],rows));}
  function expenses(){return ledger('expenses','هزینه‌ها','شرح هزینه')} function incomes(){return ledger('incomes','درآمدهای متفرقه','شرح درآمد')}
  function prices(){return box('قیمت‌های مؤثر از تاریخ',`<div class="row">${select('priceProduct',productsList(),'کالا')}${input('priceValue','قیمت','number')}${input('priceDate','تاریخ اعتبار','text',today())}</div>`,btn('addPrice','ثبت قیمت','s'))+box('تاریخچه',table(['کالا','قیمت','تاریخ'],(DB.prices||[]).slice().reverse().map(x=>`<tr><td>${esc(DB.getProduct(x.productId)?.name||'—')}</td><td>${fmt(x.price)}</td><td>${esc(x.effectiveDate)}</td></tr>`).join('')));}
  function reports(){return box('گزارش‌ها',`<div class="row">${input('reportDate','تا تاریخ','text',today())}<div><label>گزارش</label><select id="reportType"><option>مانده مشتریان</option><option>فروش</option><option>دریافت</option><option>موجودی</option><option>صندوق و بانک</option></select></div></div>`,btn('runReport','اجرای گزارش','s'))+box('خلاصه',`تاریخ گزارش: <b>${today()}</b> — گزارش‌ها از داده‌های اصلی و موتور محاسبات تولید می‌شوند.`);}
  function settings(){return box('تنظیمات',`<div class="row">${input('setCurrency','واحد پول','text',DB.settings.currency||'ریال')}${input('setBasis','مبنای روزشمار','number',DB.settings.dayBasis||30)}${input('setGrace','مهلت سیاست چک برگشتی','number',DB.settings.graceDays||30)}${input('setPin','PIN','password',DB.settings.pin||'')}</div><h4>طبقات سود روزشمار</h4>${table(['طبقه','حد روز','نرخ'],(DB.settings.tiers||[]).map((t,i)=>`<tr><td>${i+1}</td><td>${fmt(t.maxDays)}</td><td>${Number(t.rate||0)*100}%</td></tr>`).join(''))}`,btn('saveSettings','ذخیره تنظیمات','s'))}
  function backup(){return box('پشتیبان',`<div class="hint">تمام جداول، تنظیمات و Audit در یک فایل JSON ذخیره می‌شوند.</div>`,btn('exportBackup','دریافت پشتیبان JSON','s')+' '+btn('importBackup','بازیابی JSON','g'))}
  function audit(){return box('رویدادها',table(['زمان','عملیات','جدول','شناسه','شرح'],(DB.audit||[]).slice().reverse().map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.action)}</td><td>${esc(x.table)}</td><td>${esc(x.recordId)}</td><td>${esc(x.note)}</td></tr>`).join('')))}
  const views={dashboard,people,products,sales,saleReturns,receipts,checksIn,statement,purchases,purchaseReturns,payments,checksOut,cashbank,expenses,incomes,prices,reports,settings,backup,audit};
  function nav(){$('nav').innerHTML=MODEL.tabs.map(t=>`<button data-tab="${t[0]}" class="${window._tab===t[0]?'on':''}">${t[1]}</button>`).join('')}
  function render(){nav();$('main').innerHTML=(views[window._tab]||dashboard)();bind()}
  function bind(){
    $('nav').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;window._tab=b.dataset.tab;render()};
    $('main').querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{window._role=b.dataset.role;render()});
    $('main').onclick=e=>{const id=e.target.id||'';
      if(id.startsWith('delperson-')){DB.people=DB.people.filter(x=>x.id!==id.slice(10));DB.save('people');render();return}
      if(id.startsWith('delproduct-')){DB.products=DB.products.filter(x=>x.id!==id.slice(11));DB.save('products');render();return}
      if(id.startsWith('delsale-')){DB.sales=DB.sales.filter(x=>x.id!==id.slice(8));DB.save('sales');render();return}
      if(id.startsWith('delreceipt-')){DB.receipts=DB.receipts.filter(x=>x.id!==id.slice(10));DB.save('receipts');render();return}
      if(id.startsWith('delcheck-')){DB.checks=DB.checks.filter(x=>x.id!==id.slice(9));DB.save('checks');render();return}
      if(id==='addPerson'){const role=window._role||'customer';if(!$('pName').value)return toast('نام الزامی است','d');record('people',{name:$('pName').value,code:$('pCode').value,company:$('pCompany').value,phone:$('pPhone').value,openingBalance:num($('pOpening').value),role},'ثبت شخص');render();return}
      if(id==='addProduct'){if(!$('prName').value)return toast('نام کالا الزامی است','d');record('products',{code:$('prCode').value,name:$('prName').value,category:$('prCat').value,unit:$('prUnit').value||'عدد',packageUnit:$('prPkg').value,ppp:num($('prPpp').value)||1,kind:$('prKind').value},'ثبت کالا');render();return}
      if(id==='addSale'){const gross=num($('saleQty').value)*num($('salePrice').value),disc=num($('saleDiscount').value);if(!$('saleCustomer').value||!$('saleProduct').value||gross<=0||disc>gross)return toast('اطلاعات فاکتور را کامل و صحیح کنید','d');record('sales',{customerId:$('saleCustomer').value,productId:$('saleProduct').value,invoiceNo:$('saleNo').value,jDate:$('saleDate').value,dueDate:$('saleDue').value,qty:num($('saleQty').value),unitPrice:num($('salePrice').value),grossAmount:gross,discount:disc,netAmount:gross-disc,amount:gross-disc},'ثبت فروش');render();return}
      if(id==='addSaleReturn'){record('saleReturns',{customerId:$('srCustomer').value,productId:$('srProduct').value,qty:num($('srQty').value),amount:num($('srAmount').value),jDate:$('srDate').value,referenceId:$('srRef').value},'ثبت برگشت فروش');render();return}
      if(id==='addReceipt'){const r={customerId:$('recCustomer').value,type:$('recType').value,amount:num($('recAmount').value),jDate:$('recDate').value,dueDate:$('recDue').value,status:$('recStatus').value,accountId:$('recBank').value,description:$('recDesc').value};if(!r.customerId||r.amount<=0)return toast('مشتری و مبلغ را کامل کنید','d');record('receipts',r,'ثبت دریافت');if(r.type==='چک')record('checks',{customerId:r.customerId,amount:r.amount,jDate:r.jDate,issueDate:r.jDate,dueDate:r.dueDate,status:r.status,direction:'in',accountId:r.accountId},'ایجاد چک دریافتی');render();return}
      if(id==='addCheckIn'){const r={customerId:$('ciCustomer').value,checkNo:$('ciNo').value,amount:num($('ciAmount').value),jDate:$('ciIssue').value,issueDate:$('ciIssue').value,dueDate:$('ciDue').value,bank:$('ciBank').value,account:$('ciAccount').value,status:$('ciStatus').value,direction:'in'};if(!r.customerId||r.amount<=0||!r.dueDate)return toast('اطلاعات چک ناقص است','d');record('checks',r,'ثبت چک دریافتی');render();return}
      if(id==='addPurchase'){const amount=num($('puQty').value)*num($('puPrice').value)-num($('puDiscount').value);if(!$('puSupplier').value||!$('puProduct').value||amount<=0)return toast('اطلاعات خرید را کامل کنید','d');record('purchases',{supplierId:$('puSupplier').value,productId:$('puProduct').value,invoiceNo:$('puNo').value,jDate:$('puDate').value,qty:num($('puQty').value),unitPrice:num($('puPrice').value),discount:num($('puDiscount').value),amount},'ثبت خرید');render();return}
      if(id==='addPurchaseReturn'){record('purchaseReturns',{supplierId:$('purSupplier').value,productId:$('purProduct').value,qty:num($('purQty').value),amount:num($('purAmount').value),jDate:$('purDate').value,referenceId:$('purRef').value},'ثبت برگشت خرید');render();return}
      if(id==='addPayment'){const r={payeeId:$('pmtPayee').value,type:$('pmtType').value,amount:num($('pmtAmount').value),jDate:$('pmtDate').value,dueDate:$('pmtDue').value,accountId:$('pmtBank').value,description:$('pmtDesc').value};if(!r.payeeId||r.amount<=0)return toast('طرف حساب و مبلغ را کامل کنید','d');record('payments',r,'ثبت پرداخت');if(r.type==='چک')record('checks',{payeeId:r.payeeId,amount:r.amount,jDate:r.jDate,issueDate:r.jDate,dueDate:r.dueDate,status:'صادر شده',direction:'out',accountId:r.accountId},'ایجاد چک پرداختی');render();return}
      if(id==='addCheckOut'){const r={payeeId:$('coPayee').value,checkNo:$('coNo').value,amount:num($('coAmount').value),jDate:$('coIssue').value,issueDate:$('coIssue').value,dueDate:$('coDue').value,bank:$('coBank').value,account:$('coAccount').value,status:$('coStatus').value,direction:'out'};if(!r.payeeId||r.amount<=0||!r.dueDate)return toast('اطلاعات چک ناقص است','d');record('checks',r,'ثبت چک پرداختی');render();return}
      if(id==='addAccount'){if(!$('accName').value)return toast('نام حساب الزامی است','d');record('accounts',{name:$('accName').value,code:$('accCode').value,type:$('accType').value,openingBalance:num($('accOpening').value)},'ثبت حساب');render();return}
      if(id==='add-expenses'||id==='add-incomes'){const k=id.slice(4);record(k,{jDate:$(k+'Date').value,title:$(k+'Title').value,amount:num($(k+'Amount').value),accountId:$(k+'Account').value},k==='expenses'?'ثبت هزینه':'ثبت درآمد');render();return}
      if(id==='addPrice'){record('prices',{productId:$('priceProduct').value,price:num($('priceValue').value),effectiveDate:$('priceDate').value},'ثبت قیمت');render();return}
      if(id==='calcStatement'){window._statementDate=$('stmtDate').value;render();return}
      if(id==='saveSettings'){DB.settings.currency=$('setCurrency').value;DB.settings.dayBasis=num($('setBasis').value)||30;DB.settings.graceDays=num($('setGrace').value)||30;DB.settings.pin=$('setPin').value;DB.save('settings');toast('تنظیمات ذخیره شد','s');return}
      if(id==='exportBackup'){const state={version:2};['people','products','prices','sales','receipts','payments','checks','purchases','saleReturns','purchaseReturns','accounts','transfers','expenses','incomes','adjustments','audit','settings'].forEach(k=>state[k]=DB[k]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='accounting-backup.json';a.click();return}
      if(id==='importBackup'){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);Object.keys(x).forEach(k=>{if(Array.isArray(DB[k])){DB[k]=x[k];DB.save(k)}});if(x.settings){DB.settings=x.settings;DB.save('settings')}location.reload()}catch(e){toast('پشتیبان نامعتبر است','d')}};rd.readAsText(f)};i.click()}
    };
  }
  root.AccountingV2={start:()=>{window._tab='dashboard';nav();render()},MODEL};
})(globalThis);
