'use strict';
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.AccountingModules=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const ERR={INVALID_UNIT_CONVERSION:'INVALID_UNIT_CONVERSION',INVALID_TRANSFER:'INVALID_WAREHOUSE_TRANSFER',STOCK_SHORTAGE:'STOCK_SHORTAGE',INVALID_PURCHASE:'INVALID_PURCHASE',INVALID_PRODUCTION:'INVALID_PRODUCTION',FORMULA_NOT_FOUND:'FORMULA_NOT_FOUND',FORMULA_CIRCULAR:'FORMULA_CIRCULAR',INVALID_CAPITAL:'INVALID_CAPITAL',OWNERSHIP_TOTAL_INVALID:'OWNERSHIP_TOTAL_INVALID',SHARE_TRANSFER_INVALID:'SHARE_TRANSFER_INVALID',INVALID_PAYROLL:'INVALID_PAYROLL',DUPLICATE_CHECK_REPLACEMENT:'DUPLICATE_CHECK_REPLACEMENT'};
function n(x){const v=Number(x);return Number.isFinite(v)?v:0;} function assertPos(x,code){if(n(x)<=0)throw new Error(code);}
function normalizeConversion(x){if(!x||!x.fromUnit||!x.toUnit||n(x.factor)<=0)throw new Error(ERR.INVALID_UNIT_CONVERSION);return Object.freeze({id:x.id||null,productId:x.productId||null,fromUnit:x.fromUnit,toUnit:x.toUnit,factor:n(x.factor),effectiveDate:x.effectiveDate||null,version:x.version||1});}
function convert(quantity,conversion){assertPos(quantity,ERR.INVALID_UNIT_CONVERSION);return n(quantity)*normalizeConversion(conversion).factor;}
function stock(movements,productId,warehouseId,asOf){return (movements||[]).filter(x=>x.productId===productId&&x.warehouseId===warehouseId&&(!asOf||String(x.jDate)<=String(asOf))).reduce((s,x)=>s+n(x.baseQty),0);}
function reconcileInventory(movements,counts){const keys=new Set([...(movements||[]).map(x=>x.productId+'|'+x.warehouseId),...(counts||[]).map(x=>x.productId+'|'+x.warehouseId)]);return [...keys].map(k=>{const [productId,warehouseId]=k.split('|');const ledgerQty=stock(movements,productId,warehouseId);const row=(counts||[]).find(x=>x.productId===productId&&x.warehouseId===warehouseId);const countedQty=row?n(row.countedQty):0;return {productId,warehouseId,ledgerQty,countedQty,difference:countedQty-ledgerQty};});}
function transferWarehouse(x,currentStock){if(!x||!x.transferId||!x.productId||!x.fromWarehouseId||!x.toWarehouseId||x.fromWarehouseId===x.toWarehouseId||n(x.baseQty)<=0)throw new Error(ERR.INVALID_TRANSFER);if(n(currentStock)<n(x.baseQty))throw new Error(ERR.STOCK_SHORTAGE);const q=n(x.baseQty);return Object.freeze([{id:x.transferId+'-OUT',transferId:x.transferId,productId:x.productId,warehouseId:x.fromWarehouseId,jDate:x.jDate,type:'transferOut',baseQty:-q,source:'WAREHOUSE_TRANSFER',sourceId:x.transferId},{id:x.transferId+'-IN',transferId:x.transferId,productId:x.productId,warehouseId:x.toWarehouseId,jDate:x.jDate,type:'transferIn',baseQty:q,source:'WAREHOUSE_TRANSFER',sourceId:x.transferId}]);}
function purchase(x){if(!x||!x.supplierId||!x.productId||n(x.quantity)<=0||n(x.unitPrice)<0)throw new Error(ERR.INVALID_PURCHASE);const amount=n(x.amount)||n(x.quantity)*n(x.unitPrice);return Object.freeze({id:x.id,OperationType:'PURCHASE',supplierId:x.supplierId,productId:x.productId,warehouseId:x.warehouseId||'RM',quantity:n(x.quantity),baseQuantity:n(x.baseQuantity||x.quantity),supplierPrice:n(x.supplierPrice??x.unitPrice),purchasePrice:n(x.unitPrice),freight:n(x.freight),unloading:n(x.unloading),costBasis:n(x.costBasis??(amount+n(x.freight)+n(x.unloading))),amount,jDate:x.jDate,status:'POSTED'});}
function purchaseEffects(row){return [{EffectType:'INVENTORY_IN',RecordID:row.id,Quantity:row.baseQuantity,Unit:'BASE',Amount:row.costBasis},{EffectType:'SUPPLIER_LIABILITY',RecordID:row.id,Amount:row.amount+n(row.freight)+n(row.unloading)}];}
function effectiveConversion(conversions,productId,fromUnit,toUnit,date){return (conversions||[]).filter(x=>x.productId===productId&&x.fromUnit===fromUnit&&x.toUnit===toUnit&&String(x.effectiveDate)<=String(date)).slice().sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate))||n(b.version)-n(a.version))[0]||null;}
function formulaOutput(formula,qty,actualDate,formulas){const f=(formulas||[]).find(x=>x.id===formula.formulaId&&x.productId===formula.productId&&String(x.effectiveDate)<=String(actualDate));if(!f)throw new Error(ERR.FORMULA_NOT_FOUND);return (f.outputs||[]).map(o=>({productId:o.productId,goodQty:n(qty)*n(o.qtyPerBatch),unit:o.unit,formulaId:f.id,formulaVersion:f.version}));}
function validateFormulaGraph(formulas){const graph=new Map((formulas||[]).map(f=>[f.id,(f.inputs||[]).filter(x=>x.formulaId).map(x=>x.formulaId)]));const visiting=new Set(),done=new Set();function dfs(id){if(visiting.has(id))throw new Error(ERR.FORMULA_CIRCULAR);if(done.has(id))return;visiting.add(id);for(const x of graph.get(id)||[])dfs(x);visiting.delete(id);done.add(id);}for(const id of graph.keys())dfs(id);return true;}
function production(x,formulas){if(!x||!x.id||!x.formulaId||!x.productId||n(x.actualQty)<=0)throw new Error(ERR.INVALID_PRODUCTION);validateFormulaGraph(formulas);const outputs=formulaOutput({formulaId:x.formulaId,productId:x.productId},n(x.actualQty),x.jDate,formulas);const waste=n(x.wasteQty);return Object.freeze({id:x.id,OperationType:'PRODUCTION',formulaId:x.formulaId,productId:x.productId,jDate:x.jDate,goodQty:outputs.reduce((s,o)=>s+o.goodQty,0),wasteQty:waste,outputs,manualUnitCost:x.manualUnitCost==null?null:n(x.manualUnitCost),historicalCostBasis:x.historicalCostBasis==null?null:n(x.historicalCostBasis),status:'POSTED'});}
function productionEffects(row){const out=[{EffectType:'PRODUCTION_OUT',RecordID:row.id,Quantity:row.goodQty+row.wasteQty,Amount:null},{EffectType:'PRODUCTION_IN',RecordID:row.id,Quantity:row.goodQty,Amount:row.historicalCostBasis==null?null:row.historicalCostBasis*row.goodQty}];if(row.wasteQty>0)out.push({EffectType:'WASTE',RecordID:row.id,Quantity:row.wasteQty,Amount:null});return out;}
function snapshotCost(costRows,asOf){return (costRows||[]).filter(x=>String(x.effectiveDate)<=String(asOf)).slice().sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate))||String(b.id).localeCompare(String(a.id)))[0]||null;}
function checkStatusTransition(current,to){const allowed={'نزد ما':['تودیع‌شده','وصول شده','برگشتی','باطل'],'تودیع‌شده':['وصول شده','برگشتی','باطل'],'وصول شده':['برگشتی','باطل'],'برگشتی':[],'باطل':[]};if(current===to)return false;if(!allowed[current]||!allowed[current].includes(to))throw new Error('INVALID_CHECK_STATUS_TRANSITION');return true;}
function replaceCheck(original,replacement){if(!original||!replacement||!original.id||!replacement.id||original.id===replacement.id)throw new Error(ERR.DUPLICATE_CHECK_REPLACEMENT);return Object.freeze({...replacement,originalReceiptId:original.id,replacementOfReceiptId:original.id,status:replacement.type==='چک'?(replacement.status||'نزد ما'):'وصول شده'});}
function accountTransfer(x){if(!x||!x.id||!x.sourceAccountId||!x.destinationAccountId||x.sourceAccountId===x.destinationAccountId||n(x.amount)<=0)throw new Error('INVALID_TREASURY_TRANSFER');return Object.freeze([{EffectType:'TREASURY_OUT',RecordID:x.id,AccountID:x.sourceAccountId,Amount:-n(x.amount)},{EffectType:'TREASURY_IN',RecordID:x.id,AccountID:x.destinationAccountId,Amount:n(x.amount)}]);}
function capitalEvent(x){if(!x||!x.id||!x.personId||n(x.amount)<=0||!['CONTRIBUTION','WITHDRAWAL'].includes(x.eventType))throw new Error(ERR.INVALID_CAPITAL);return Object.freeze({...x,amount:n(x.amount),status:'POSTED'});}
function validateOwnership(rows){const total=(rows||[]).filter(x=>x.active!==false).reduce((s,x)=>s+n(x.ownershipPercent),0);if(Math.abs(total-100)>1e-9)throw new Error(ERR.OWNERSHIP_TOTAL_INVALID);return true;}
function transferShare(x,ownership){if(!x||!x.id||!x.fromPartnerId||!x.toPartnerId||x.fromPartnerId===x.toPartnerId||n(x.percent)<=0)throw new Error(ERR.SHARE_TRANSFER_INVALID);const rows=(ownership||[]).map(r=>({...r}));const from=rows.find(r=>r.partnerId===x.fromPartnerId&&r.active!==false),to=rows.find(r=>r.partnerId===x.toPartnerId&&r.active!==false);if(!from||n(from.ownershipPercent)<n(x.percent))throw new Error(ERR.SHARE_TRANSFER_INVALID);if(!to)rows.push({partnerId:x.toPartnerId,ownershipPercent:0,active:true});from.ownershipPercent-=n(x.percent);rows.find(r=>r.partnerId===x.toPartnerId).ownershipPercent+=n(x.percent);validateOwnership(rows);return Object.freeze(rows);}
function payroll(x){if(!x||!x.employeeId||!x.period||n(x.grossPay)<0)throw new Error(ERR.INVALID_PAYROLL);const employerCost=n(x.grossPay)+n(x.employerContribution)+n(x.otherEmployerCost);return Object.freeze({...x,grossPay:n(x.grossPay),employeeDeduction:n(x.employeeDeduction),employerContribution:n(x.employerContribution),otherEmployerCost:n(x.otherEmployerCost),employerCost,status:'POSTED'});}
function expense(x){if(!x||!x.id||n(x.amount)<=0)throw new Error('INVALID_EXPENSE');return Object.freeze({...x,amount:n(x.amount),status:'POSTED'});} function income(x){if(!x||!x.id||n(x.amount)<=0)throw new Error('INVALID_INCOME');return Object.freeze({...x,amount:n(x.amount),status:'POSTED'});}
function returnSale(x){if(!x||!x.id||!x.originalSaleId||n(x.quantity)<=0)throw new Error('INVALID_SALE_RETURN');return Object.freeze({...x,OperationType:'RETURN',ReturnType:'SALE',status:'POSTED'});} function returnPurchase(x){if(!x||!x.id||!x.originalPurchaseId||n(x.quantity)<=0)throw new Error('INVALID_PURCHASE_RETURN');return Object.freeze({...x,OperationType:'RETURN',ReturnType:'PURCHASE',status:'POSTED'});}
return{ERR,normalizeConversion,convert,reconcileInventory,stock,transferWarehouse,purchase,purchaseEffects,effectiveConversion,validateFormulaGraph,formulaOutput,production,productionEffects,snapshotCost,checkStatusTransition,replaceCheck,accountTransfer,capitalEvent,validateOwnership,transferShare,payroll,expense,income,returnSale,returnPurchase};
});
