"use strict";
(function(root,factory){var api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;root.DateEngine=api.DateEngine;root.Finance=api.Finance;})(typeof globalThis!=="undefined"?globalThis:this,function(){
function p2(n){return n<10?'0'+n:''+n} function dv(a,b){return Math.floor(a/b)}
function g2j(gy,gm,gd){var m=[0,31,59,90,120,151,181,212,243,273,304,334],jy=gy>1600?979:0;gy-=gy>1600?1600:621;var gy2=gm>2?gy+1:gy,d=365*gy+dv(gy2+3,4)-dv(gy2+99,100)+dv(gy2+399,400)-80+gd+m[gm-1];jy+=33*dv(d,12053);d%=12053;jy+=4*dv(d,1461);d%=1461;if(d>365){jy+=dv(d-1,365);d=(d-1)%365}var jm=d<186?1+dv(d,31):7+dv(d-186,30),jd=1+(d<186?d%31:(d-186)%30);return[jy,p2(jm),p2(jd)]}
function j2g(jy,jm,jd){jy+=1595;var d=-355668+365*jy+dv(jy,33)*8+dv((jy%33)+3,4)+jd+(jm<7?(jm-1)*31:(jm-7)*30+186),gy=400*dv(d,146097);d%=146097;if(d>36524){gy+=100*dv(d-1,36524);d=(d-1)%36524;if(d>=365)d++}gy+=4*dv(d,1461);d%=1461;if(d>365){gy+=dv(d-1,365);d=(d-1)%365}var gd=d+1,md=[0,31,((gy%4===0&&gy%100!==0)||gy%400===0)?29:28,31,30,31,30,31,31,30,31,30,31],gm=1;while(gm<=12&&gd>md[gm]){gd-=md[gm];gm++}return[gy,gm,gd]}
function parseJ(s){if(Array.isArray(s))return s.map(Number);var m=String(s||'').match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})$/);if(!m)return null;var y=+m[1],mo=+m[2],d=+m[3];if(mo<1||mo>12||d<1||d>(mo<=6?31:mo<=11?30:31))return null;return[y,mo,d]}
function diffJ(a,b){var x=j2g(a[0],a[1],a[2]),y=j2g(b[0],b[1],b[2]);return Math.round((Date.UTC(y[0],y[1]-1,y[2])-Date.UTC(x[0],x[1]-1,x[2]))/86400000)}
function getMultiplier(days,tiers,basis){days=Math.max(0,Number(days)||0);basis=Number(basis)||30;var act=(tiers||[]).filter(function(t){return t.active!==false}).slice().sort(function(a,b){return Number(a.maxDays)-Number(b.maxDays)});if(!act.length)return 1;var sel=act[act.length-1];for(var i=0;i<act.length;i++)if(days<=Number(act[i].maxDays)){sel=act[i];break}return 1+(Number(sel.rate)||0)*days/basis}
function effectiveReceipt(r,calcDate){if(!r||r.status==='باطل')return false;if(r.type!=='چک')return r.status!=='برگشتی'&&String(r.jDate)<=String(calcDate);if(r.status==='وصول شده')return String(r.jDate)<=String(calcDate);if(r.status==='برگشتی')return false;return String(r.dueDate||r.jDate)<=String(calcDate)}
function fifo(input){input=input||{};var cid=input.customerId,calc=input.calcDate;if(!parseJ(calc))throw Error('calcDate must be YYYY/MM/DD');var settings=input.settings||{dayBasis:30,tiers:[]};var sales=(input.sales||[]).filter(function(x){return x.customerId===cid&&parseJ(x.jDate)&&String(x.jDate)<=String(calc)&&x.status!=='باطل'}).slice().sort(function(a,b){return String(a.jDate).localeCompare(String(b.jDate))||String(a.id).localeCompare(String(b.id))});var returns=(input.saleReturns||[]).filter(function(x){return x.customerId===cid&&parseJ(x.jDate)&&String(x.jDate)<=String(calc)&&x.status!=='باطل'}),ret={};returns.forEach(function(x){if(x.referenceId)ret[x.referenceId]=(ret[x.referenceId]||0)+(Number(x.amount)||0)});var alloc=sales.map(function(s){var o=Math.max(0,(Number(s.netAmount??s.amount??0)||0)-(ret[s.id]||0));return{sale:s,orig:o,remaining:o,days:0,mult:1,settlement:0,interest:0}});var receipts=(input.receipts||[]).filter(function(r){return r.customerId===cid&&effectiveReceipt(r,calc)}).slice().sort(function(a,b){var ad=a.type==='چک'?(a.dueDate||a.jDate):a.jDate,bd=b.type==='چک'?(b.dueDate||b.jDate):b.jDate;return String(ad).localeCompare(String(bd))||String(a.id).localeCompare(String(b.id))});receipts.forEach(function(r){var rem=Number(r.amount)||0,rd=r.type==='چک'?(r.dueDate||r.jDate):r.jDate;for(var i=0;i<alloc.length&&rem>0;i++){var a=alloc[i];if(a.remaining<=0)continue;if(String(a.sale.jDate)>String(rd))break;var take=Math.min(rem,a.remaining);a.remaining-=take;rem-=take}});var totalOrig=alloc.reduce(function(n,a){return n+a.orig},0),remaining=alloc.reduce(function(n,a){return n+a.remaining},0),effective=receipts.reduce(function(n,r){return n+(Number(r.amount)||0)},0),credit=Math.max(0,effective-(totalOrig-remaining)),futureChecks=0,returnedChecks=0;(input.checks||[]).filter(function(x){return x.direction!=='out'&&x.customerId===cid}).forEach(function(c){if(c.status==='برگشتی')returnedChecks+=Number(c.amount)||0;else if(c.status!=='باطل'&&String(c.dueDate||'')>String(calc))futureChecks+=Number(c.amount)||0});var totalInt=0,totalSV=0;alloc.forEach(function(a){if(a.remaining<=0)return;a.days=Math.max(0,diffJ(parseJ(a.sale.jDate),parseJ(calc)));a.mult=getMultiplier(a.days,settings.tiers,settings.dayBasis);a.settlement=a.remaining*a.mult;a.interest=a.settlement-a.remaining;totalInt+=a.interest;totalSV+=a.settlement});return{alloc:alloc,credit:credit,totalInt:totalInt,totalRem:remaining,totalSV:totalSV,totalOrig:totalOrig,futureChecks:futureChecks,returnedChecks:returnedChecks,totalEffective:effective}}
function customerSummary(input){var f=fifo(input),sales=(input.sales||[]).filter(function(x){return x.customerId===input.customerId&&String(x.jDate)<=String(input.calcDate)&&x.status!=='باطل'}),rets=(input.saleReturns||[]).filter(function(x){return x.customerId===input.customerId&&String(x.jDate)<=String(input.calcDate)&&x.status!=='باطل'});return{totalSales:sales.reduce(function(n,x){return n+Number(x.netAmount??x.amount??0)},0)-rets.reduce(function(n,x){return n+Number(x.amount||0)},0),totalReceipts:f.totalEffective,balance:f.totalRem,principal:f.totalRem,interest:f.totalInt,settlement:f.totalSV,credit:f.credit,futureChecks:f.futureChecks,returnedChecks:f.returnedChecks,engine:f}}
return{DateEngine:{g2j:g2j,j2g:j2g,parseJ:parseJ,diffJ:diffJ},Finance:{getMultiplier:getMultiplier,fifo:fifo,customerSummary:customerSummary,effectiveReceipt:effectiveReceipt}};
});
