'use strict';
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.AccountingDomain=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
function parseJ(s){if(Array.isArray(s))return s.map(Number);const m=String(s||'').match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})$/);return m?[+m[1],+m[2],+m[3]]:null;}
function j2g(jy,jm,jd){jy+=1595;let d=-355668+365*jy+Math.floor(jy/33)*8+Math.floor(((jy%33)+3)/4)+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);let gy=400*Math.floor(d/146097);d%=146097;if(d>36524){gy+=100*Math.floor(--d/36524);d%=36524;if(d>=365)d++;}gy+=4*Math.floor(d/1461);d%=1461;if(d>365){gy+=Math.floor((d-1)/365);d=(d-1)%365;}let gd=d+1,md=[0,31,((gy%4===0&&gy%100!==0)||gy%400===0)?29:28,31,30,31,30,31,31,30,31,30,31];let gm=1;while(gm<=12&&gd>md[gm]){gd-=md[gm];gm++;}return[gy,gm,gd];}
function g2j(gy,gm,gd){const m=[0,31,59,90,120,151,181,212,243,273,304,334];let jy=gy>1600?979:0;gy-=gy>1600?1600:621;const gy2=gm>2?gy+1:gy;let d=365*gy+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)-80+gd+m[gm-1];jy+=33*Math.floor(d/12053);d%=12053;jy+=4*Math.floor(d/1461);d%=1461;if(d>365){jy+=Math.floor((d-1)/365);d=(d-1)%365;}return[jy,d<186?1+Math.floor(d/31):7+Math.floor((d-186)/30),1+(d<186?d%31:(d-186)%30)];}
function diffJ(a,b){const x=j2g(...parseJ(a)),y=j2g(...parseJ(b));return Math.round((Date.UTC(y[0],y[1]-1,y[2])-Date.UTC(x[0],x[1]-1,x[2]))/86400000);}
function getMultiplier(days,tiers,basis){days=Math.max(0,Number(days)||0);basis=Number(basis)||30;const active=(tiers||[]).filter(t=>t.active!==false).slice().sort((a,b)=>Number(a.maxDays)-Number(b.maxDays));if(!active.length)return 1;let selected=active[active.length-1];for(const t of active){if(days<=Number(t.maxDays)){selected=t;break;}}return 1+(Number(selected.rate)||0)*days/basis;}
function tiersForSale(sale,settings){const cfg=settings||{};const packages=Array.isArray(cfg.paymentPackages)?cfg.paymentPackages:[];if(sale&&sale.paymentPackageId){const pack=packages.find(p=>p.id===sale.paymentPackageId);if(pack&&Array.isArray(pack.tiers))return pack.tiers;}return Array.isArray(cfg.tiers)?cfg.tiers:[];}
function buildReceiptAllocations({customerId,calcDate,settings,sales,receipts}){const cfg=settings||{dayBasis:30,tiers:[]};const ss=(sales||[]).filter(s=>s.customerId===customerId&&parseJ(s.jDate)&&String(s.jDate)<=String(calcDate)).slice().sort((a,b)=>String(a.jDate).localeCompare(String(b.jDate))||String(a.id).localeCompare(String(b.id)));const rr=(receipts||[]).filter(r=>r.customerId===customerId&&r.status!=='باطل'&&r.status!=='برگشتی'&&parseJ(r.jDate)&&String(r.jDate)<=String(calcDate)).slice().sort((a,b)=>String(a.jDate).localeCompare(String(b.jDate))||String(a.id).localeCompare(String(b.id)));const alloc=ss.map(s=>({sale:s,remaining:Number(s.amount)||0}));const out=[];let credit=0;for(const r of rr){let rem=Number(r.amount)||0;for(const a of alloc){if(rem<=0)break;if(a.remaining<=0)continue;if(String(a.sale.jDate)>String(r.jDate))break;const days=diffJ(a.sale.jDate,r.jDate),mult=getMultiplier(days,tiersForSale(a.sale,cfg),cfg.dayBasis),settlement=Math.min(rem,a.remaining*mult),principalReduction=settlement/mult;a.remaining-=principalReduction;rem-=settlement;out.push({ReceiptID:r.id,SaleID:a.sale.id,SettlementAmount:settlement,PrincipalReduction:principalReduction,DurationDays:days,Multiplier:mult,PaymentPackageID:a.sale.paymentPackageId||null});}credit+=Math.max(0,rem);}return{rows:out,credit};}
function fifo({customerId,calcDate,settings,sales,receipts}){if(!parseJ(calcDate))throw new Error('calcDate must be YYYY/MM/DD');const built=buildReceiptAllocations({customerId,calcDate,settings,sales,receipts});const rows=built.rows;const ss=(sales||[]).filter(s=>s.customerId===customerId&&parseJ(s.jDate)&&String(s.jDate)<=String(calcDate));const applied=new Map();for(const x of rows)applied.set(x.SaleID,(applied.get(x.SaleID)||0)+x.PrincipalReduction);let totalRem=0,totalInt=0,totalSV=0;for(const s of ss){const rem=Math.max(0,(Number(s.amount)||0)-(applied.get(s.id)||0));if(rem<=0)continue;const days=diffJ(s.jDate,calcDate),mult=getMultiplier(days,tiersForSale(s,settings||{}),(settings||{}).dayBasis);totalRem+=rem;totalInt+=rem*(mult-1);totalSV+=rem*mult;}return{alloc:[],receiptAllocations:rows,credit:built.credit,totalRem,totalInt,totalSV,totalOrig:ss.reduce((n,x)=>n+Number(x.amount||0),0)};}
return{DateEngine:{parseJ,g2j,j2g,diffJ},Finance:{getMultiplier,tiersForSale,buildReceiptAllocations,fifo}};
});
