"use strict";
(function(root,factory){var api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.Inventory=api.Inventory;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function normalizeQty(x){return Number(x.baseQty!=null?x.baseQty:x.qty!=null?x.qty:x.quantity)||0;}
  function signed(row){switch(row.type){case'purchase':case'saleReturn':case'adjustmentIn':case'transferIn':case'productionIn':return normalizeQty(row);case'sale':case'purchaseReturn':case'adjustmentOut':case'transferOut':case'productionOut':return-normalizeQty(row);default:return Number(row.baseQty)||0;}}
  function stock(rows,productId,warehouseId,asOf){return(rows||[]).filter(function(x){return x.productId===productId&&x.warehouseId===warehouseId&&(!asOf||String(x.jDate)<=String(asOf));}).reduce(function(n,x){return n+signed(x);},0);}
  function movements(state,productId,warehouseId,from,to){return(state.inventoryMovements||[]).filter(function(x){return x.productId===productId&&(!warehouseId||x.warehouseId===warehouseId)&&(!from||String(x.jDate)>=String(from))&&(!to||String(x.jDate)<=String(to));}).slice().sort(function(a,b){return String(a.jDate).localeCompare(String(b.jDate))||String(a.id).localeCompare(String(b.id));});}
  function transfer(input){var q=Math.abs(Number(input.baseQty)||0);if(!input.id||!input.productId||!input.fromWarehouseId||!input.toWarehouseId||input.fromWarehouseId===input.toWarehouseId||q<=0)throw Error('INVALID_WAREHOUSE_TRANSFER');return[{id:input.id+'-OUT',transferId:input.id,productId:input.productId,warehouseId:input.fromWarehouseId,jDate:input.jDate,type:'transferOut',baseQty:-q,source:'WAREHOUSE_TRANSFER',sourceId:input.id},{id:input.id+'-IN',transferId:input.id,productId:input.productId,warehouseId:input.toWarehouseId,jDate:input.jDate,type:'transferIn',baseQty:q,source:'WAREHOUSE_TRANSFER',sourceId:input.id}];}
  function applySale(x){return{productId:x.productId,warehouseId:x.warehouseId,type:'sale',baseQty:Math.abs(Number(x.baseQuantity!=null?x.baseQuantity:x.quantity)||0),jDate:x.jDate,source:'SALE',sourceId:x.id};}
  function applyPurchase(x){return{productId:x.productId,warehouseId:x.warehouseId,type:'purchase',baseQty:Math.abs(Number(x.baseQuantity!=null?x.baseQuantity:x.quantity)||0),jDate:x.jDate,source:'PURCHASE',sourceId:x.id};}
  return{Inventory:{stock:stock,movements:movements,transfer:transfer,applySale:applySale,applyPurchase:applyPurchase,signed:signed}};
});
