'use strict';
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.AccountingOperations=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const SENSITIVE=['SALE','RECEIPT','PURCHASE','PAYMENT','TRANSFER','INVENTORY_ADJUSTMENT','WAREHOUSE_TRANSFER','PRODUCTION','RETURN','CHECK_STATUS_CHANGE','CHECK_REPLACEMENT','CAPITAL_EVENT','SHARE_TRANSFER','PAYROLL','EXPENSE','INCOME'];
const ERR={INVALID_OPERATION:'INVALID_OPERATION',INVALID_OPERATION_TYPE:'INVALID_OPERATION_TYPE',IDEMPOTENCY_CONFLICT:'IDEMPOTENCY_CONFLICT',ALREADY_REVERSED:'ALREADY_REVERSED',NOT_FOUND:'NOT_FOUND',NEEDS_REPAIR:'NEEDS_REPAIR'};
class OpError extends Error{constructor(code,msg){super(msg||code);this.code=code;}}
function stable(v){return JSON.stringify(v,Object.keys(v||{}).sort());}
class OperationEngine{
constructor(seed){this.operations=[];this.effects=[];this.audit=[];this.receiptAllocations=[];this.seq=0;this.failAfterEffects=false;Object.assign(this,seed||{});}
id(p){this.seq++;return `${p}-${String(this.seq).padStart(6,'0')}`;}
auditEvent(x){this.audit.push(Object.freeze({...x,AuditID:this.id('AUD'),Timestamp:new Date().toISOString()}));}
execute(req,apply){if(!req||!req.operationType)throw new OpError(ERR.INVALID_OPERATION,'operationType required');if(!SENSITIVE.includes(req.operationType))throw new OpError(ERR.INVALID_OPERATION_TYPE,req.operationType);if(!req.idempotencyKey||!req.actorId)throw new OpError(ERR.INVALID_OPERATION,'idempotencyKey and actorId required');const hash=stable(req.payload||{});const old=this.operations.find(o=>o.IdempotencyKey===req.idempotencyKey);if(old){if(old.PayloadHash!==hash)throw new OpError(ERR.IDEMPOTENCY_CONFLICT,'same key with different payload');return {replayed:true,operation:old,effects:this.effects.filter(e=>e.OperationID===old.OperationID)};}const op={OperationID:this.id('OP'),OperationType:req.operationType,IdempotencyKey:req.idempotencyKey,ActorID:req.actorId,CorrelationID:req.correlationId||this.id('COR'),Status:'PENDING',PayloadHash:hash,OccurredDate:req.occurredDate||null,Source:req.source||'WEB'};this.operations.push(op);this.auditEvent({OperationID:op.OperationID,Action:'PENDING',Result:'OK'});try{const effects=apply?apply(op,req.payload||{}):[];for(const e of effects||[])this.effects.push({...e,EffectID:this.id('EFF'),OperationID:op.OperationID,Status:'POSTED'});if(this.failAfterEffects){op.Status='NEEDS_REPAIR';this.auditEvent({OperationID:op.OperationID,Action:'FAIL_AFTER_EFFECTS',Result:'ERROR',ErrorCode:ERR.NEEDS_REPAIR});throw new OpError(ERR.NEEDS_REPAIR,'effects written; repair required');}op.Status='POSTED';this.auditEvent({OperationID:op.OperationID,Action:'POST',Result:'OK'});return {replayed:false,operation:op,effects:this.effects.filter(e=>e.OperationID===op.OperationID)};}catch(e){if(e.code!==ERR.NEEDS_REPAIR)op.Status='FAILED';throw e;}}
repair(operationId,repairFn){const op=this.operations.find(o=>o.OperationID===operationId);if(!op)throw new OpError(ERR.NOT_FOUND);if(op.Status!=='NEEDS_REPAIR')throw new Error('operation is not repairable');if(repairFn)repairFn(op,this.effects.filter(e=>e.OperationID===operationId));op.Status='POSTED';this.auditEvent({OperationID:operationId,Action:'REPAIR',Result:'OK'});return op;}
reverse(operationId,req){const src=this.operations.find(o=>o.OperationID===operationId);if(!src)throw new OpError(ERR.NOT_FOUND);if(src.Status==='REVERSED')throw new OpError(ERR.ALREADY_REVERSED);if(!req||!req.idempotencyKey||!req.actorId)throw new OpError(ERR.INVALID_OPERATION);const existing=this.operations.find(o=>o.IdempotencyKey===req.idempotencyKey);if(existing)return {replayed:true,operation:existing,effects:this.effects.filter(e=>e.OperationID===existing.OperationID)};const rev=this.execute({operationType:src.OperationType,idempotencyKey:req.idempotencyKey,actorId:req.actorId,correlationId:req.correlationId,source:'REVERSAL',payload:{ReversalOfOperationID:operationId}},()=>this.effects.filter(e=>e.OperationID===operationId).map(e=>({EffectType:'REVERSAL',ReversesEffectID:e.EffectID,Value:-Number(e.Value||0),ReversalOfOperationID:operationId})));src.Status='REVERSED';this.auditEvent({OperationID:operationId,Action:'REVERSE',Result:'OK',ReversalOperationID:rev.operation.OperationID});return rev;}
}
return {OperationEngine,OpError,SENSITIVE,ERR};
});
