'use strict';
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.AccountingOperations=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const SENSITIVE=['SALE','RECEIPT','PURCHASE','PAYMENT','TRANSFER','INVENTORY_ADJUSTMENT','WAREHOUSE_TRANSFER','PRODUCTION','RETURN','CHECK_STATUS_CHANGE','CHECK_REPLACEMENT','CAPITAL_EVENT','SHARE_TRANSFER','PAYROLL','EXPENSE','INCOME'];
const ERR={INVALID_OPERATION:'INVALID_OPERATION',INVALID_OPERATION_TYPE:'INVALID_OPERATION_TYPE',IDEMPOTENCY_CONFLICT:'IDEMPOTENCY_CONFLICT',ALREADY_REVERSED:'ALREADY_REVERSED',NOT_FOUND:'NOT_FOUND',NEEDS_REPAIR:'NEEDS_REPAIR'};
class OpError extends Error{constructor(code,msg){super(msg||code);this.code=code;}}
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';}
function nextSeq(arr,prefix){let n=0;for(const x of arr||[]){const id=String(x.OperationID||x.EffectID||x.AuditID||'');const m=id.match(new RegExp('^'+prefix+'-(\\d+)$'));if(m)n=Math.max(n,Number(m[1]));}return n;}
class OperationEngine{
constructor(seed){this.operations=[];this.effects=[];this.audit=[];this.receiptAllocations=[];Object.assign(this,seed||{});this.seq=Math.max(Number(this.seq)||0,nextSeq(this.operations,'OP'),nextSeq(this.effects,'EFF'),nextSeq(this.audit,'AUD'));}
id(p){this.seq++;return `${p}-${String(this.seq).padStart(6,'0')}`;}
auditEvent(x){this.audit.push(Object.freeze({...x,AuditID:this.id('AUD'),Timestamp:new Date().toISOString()}));}
execute(req,apply){if(!req||!req.operationType)throw new OpError(ERR.INVALID_OPERATION,'operationType required');if(!SENSITIVE.includes(req.operationType))throw new OpError(ERR.INVALID_OPERATION_TYPE,req.operationType);if(!req.idempotencyKey||!req.actorId)throw new OpError(ERR.INVALID_OPERATION,'idempotencyKey and actorId required');const hash=stable(req.payload||{});const old=this.operations.find(o=>o.IdempotencyKey===req.idempotencyKey);if(old){if(old.PayloadHash!==hash)throw new OpError(ERR.IDEMPOTENCY_CONFLICT,'same key with different payload');return {replayed:true,operation:old,effects:this.effects.filter(e=>e.OperationID===old.OperationID)};}const op={OperationID:this.id('OP'),OperationType:req.operationType,IdempotencyKey:req.idempotencyKey,ActorID:req.actorId,CorrelationID:req.correlationId||this.id('COR'),Status:'PENDING',PayloadHash:hash,OccurredDate:req.occurredDate||null,Source:req.source||'WEB'};this.operations.push(op);this.auditEvent({OperationID:op.OperationID,ActorID:op.ActorID,Action:'PENDING',Result:'OK'});try{const effects=apply?apply(op,req.payload||{}):[];for(const e of effects||[])this.effects.push(Object.freeze({...e,EffectID:this.id('EFF'),OperationID:op.OperationID,Status:'POSTED'}));if(this.failAfterEffects){op.Status='NEEDS_REPAIR';this.auditEvent({OperationID:op.OperationID,ActorID:op.ActorID,Action:'FAIL_AFTER_EFFECTS',Result:'ERROR',ErrorCode:ERR.NEEDS_REPAIR});throw new OpError(ERR.NEEDS_REPAIR,'effects written; repair required');}op.Status='POSTED';this.auditEvent({OperationID:op.OperationID,ActorID:op.ActorID,Action:'POST',Result:'OK'});return {replayed:false,operation:op,effects:this.effects.filter(e=>e.OperationID===op.OperationID)};}catch(e){if(e.code!==ERR.NEEDS_REPAIR)op.Status='FAILED';throw e;}}
repair(operationId,repairFn){const op=this.operations.find(o=>o.OperationID===operationId);if(!op)throw new OpError(ERR.NOT_FOUND);if(op.Status!=='NEEDS_REPAIR')throw new Error('operation is not repairable');if(repairFn)repairFn(op,this.effects.filter(e=>e.OperationID===operationId));op.Status='POSTED';this.auditEvent({OperationID:operationId,ActorID:op.ActorID,Action:'REPAIR',Result:'OK'});return op;}
reverse(operationId,req){const src=this.operations.find(o=>o.OperationID===operationId);if(!src)throw new OpError(ERR.NOT_FOUND);if(src.Status==='REVERSED')throw new OpError(ERR.ALREADY_REVERSED);if(src.Status!=='POSTED')throw new OpError(ERR.INVALID_OPERATION,'operation is not posted');if(!req||!req.idempotencyKey||!req.actorId)throw new OpError(ERR.INVALID_OPERATION);const existing=this.operations.find(o=>o.IdempotencyKey===req.idempotencyKey);if(existing){if(existing.Status!=='POSTED')throw new OpError(ERR.INVALID_OPERATION,'reversal operation is not posted');return {replayed:true,operation:existing,effects:this.effects.filter(e=>e.OperationID===existing.OperationID)};}const sourceEffects=this.effects.filter(e=>e.OperationID===operationId&&e.Status==='POSTED'&&!e.ReversesEffectID);const rev=this.execute({operationType:'RETURN',idempotencyKey:req.idempotencyKey,actorId:req.actorId,correlationId:req.correlationId,source:'REVERSAL',payload:{ReversalOfOperationID:operationId}},()=>sourceEffects.map(e=>({EffectType:'REVERSAL',ReversesEffectID:e.EffectID,Value:e.Value==null?null:-Number(e.Value),Quantity:e.Quantity==null?null:-Number(e.Quantity),ReversalOfOperationID:operationId})));src.Status='REVERSED';src.ReversedByOperationID=rev.operation.OperationID;this.auditEvent({OperationID:operationId,ActorID:req.actorId,Action:'REVERSE',Result:'OK',ReversalOperationID:rev.operation.OperationID});return rev;}
}
return {OperationEngine,OpError,SENSITIVE,ERR};
});
