'use strict';
const crypto=require('node:crypto');
const {Finance}=require('./domain.js');
const SENSITIVE_OPERATION_TYPES=Object.freeze(['SALE','RECEIPT','PURCHASE','PAYMENT','TRANSFER','INVENTORY_ADJUSTMENT','WAREHOUSE_TRANSFER','PRODUCTION','RETURN','CHECK_STATUS_CHANGE','CHECK_REPLACEMENT','CAPITAL_EVENT','SHARE_TRANSFER','PAYROLL','EXPENSE','INCOME']);
const STATUS=Object.freeze({PENDING:'PENDING',POSTED:'POSTED',FAILED:'FAILED',NEEDS_REPAIR:'NEEDS_REPAIR',REVERSED:'REVERSED'});
function stablePayload(payload){if(payload===undefined)return'undefined';if(payload===null||typeof payload!=='object')return JSON.stringify(payload);if(Array.isArray(payload))return'['+payload.map(stablePayload).join(',')+']';return'{'+Object.keys(payload).sort().map(k=>JSON.stringify(k)+':'+stablePayload(payload[k])).join(',')+'}';}
function makeId(prefix,seq){return`${prefix}-${String(seq).padStart(6,'0')}`;}
class ContractEngine{
constructor(){this.operations=new Map();this.effects=new Map();this.auditLog=[];this.schemas=new Map();this.allocations=new Map();this.sales=new Map();this.receipts=new Map();this._seq={OP:0,EF:0,AU:0,AL:0};}
nextId(prefix){this._seq[prefix]=(this._seq[prefix]||0)+1;return makeId(prefix,this._seq[prefix]);}
registerSchema(schema){if(!schema||!schema.tableName||!schema.primaryKey||!Array.isArray(schema.columns))throw new Error('SCHEMA_INVALID');this.schemas.set(schema.tableName,structuredClone(schema));}
validateSchema(tableName,rows=[]){const schema=this.schemas.get(tableName);if(!schema)throw new Error('SCHEMA_INVALID');const names=new Set(schema.columns.map(c=>typeof c==='string'?c:c.name));for(const row of rows){for(const key of Object.keys(row))if(!names.has(key))throw new Error(`SCHEMA_INVALID:UNKNOWN_FIELD:${key}`);for(const col of schema.columns){const c=typeof col==='string'?{name:col}:col;if(c.required&&(row[c.name]===undefined||row[c.name]===null||row[c.name]===''))throw new Error(`SCHEMA_INVALID:REQUIRED:${c.name}`)}}return true;}
_audit(event){const row=Object.freeze({AuditID:this.nextId('AU'),Timestamp:new Date().toISOString(),...event});this.auditLog.push(row);return row;}
execute(req){if(!req||!req.operationType||!req.idempotencyKey||!req.payload)throw new Error('INVALID_OPERATION');if(!SENSITIVE_OPERATION_TYPES.includes(req.operationType))throw new Error('INVALID_OPERATION_TYPE');const payloadHash=crypto.createHash('sha256').update(stablePayload(req.payload)).digest('hex');const prior=[...this.operations.values()].find(o=>o.IdempotencyKey===req.idempotencyKey);if(prior){if(prior.PayloadHash!==payloadHash)throw new Error('IDEMPOTENCY_CONFLICT');return{replayed:true,operation:prior,effects:[...this.effects.values()].filter(e=>e.OperationID===prior.OperationID)};}if(req.schemaChecks)for(const c of req.schemaChecks)this.validateSchema(c.tableName,c.rows||[]);const operation=Object.freeze({OperationID:this.nextId('OP'),OperationType:req.operationType,IdempotencyKey:req.idempotencyKey,CorrelationID:req.correlationId||req.idempotencyKey,PayloadHash:payloadHash,Status:STATUS.PENDING,RecordID:req.recordId||null,TableName:req.tableName||null,OccurredDate:req.occurredDate||null,EngineVersion:req.engineVersion||'phase05-1.0'});this.operations.set(operation.OperationID,operation);this._audit({OperationID:operation.OperationID,CorrelationID:operation.CorrelationID,IdempotencyKey:operation.IdempotencyKey,Action:'OPERATION_CREATED',Table:operation.TableName,RecordID:operation.RecordID,Result:'PENDING'});try{const effects=(req.effects||[]).map((e,i)=>Object.freeze({EffectID:this.nextId('EF'),OperationID:operation.OperationID,EffectIndex:i,EffectType:e.effectType||'GENERIC',RecordID:e.recordId||operation.RecordID,Amount:e.amount===undefined?null:Number(e.amount),Quantity:e.quantity===undefined?null:Number(e.quantity),Before:e.before===undefined?null:structuredClone(e.before),After:e.after===undefined?null:structuredClone(e.after),Status:STATUS.POSTED,ReversesEffectID:null}));effects.forEach(e=>this.effects.set(e.EffectID,e));if(req.failAfterEffects)throw new Error('INJECTED_FAILURE');const posted=Object.freeze({...operation,Status:STATUS.POSTED});this.operations.set(operation.OperationID,posted);this._audit({OperationID:operation.OperationID,CorrelationID:operation.CorrelationID,IdempotencyKey:operation.IdempotencyKey,Action:'OPERATION_POSTED',Table:operation.TableName,RecordID:operation.RecordID,Result:'POSTED'});return{replayed:false,operation:posted,effects};}catch(err){const failed=Object.freeze({...operation,Status:STATUS.NEEDS_REPAIR,ErrorCode:err.code||'EXECUTION_ERROR'});this.operations.set(operation.OperationID,failed);this._audit({OperationID:operation.OperationID,CorrelationID:operation.CorrelationID,IdempotencyKey:operation.IdempotencyKey,Action:'OPERATION_NEEDS_REPAIR',Result:'NEEDS_REPAIR',ErrorMessage:String(err.message||err)});throw err;}}
reverse(operationId,req={}){const source=this.operations.get(operationId);if(!source)throw new Error('NOT_FOUND');if(source.Status===STATUS.REVERSED)throw new Error('ALREADY_REVERSED');if(source.Status!==STATUS.POSTED)throw new Error('INVALID_OPERATION_STATUS');const sourceEffects=[...this.effects.values()].filter(e=>e.OperationID===operationId&&e.Status===STATUS.POSTED&&!e.ReversesEffectID);const reversalKey=req.idempotencyKey||`REV-${operationId}`;const prior=[...this.operations.values()].find(o=>o.IdempotencyKey===reversalKey);if(prior)return{replayed:true,operation:prior,effects:[...this.effects.values()].filter(e=>e.OperationID===prior.OperationID)};const result=this.execute({operationType:'RETURN',idempotencyKey:reversalKey,payload:{reversalOf:operationId,reason:req.reason||''},recordId:source.RecordID,tableName:source.TableName,occurredDate:req.occurredDate||source.OccurredDate,effects:sourceEffects.map(e=>({effectType:'REVERSAL',recordId:e.RecordID,amount:e.Amount===null?null:-e.Amount,quantity:e.Quantity===null?null:-e.Quantity,before:e.After,after:e.Before}))});const reversedEffects=result.effects.map((e,i)=>Object.freeze({...e,ReversesEffectID:sourceEffects[i]?.EffectID||null}));reversedEffects.forEach(e=>this.effects.set(e.EffectID,e));this.operations.set(operationId,Object.freeze({...source,Status:STATUS.REVERSED,ReversedByOperationID:result.operation.OperationID}));this._audit({OperationID:operationId,ReversesOperationID:result.operation.OperationID,Action:'OPERATION_REVERSED',Result:'REVERSED'});return{replayed:false,operation:result.operation,effects:reversedEffects};}
repair(operationId){const op=this.operations.get(operationId);if(!op)throw new Error('NOT_FOUND');if(op.Status!==STATUS.NEEDS_REPAIR)throw new Error('INVALID_OPERATION_STATUS');const repaired=Object.freeze({...op,Status:STATUS.POSTED,RepairedAt:new Date().toISOString()});this.operations.set(operationId,repaired);this._audit({OperationID:operationId,Action:'OPERATION_REPAIRED',Result:'POSTED'});return repaired;}
addSale(sale){this.sales.set(sale.id,structuredClone(sale));}
addReceipt(receipt){this.receipts.set(receipt.id,structuredClone(receipt));}
allocateReceipt(receiptId,calcDate,settings){const r=this.receipts.get(receiptId);if(!r)throw new Error('NOT_FOUND');if(r.status==='باطل'||r.status==='برگشتی')return[];const existing=[...this.allocations.values()].filter(a=>a.ReceiptID===receiptId&&a.Status==='POSTED'&&!a.ReversesAllocationID);if(existing.length)return existing;const rows=Finance.buildReceiptAllocations({customerId:r.customerId,calcDate,settings:settings||{dayBasis:30,tiers:[]},sales:[...this.sales.values()],receipts:[...this.receipts.values()]}).filter(a=>a.ReceiptID===receiptId);return rows.map(a=>{const row=Object.freeze({AllocationID:this.nextId('AL'),OperationID:r.operationId||null,ReceiptID:a.ReceiptID,SaleID:a.SaleID,SettlementAmount:a.SettlementAmount,PrincipalReduction:a.PrincipalReduction,DurationDays:a.DurationDays,Multiplier:a.Multiplier,Version:1,Status:'POSTED',ReversesAllocationID:null});this.allocations.set(row.AllocationID,row);return row;});}
reverseAllocation(allocationId){const source=this.allocations.get(allocationId);if(!source)throw new Error('NOT_FOUND');if(source.Status!=='POSTED'||source.ReversesAllocationID)throw new Error('ALREADY_REVERSED');const row=Object.freeze({...source,AllocationID:this.nextId('AL'),Version:source.Version+1,Status:'POSTED',SettlementAmount:-source.SettlementAmount,PrincipalReduction:-source.PrincipalReduction,ReversesAllocationID:source.AllocationID});this.allocations.set(row.AllocationID,row);return row;}
reconcile(totalSales,netPrincipalApplied){const outstanding=Number(totalSales)-Number(netPrincipalApplied);if(!Number.isFinite(outstanding))throw new Error('RECONCILIATION_FAILED');return{ok:true,totalSales:Number(totalSales),netPrincipalApplied:Number(netPrincipalApplied),totalOutstanding:outstanding};}}
module.exports={ContractEngine,SENSITIVE_OPERATION_TYPES,STATUS,stablePayload};
