'use strict';
(function(root){
let current='dashboard';
const tabs=[['dashboard','داشبورد'],['customers','مشتریان'],['products','کالاها'],['prices','تاریخچه قیمت'],['sales','فروش'],['receipts','دریافت'],['checks','چک‌ها'],['inventory','موجودی'],['production','تولید'],['purchases','خرید'],['payments','پرداخت'],['expenses','هزینه‌ها'],['capital','سرمایه/شرکا'],['reports','حساب جاری'],['settings','تنظیمات']];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const fmt=x=>Math.round(Number(x)||0).toLocaleString('en-US');const opts=a=>a.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');
function table(rows,heads,map){if(!rows.length)return '<p>رکوردی وجود ندارد.</p>';return `<div class="tbl-wrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(x=>`<tr>${map(x).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function box(title,body){return `<section class="bx"><h3>${title}</h3>${body}</section>`;}
const v={
dashboard:()=>{const k=Reports.dashboard();return `<div class="kpi"><div class="k"><div class="l">فروش</div><div class="v">${fmt(k.sales)}</div></div><div class="k"><div class="l">دریافت مؤثر</div><div class="v">${fmt(k.receipts)}</div></div><div class="k"><div class="l">مشتری</div><div class="v">${k.customers}</div></div><div class="k"><div class="l">عملیات</div><div class="v">${k.operations}</div></div></div>${box('وضعیت پروژه','<p>این نسخه، پروژه تدوین‌شده را مبنای اجرا قرار می‌دهد؛ prototype قبلی مرجع نیازمندی نیست.</p>')}`},
customers:()=>box('مشتریان',`<div class="row"><div><label>نام *</label><input id="cName"></div><div><label>شرکت</label><input id="cCompany"></div><div><label>تلفن</label><input id="cPhone"></div></div><div class="actions"><button class="btn s" id="saveCustomer">ثبت</button></div>${table(DB.state.customers,['نام','شرکت','تلفن'],x=>[x.name,x.company,x.phone])}`),
products:()=>box('کالاها',`<div class="row"><div><label>نام *</label><input id="pName"></div><div><label>واحد پایه</label><input id="pUnit" value="عدد"></div><div><label>واحد بسته</label><input id="pPack" value="کارتن"></div><div><label>تعداد پایه در بسته</label><input id="pUpp" type="number" value="1"></div></div><div class="actions"><button class="btn s" id="saveProduct">ثبت</button></div>${table(DB.state.products,['کالا','واحد','بسته','تعداد'],x=>[x.name,x.baseUnit,x.packUnit,x.unitsPerPack])}`),
prices:()=>box('تاریخچه قیمت',`<div class="row"><div><label>کالا</label><select id="priceProduct">${opts(DB.state.products)}</select></div><div><label>قیمت</label><input id="priceValue" type="number"></div><div><label>تاریخ اعتبار</label><input id="priceDate" value="${DB.todayJ()}"></div></div><div class="actions"><button class="btn s" id="savePrice">ثبت</button></div>${table(DB.state.prices,['کالا','قیمت','تاریخ'],x=>[(DB.getProduct(x.productId)||{}).name,fmt(x.price),x.effectiveDate])}`),
sales:()=>box('فروش',`<div class="row"><div><label>مشتری</label><select id="saleCustomer">${opts(DB.state.customers)}</select></div><div><label>کالا</label><select id="saleProduct">${opts(DB.state.products)}</select></div><div><label>تعداد</label><input id="saleQty" type="number" value="1"></div><div><label>قیمت واحد</label><input id="saleUnit" type="number"></div><div><label>تاریخ</label><input id="saleDate" value="${DB.todayJ()}"></div></div><div class="actions"><button class="btn s" id="saveSale">ثبت فروش</button></div>${table(DB.state.sales,['تاریخ','مشتری','کالا','تعداد','مبلغ'],x=>[x.jDate,(DB.getCustomer(x.customerId)||{}).name,(DB.getProduct(x.productId)||{}).name,x.quantity,fmt(x.amount)])}`),
receipts:()=>box('دریافت',`<div class="row"><div><label>مشتری</label><select id="recCustomer">${opts(DB.state.customers)}</select></div><div><label>مبلغ</label><input id="recAmount" type="number"></div><div><label>نوع</label><select id="recType"><option>نقد</option><option>کارت</option><option>چک</option></select></div><div><label>تاریخ</label><input id="recDate" value="${DB.todayJ()}"></div><div><label>وضعیت</label><select id="recStatus"><option>وصول شده</option><option>نزد ما</option><option>برگشتی</option><option>باطل</option></select></div></div><div class="actions"><button class="btn s" id="saveReceipt">ثبت دریافت</button></div>${table(DB.state.receipts,['تاریخ','مشتری','مبلغ','نوع','وضعیت'],x=>[x.jDate,(DB.getCustomer(x.customerId)||{}).name,fmt(x.amount),x.type,x.status])}`),
checks:()=>box('چک‌ها','<p>مدل CheckEvent، وضعیت مؤثر، سررسید، برگشت و جایگزینی در قرارداد پروژه ثبت شده و اتصال کامل رابط در گام بعدی همین اجرای پروژه انجام می‌شود.</p>'),
inventory:()=>box('موجودی','<p>انبارها: مواد اولیه، محصول نهایی و کالای بازرگانی. مقدار موجودی باید از حرکت‌های نرمال‌شده و واحد پایه محاسبه شود.</p>'),
production:()=>box('تولید','<p>تولید چندمرحله‌ای: مواد اولیه → کوت/نیمه‌ساخته → محصول نهایی، همراه GoodQty/WasteQty و snapshot هزینه تاریخی.</p>'),
purchases:()=>box('خرید','<p>Purchase Price، Supplier Price و Cost Basis سه مفهوم جدا هستند.</p>'),
payments:()=>box('پرداخت','<p>پرداخت از هزینه مستقل است و نباید دوباره‌شماری شود.</p>'),
expenses:()=>box('هزینه‌ها',`<div class="row"><div><label>دسته</label><input id="expCat" value="عمومی"></div><div><label>مبلغ</label><input id="expAmount" type="number"></div><div><label>تاریخ</label><input id="expDate" value="${DB.todayJ()}"></div></div><div class="actions"><button class="btn s" id="saveExpense">ثبت هزینه</button></div>${table(DB.state.expenses,['تاریخ','دسته','مبلغ'],x=>[x.jDate,x.category,fmt(x.amount)])}`),
capital:()=>box('سرمایه و شرکا','<p>سرمایه/حقوق مالکیت از حساب جاری شریک جداست. انتقال سهم، ذاتاً افزایش سرمایه نیست.</p>'),
reports:()=>box('حساب جاری مشتریان',table(Reports.customerBalances(DB.todayJ()),['مشتری','مانده اصل','اعتبار','سود اطلاعاتی'],x=>[x.customer.name,fmt(x.balance),fmt(x.credit),fmt(x.interest)])),
settings:()=>box('تنظیمات',`<p>مبنای روز: ${DB.state.settings.dayBasis}</p><p>تعداد tier: ${DB.state.settings.tiers.length}</p><p>تاریخ محاسبه: ${DB.todayJ()}</p>`)};
function render(){document.getElementById('nav').innerHTML=tabs.map(t=>`<button data-tab="${t[0]}" class="${current===t[0]?'on':''}">${t[1]}</button>`).join('');document.getElementById('main').innerHTML=(v[current]||v.dashboard)();}
document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t){current=t.dataset.tab;render();return;}try{if(e.target.id==='saveCustomer')Transactions.addCustomer({name:cName.value,company:cCompany.value,phone:cPhone.value});else if(e.target.id==='saveProduct')Transactions.addProduct({name:pName.value,baseUnit:pUnit.value,packUnit:pPack.value,unitsPerPack:pUpp.value});else if(e.target.id==='savePrice')Transactions.addPrice({productId:priceProduct.value,price:priceValue.value,effectiveDate:priceDate.value});else if(e.target.id==='saveSale')Transactions.addSale({customerId:saleCustomer.value,productId:saleProduct.value,quantity:saleQty.value,unitPrice:saleUnit.value,jDate:saleDate.value});else if(e.target.id==='saveReceipt')Transactions.addReceipt({customerId:recCustomer.value,amount:recAmount.value,type:recType.value,status:recStatus.value,jDate:recDate.value});else if(e.target.id==='saveExpense')Transactions.addExpense({category:expCat.value,amount:expAmount.value,jDate:expDate.value});else return;render();}catch(err){alert(err.message);}});root.ProjectUI={render};
})(typeof globalThis!=='undefined'?globalThis:this);
