'use strict';
(function(root){
let current='dashboard';
const tabs=[['dashboard','داشبورد'],['people','اشخاص'],['products','کالاها'],['prices','تاریخچه قیمت'],['sales','فروش'],['receipts','دریافت و چک'],['inventory','موجودی'],['production','تولید'],['purchases','خرید'],['payments','پرداخت'],['expenses','هزینه‌ها'],['capital','سرمایه و شرکا'],['reports','حساب جاری'],['settings','تنظیمات']];
const roles=[['customer','مشتری'],['supplier','تأمین‌کننده'],['partner','شریک'],['worker','کارگر'],['bank','بانک/مؤسسه'],['other','سایر']];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=x=>Number(x)||0,fmt=x=>Math.round(n(x)).toLocaleString('en-US');
const today=()=>DB.todayJ(), people=()=>DB.state.people||[], customers=()=>people().filter(p=>(p.roles||[]).includes('customer')), suppliers=()=>people().filter(p=>(p.roles||[]).includes('supplier')), partners=()=>people().filter(p=>(p.roles||[]).includes('partner'));
const pname=id=>(DB.getPerson(id)||{}).name||'—', prname=id=>(DB.getProduct(id)||{}).name||'—';
const options=a=>(a||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.code||x.id)}</option>`).join('');
function box(t,b){return `<section class="bx"><h3>${t}</h3>${b}</section>`}function field(l,id,type='text',v='',ex=''){return `<div><label>${l}</label><input id="${id}" type="${type}" value="${esc(v)}" ${ex}></div>`}function sel(l,id,o){return `<div><label>${l}</label><select id="${id}">${o}</select></div>`}
function table(rows,h,map){if(!rows.length)return '<div class="em">رکوردی وجود ندارد.</div>';return `<div class="tbl-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${map(r).map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function toast(m,t='s'){let q=document.querySelector('.toast');if(!q){q=document.createElement('div');q.className='toast';document.body.appendChild(q)}const e=document.createElement('div');e.className='t '+t;e.textContent=m;q.appendChild(e);setTimeout(()=>e.remove(),3000)}
function run(f){try{f();DB.save();render();toast('با موفقیت ثبت شد')}catch(e){console.error(e);toast(e.message||'خطا','d')}}
function dashboard(){const k=Reports.dashboard(),s=DB.state;let bal=0;customers().forEach(c=>{try{bal+=n(Transactions.customerStatement(c.id,today()).totalRem)}catch(_){}});return `<div class="kpi"><div class="k p"><div class="l">فروش</div><div class="v">${fmt(k.sales)}</div></div><div class="k s"><div class="l">دریافت مؤثر</div><div class="v">${fmt(k.receipts)}</div></div><div class="k d"><div class="l">مانده اصل</div><div class="v">${fmt(bal)}</div></div><div class="k"><div class="l">اشخاص</div><div class="v">${s.people.length}</div></div><div class="k"><div class="l">کالاها</div><div class="v">${s.products.length}</div></div><div class="k v"><div class="l">عملیات</div><div class="v">${s.operations.length}</div></div></div>${box('دسترسی سریع',`<div class="actions"><button class="btn s" data-go="sales">➕ فروش</button><button class="btn s" data-go="receipts">➕ دریافت</button><button class="btn" data-go="people">اشخاص</button><button class="btn" data-go="inventory">موجودی</button><button class="btn" data-go="reports">حساب جاری</button></div>`)}${box('وضعیت سامانه',`<div class="info-line"><span>تاریخ محاسبه</span><b>${today()}</b></div><div class="info-line"><span>بسته‌های پرداخت</span><b>${s.paymentPackages.length}</b></div><div class="info-line"><span>انبارها</span><b>${s.warehouses.length}</b></div><div class="info-line"><span>Receipt Allocation</span><b>${s.receiptAllocations.length}</b></div>`)}`}
function peopleView(){const checks=roles.map(([id,l])=>`<label class="check"><input type="checkbox" name="personRole" value="${id}"><span>${l}</span></label>`).join('');return box('اشخاص',`<div class="actions"><button class="btn s" id="addPerson">➕ افزودن شخص</button></div>${table(people(),['نام','شرکت','تلفن','نقش‌ها','بسته پرداخت','وضعیت',''],p=>[esc(p.name),esc(p.company||'—'),esc(p.phone||'—'),esc((p.roles||[]).map(r=>(roles.find(z=>z[0]===r)||['',r])[1]).join('، ')||'—'),esc(p.paymentPackageId||'—'),p.active===false?'<span class="tag d">غیرفعال</span>':'<span class="tag s">فعال</span>',`<button class="btn" data-edit-person="${esc(p.id)}">ویرایش</button>`])}<dialog id="personDialog"><form method="dialog"><h3 id="personTitle">افزودن شخص</h3><div class="row">${field('نام *','personName')}${field('شرکت / فروشگاه','personCompany')}${field('تلفن','personPhone')}</div><div class="row">${field('آدرس','personAddress')}${sel('بسته شرایط پرداخت','personPackage','<option value="">هیچکدام</option>'+options(DB.state.paymentPackages))}</div><label>نقش‌ها</label><div class="checks">${checks}</div>${field('یادداشت','personNotes')}<div class="actions"><button type="button" class="btn g" data-close-dialog>انصراف</button><button type="button" class="btn s" id="savePerson">ذخیره</button></div></form></dialog>`)}
function productsView(){return box('کالاها',`<div class="row">${field('کد کالا','pCode')}${field('نام کالا *','pName')}${field('واحد پایه','pBase','text','عدد')}${field('واحد بسته','pPack','text','کارتن')}</div><div class="row">${field('تعداد پایه در بسته','pUpp','number','1','min="1" step="0.000001"')}${sel('واحد قیمت‌گذاری','pPricing','<option>عدد</option><option>کیلوگرم</option><option>کارتن</option><option>بسته</option>')}${sel('انبار پیش‌فرض','pWarehouse',options(DB.state.warehouses))}</div><div class="actions"><button class="btn s" id="saveProduct">ثبت کالا</button></div>${table(DB.state.products,['کد','نام','واحد پایه','واحد بسته','تعداد/بسته','قیمت‌گذاری','انبار'],p=>[esc(p.code||'—'),esc(p.name),esc(p.baseUnit),esc(p.packageUnit),n(p.unitsPerPackage).toLocaleString('en-US'),esc(p.pricingUnit),esc((DB.state.warehouses.find(w=>w.id===p.warehouseId)||{}).name||'—')])}`)}
function pricesView(){return box('تاریخچه قیمت',`<div class="row">${sel('کالا','priceProduct',options(DB.state.products))}${sel('مشتری','priceCustomer','<option value="">عمومی / همه</option>'+options(customers()))}${field('قیمت','priceValue','number','0','min="0" step="0.01"')}${field('شروع اعتبار','priceDate','text',today())}</div>${field('یادداشت','priceNotes')}<div class="actions"><button class="btn s" id="savePrice">ثبت قیمت</button></div>${table(DB.state.prices.slice().reverse(),['کالا','مشتری','قیمت','از تاریخ','شناسه'],p=>[esc(prname(p.productId)),esc(p.customerId?pname(p.customerId):'عمومی'),fmt(p.price),esc(p.effectiveDate),esc(p.id)])}`)}
function salesView(){return box('فروش و فاکتور',`<div class="row">${sel('مشتری *','saleCustomer',options(customers()))}${sel('کالا *','saleProduct',options(DB.state.products))}${sel('واحد فروش','saleUnit','')}${field('مقدار','saleQty','number','1','min="0.000001" step="0.000001"')}${field('تاریخ فاکتور','saleDate','text',today())}</div><div class="row">${field('قیمت پیشنهادی','saleSuggested','number','0','readonly')}${field('قیمت نهایی هر واحد','saleUnitPrice','number','0','min="0" step="0.01"')}${sel('شرایط پرداخت','salePackage','<option value="">از شخص / بدون override</option>'+options(DB.state.paymentPackages))}${field('مبلغ کل','saleTotal','number','0','readonly')}</div>${field('یادداشت','saleNotes')}<div class="actions"><button class="btn" id="resetSalePrice">↺ قیمت تاریخچه</button><button class="btn s" id="saveSale">ثبت فروش</button></div>${table(DB.state.sales.slice().reverse(),['تاریخ','مشتری','کالا','واحد','مقدار','قیمت','مبلغ','شرایط','منبع قیمت'],x=>[esc(x.jDate),esc(pname(x.customerId)),esc(prname(x.productId)),esc(x.salesUnit),n(x.quantity).toLocaleString('en-US'),fmt(x.unitPrice),fmt(x.amount),esc(x.paymentPackageId||'—'),x.manualPrice?'<span class="tag w">دستی</span>':'<span class="tag i">تاریخچه</span>'])}`)}
function receiptsView(){return box('دریافت و چک',`<div class="row">${sel('مشتری *','recCustomer',options(customers()))}${sel('نوع دریافت','recType','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')}${field('مبلغ *','recAmount','number','0','min="0.01" step="0.01"')}${field('تاریخ','recDate','text',today())}${sel('وضعیت','recStatus','<option>وصول شده</option><option>نزد ما</option><option>تودیع‌شده</option><option>برگشتی</option><option>باطل</option>')}</div><div id="checkFields" class="row" style="display:none">${field('شماره چک','recCheckNo')}${field('بانک','recBank')}${field('سررسید','recDue','text',today())}</div>${field('یادداشت','recNotes')}<div class="actions"><button class="btn s" id="saveReceipt">ثبت دریافت</button></div>${table(DB.state.receipts.slice().reverse(),['تاریخ','مشتری','نوع','مبلغ','شماره','سررسید','وضعیت',''],x=>[esc(x.jDate),esc(pname(x.customerId)),esc(x.type),fmt(x.amount),esc(x.checkNo||'—'),esc(x.dueDate||'—'),esc(x.status||'—'),x.type==='چک'?`<button class="btn" data-check-action="${esc(x.id)}">وضعیت</button>`:'—'])}`)}
function inventoryView(){const m=DB.state.inventoryMovements;const rows=DB.state.products.map(p=>{const w=DB.state.warehouses.find(z=>z.id===p.warehouseId)||DB.state.warehouses[0];return {p,w,qty:w?AccountingModules.stock(m,p.id,w.id):0,count:w?m.filter(x=>x.productId===p.id&&x.warehouseId===w.id).length:0}});return box('موجودی و تعدیل',`<div class="row">${sel('کالا','adjProduct',options(DB.state.products))}${sel('انبار','adjWarehouse',options(DB.state.warehouses))}${field('تعدیل مقدار پایه','adjQty','number','0','step="0.000001"')}${field('تاریخ','adjDate','text',today())}</div>${field('علت تعدیل','adjReason')}<div class="actions"><button class="btn s" id="saveAdjustment">ثبت تعدیل</button></div>${table(rows,['کالا','انبار','واحد پایه','موجودی','تعداد حرکت'],x=>[esc(x.p.name),esc(x.w&&x.w.name),esc(x.p.baseUnit),n(x.qty).toLocaleString('en-US'),x.count])}`)}
function productionView(){return box('تولید چندمرحله‌ای',`<div class="row">${field('شناسه تولید','prodId')}${sel('محصول خروجی','prodProduct',options(DB.state.products))}${field('Actual Qty','prodActual','number','1','min="0.000001"')}${field('Waste Qty','prodWaste','number','0','min="0" step="0.000001"')}${field('تاریخ','prodDate','text',today())}</div><div class="row">${sel('فرمول','prodFormula',options(DB.state.formulas))}${sel('انبار خروجی','prodWarehouse',options(DB.state.warehouses))}${field('هزینه دستی واحد','prodManualCost','number','0','min="0"')}${field('Historical Cost Basis','prodHistoricalCost','number','0','min="0"')}</div>${field('یادداشت','prodNotes')}<div class="actions"><button class="btn s" id="saveProduction">ثبت تولید</button></div>${table(DB.state.productions.slice().reverse(),['تاریخ','شناسه','محصول','فرمول','GoodQty','WasteQty','هزینه تاریخی'],x=>[esc(x.jDate),esc(x.id),esc(prname(x.productId)),esc(x.formulaId),n(x.goodQty).toLocaleString('en-US'),n(x.wasteQty).toLocaleString('en-US'),fmt(x.historicalCostBasis)])}`)}
function purchasesView(){return box('خرید و تأمین',`<div class="row">${sel('تأمین‌کننده','purSupplier',options(suppliers()))}${sel('کالا','purProduct',options(DB.state.products))}${sel('انبار','purWarehouse',options(DB.state.warehouses))}${field('مقدار','purQty','number','1','min="0.000001"')}${field('قیمت خرید واحد','purUnitPrice','number','0','min="0"')}${field('کرایه','purFreight','number','0','min="0"')}${field('تخلیه','purUnload','number','0','min="0"')}${field('تاریخ','purDate','text',today())}</div>${field('Cost Basis هر واحد پایه','purCostBasis','number','0','min="0"')}<div class="actions"><button class="btn s" id="savePurchase">ثبت خرید</button></div>${table(DB.state.purchases.slice().reverse(),['تاریخ','تأمین‌کننده','کالا','مقدار','قیمت خرید','کرایه','تخلیه','Cost Basis'],x=>[esc(x.jDate),esc(pname(x.supplierId)),esc(prname(x.productId)),n(x.quantity).toLocaleString('en-US'),fmt(x.unitPrice),fmt(x.freight),fmt(x.unloading),fmt(x.costBasis)])}`)}
function paymentsView(){return box('پرداخت‌ها',`<div class="row">${sel('طرف حساب','payee',options(people()))}${field('مبلغ','payAmount','number','0','min="0.01"')}${sel('نوع','payType','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')}${field('تاریخ','payDate','text',today())}</div>${field('یادداشت','payNotes')}<div class="actions"><button class="btn s" id="savePayment">ثبت پرداخت</button></div>${table(DB.state.payments.slice().reverse(),['تاریخ','طرف حساب','نوع','مبلغ','OperationID'],x=>[esc(x.jDate),esc(pname(x.payeeId)),esc(x.type),fmt(x.amount),esc(x.operationId||'—')])}`)}
function expensesView(){return box('هزینه‌های کارگاه',`<div class="row">${field('دسته','expCat','text','عمومی')}${field('مبلغ','expAmount','number','0','min="0.01"')}${field('تاریخ','expDate','text',today())}</div>${field('شرح','expDesc')}<div class="actions"><button class="btn s" id="saveExpense">ثبت هزینه</button></div>${table(DB.state.expenses.slice().reverse(),['تاریخ','دسته','مبلغ','شرح','OperationID'],x=>[esc(x.jDate),esc(x.category),fmt(x.amount),esc(x.description||'—'),esc(x.operationId||'—')])}`)}
function capitalView(){const list=partners().length?partners():people();return box('سرمایه و شرکا',`<div class="row">${sel('شخص','capPerson',options(list))}${sel('نوع رویداد','capType','<option value="CONTRIBUTION">افزایش سرمایه</option><option value="WITHDRAWAL">برداشت سرمایه</option>')}${field('مبلغ','capAmount','number','0','min="0.01"')}${field('تاریخ','capDate','text',today())}</div>${field('یادداشت','capNotes')}<div class="actions"><button class="btn s" id="saveCapital">ثبت رویداد</button></div>${box('مالکیت شرکا',`<div class="row">${sel('شریک','ownPartner',options(list))}${field('درصد مالکیت','ownPercent','number','0','min="0" max="100" step="0.0001"')}${field('تاریخ اثر','ownDate','text',today())}</div><div class="actions"><button class="btn" id="saveOwnership">ثبت مالکیت</button></div>${table(DB.state.ownershipHistory,['شریک','درصد','تاریخ'],x=>[esc(pname(x.partnerId)),n(x.ownershipPercent).toFixed(4)+'%',esc(x.effectiveDate)])}`)}${table(DB.state.capitalEvents.slice().reverse(),['تاریخ','شخص','نوع','مبلغ'],x=>[esc(x.jDate),esc(pname(x.personId)),esc(x.eventType),fmt(x.amount)])}`)}
function statementTable(rows){return table(rows,['مشتری','مانده اصل','اعتبار','سود اطلاعاتی','وضعیت'],x=>[esc(x.customer.name),fmt(x.balance),fmt(x.credit),fmt(x.interest),x.balance>0?'<span class="tag d">بدهکار</span>':x.credit>0?'<span class="tag s">بستانکار</span>':'<span class="tag m">تسویه</span>'])}
function reportsView(){return box('حساب جاری مشتریان',`<div class="row">${sel('مشتری','stmtCustomer','<option value="">همه مشتریان</option>'+options(customers()))}${field('تاریخ محاسبه','stmtDate','text',today())}</div><div class="actions"><button class="btn" id="refreshStatement">محاسبه</button></div><div id="statementArea">${statementTable(Reports.customerBalances(today()))}</div>`)}
function settingsView(){return box('تنظیمات',`<div class="row">${field('مبنای روز','setDayBasis','number',DB.state.settings.dayBasis,'min="1"')}${field('روز مهلت','setGrace','number',DB.state.settings.graceDays,'min="0"')}${field('واحد پول','setCurrency','text',DB.state.settings.currency)}</div><div class="actions"><button class="btn s" id="saveSettings">ذخیره تنظیمات</button></div>${box('بسته‌های شرایط پرداخت',`<div class="row">${field('شناسه بسته','pkgId')}${field('نام بسته','pkgName')}</div><div class="row">${field('Tier1 حداکثر روز','t1d','number','30')}${field('Tier1 نرخ','t1r','number','0','step="0.0001"')}${field('Tier2 حداکثر روز','t2d','number','60')}${field('Tier2 نرخ','t2r','number','0.06','step="0.0001"')}</div><div class="row">${field('Tier3 حداکثر روز','t3d','number','120')}${field('Tier3 نرخ','t3r','number','0.10','step="0.0001"')}${field('Tier4 حداکثر روز','t4d','number','9999')}${field('Tier4 نرخ','t4r','number','0.15','step="0.0001"')}</div><div class="actions"><button class="btn s" id="savePackage">ایجاد/ویرایش بسته</button></div>${table(DB.state.paymentPackages,['شناسه','نام','Tierها'],x=>[esc(x.id),esc(x.name),esc((x.tiers||[]).map(t=>`${t.maxDays} روز / ${(n(t.rate)*100).toFixed(2)}%`).join(' | '))])}`)}${box('انبارها',table(DB.state.warehouses,['شناسه','نام','وضعیت'],x=>[esc(x.id),esc(x.name),x.active===false?'غیرفعال':'فعال']))}${box('زیرساخت',`<div class="info-line"><span>Operations</span><b>${DB.state.operations.length}</b></div><div class="info-line"><span>Effects</span><b>${DB.state.effects.length}</b></div><div class="info-line"><span>AuditLog</span><b>${DB.state.audit.length}</b></div><div class="info-line"><span>ReceiptAllocation</span><b>${DB.state.receiptAllocations.length}</b></div>`)}`)}
const views={dashboard,people:peopleView,products:productsView,prices:pricesView,sales:salesView,receipts:receiptsView,inventory:inventoryView,production:productionView,purchases:purchasesView,payments:paymentsView,expenses:expensesView,capital:capitalView,reports:reportsView,settings:settingsView};
function val(id){return document.getElementById(id)?.value||''}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab;render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{current=b.dataset.go;render()});
 document.getElementById('addPerson')?.addEventListener('click',()=>document.getElementById('personDialog').showModal());document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 document.querySelectorAll('[data-edit-person]').forEach(b=>b.onclick=()=>{const p=DB.getPerson(b.dataset.editPerson);document.getElementById('personDialog').showModal();document.getElementById('personTitle').textContent='ویرایش شخص';document.getElementById('savePerson').dataset.edit=p.id;[['personName',p.name],['personCompany',p.company],['personPhone',p.phone],['personAddress',p.address],['personPackage',p.paymentPackageId||''],['personNotes',p.notes||'']].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.value=v});document.querySelectorAll('input[name="personRole"]').forEach(e=>e.checked=(p.roles||[]).includes(e.value))});
 document.getElementById('savePerson')?.addEventListener('click',()=>run(()=>{const roles=[...document.querySelectorAll('input[name="personRole"]:checked')].map(e=>e.value),x={name:val('personName').trim(),company:val('personCompany'),phone:val('personPhone'),address:val('personAddress'),paymentPackageId:val('personPackage')||null,notes:val('personNotes'),roles};if(!x.name)throw Error('نام شخص الزامی است');const id=document.getElementById('savePerson').dataset.edit;if(id)Transactions.updatePerson(id,x);else Transactions.addPerson(x);document.getElementById('personDialog').close()}));
 document.getElementById('saveProduct')?.addEventListener('click',()=>run(()=>Transactions.addProduct({code:val('pCode'),name:val('pName').trim(),baseUnit:val('pBase'),packageUnit:val('pPack'),unitsPerPackage:n(val('pUpp)),pricingUnit:val('pPricing'),warehouseId:val('pWarehouse')})));
 document.getElementById('savePrice')?.addEventListener('click',()=>run(()=>Transactions.addPrice({productId:val('priceProduct'),customerId:val('priceCustomer')||null,price:n(val('priceValue')),effectiveDate:val('priceDate'),notes:val('priceNotes')})));
 const refreshSale=()=>{const p=DB.getProduct(val('saleProduct')),u=document.getElementById('saleUnit');if(!p||!u)return;u.innerHTML=[...new Set([p.baseUnit,p.packageUnit,p.pricingUnit].filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('');try{const q=Transactions.suggestedSalePrice(p.id,val('saleCustomer'),val('saleDate')||today(),u.value);document.getElementById('saleSuggested').value=q.unitPrice;document.getElementById('saleUnitPrice').value=q.unitPrice}catch(_){document.getElementById('saleSuggested').value=''}};['saleProduct','saleCustomer','saleDate','saleUnit'].forEach(id=>document.getElementById(id)?.addEventListener('change',refreshSale));['saleQty','saleUnitPrice'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>document.getElementById('saleTotal').value=n(val('saleQty'))*n(val('saleUnitPrice'))));refreshSale();document.getElementById('resetSalePrice')?.addEventListener('click',refreshSale);
 document.getElementById('saveSale')?.addEventListener('click',()=>run(()=>Transactions.addSale({customerId:val('saleCustomer'),productId:val('saleProduct'),salesUnit:val('saleUnit'),quantity:n(val('saleQty')),unitPrice:n(val('saleUnitPrice')),jDate:val('saleDate'),paymentPackageId:val('salePackage')||null,notes:val('saleNotes')})));
 const ct=document.getElementById('recType'),toggle=()=>{const e=document.getElementById('checkFields');if(e)e.style.display=ct?.value==='چک'?'grid':'none'};ct?.addEventListener('change',toggle);toggle();document.getElementById('saveReceipt')?.addEventListener('click',()=>run(()=>Transactions.addReceipt({customerId:val('recCustomer'),type:val('recType'),amount:n(val('recAmount')),jDate:val('recDate'),status:val('recStatus'),checkNo:val('recCheckNo'),bank:val('recBank'),dueDate:val('recDue'),notes:val('recNotes')})));
 document.querySelectorAll('[data-check-action]').forEach(b=>b.onclick=()=>{const r=DB.state.receipts.find(x=>x.id===b.dataset.checkAction),s=prompt('وضعیت جدید',r.status);if(s)run(()=>Transactions.changeCheckStatus(r.id,s,{actualDate:today()}))});
 document.getElementById('saveAdjustment')?.addEventListener('click',()=>run(()=>Transactions.addInventoryAdjustment({productId:val('adjProduct'),warehouseId:val('adjWarehouse'),baseQty:n(val('adjQty')),jDate:val('adjDate'),reason:val('adjReason')})));
 document.getElementById('saveProduction')?.addEventListener('click',()=>run(()=>Transactions.addProduction({id:val('prodId')||undefined,productId:val('prodProduct'),actualQty:n(val('prodActual')),wasteQty:n(val('prodWaste')),formulaId:val('prodFormula'),jDate:val('prodDate'),outputWarehouseId:val('prodWarehouse'),manualUnitCost:n(val('prodManualCost')),historicalCostBasis:n(val('prodHistoricalCost')),notes:val('prodNotes')})));
 document.getElementById('savePurchase')?.addEventListener('click',()=>run(()=>Transactions.addPurchase({supplierId:val('purSupplier'),productId:val('purProduct'),warehouseId:val('purWarehouse'),quantity:n(val('purQty')),unitPrice:n(val('purUnitPrice')),amount:n(val('purQty'))*n(val('purUnitPrice')),freight:n(val('purFreight')),unloading:n(val('purUnload')),costBasis:n(val('purCostBasis')),jDate:val('purDate')})));
 document.getElementById('savePayment')?.addEventListener('click',()=>run(()=>Transactions.addPayment({payeeId:val('payee'),amount:n(val('payAmount')),type:val('payType'),jDate:val('payDate'),notes:val('payNotes')})));
 document.getElementById('saveExpense')?.addEventListener('click',()=>run(()=>Transactions.addExpense({category:val('expCat'),amount:n(val('expAmount')),jDate:val('expDate'),description:val('expDesc')})));
 document.getElementById('saveCapital')?.addEventListener('click',()=>run(()=>Transactions.addCapitalEvent({personId:val('capPerson'),eventType:val('capType'),amount:n(val('capAmount')),jDate:val('capDate'),notes:val('capNotes')})));
 document.getElementById('saveOwnership')?.addEventListener('click',()=>run(()=>Transactions.setOwnership({partnerId:val('ownPartner'),ownershipPercent:n(val('ownPercent')),effectiveDate:val('ownDate')})));
 document.getElementById('refreshStatement')?.addEventListener('click',()=>{const d=val('stmtDate')||today(),id=val('stmtCustomer'),rows=id?Reports.customerBalances(d).filter(x=>x.customer.id===id):Reports.customerBalances(d);document.getElementById('statementArea').innerHTML=statementTable(rows)});
 document.getElementById('saveSettings')?.addEventListener('click',()=>run(()=>{DB.state.settings.dayBasis=n(val('setDayBasis'))||30;DB.state.settings.graceDays=n(val('setGrace'));DB.state.settings.currency=val('setCurrency')||'ریال'}));
 document.getElementById('savePackage')?.addEventListener('click',()=>run(()=>{const id=val('pkgId').trim(),name=val('pkgName').trim()||id;if(!id)throw Error('شناسه بسته الزامی است');const tiers=[['t1','t1d','t1r'],['t2','t2d','t2r'],['t3','t3d','t3r'],['t4','t4d','t4r']].map(([i,d,r])=>({id:i,maxDays:n(val(d)),rate:n(val(r)),active:true}));const old=DB.getPaymentPackage(id);if(old)DB.updatePaymentPackage(id,{name,tiers,active:true});else DB.addPaymentPackage({id,name,tiers,active:true})}));
}
function render(){const nav=document.getElementById('nav'),main=document.getElementById('main');if(!nav||!main)return;nav.innerHTML=tabs.map(([id,l])=>`<button class="${id===current?'on':''}" data-tab="${id}">${l}</button>`).join('');main.innerHTML=views[current]();bind()}
root.ProjectUI={render,setPage:p=>{if(views[p]){current=p;render()}}};
})(typeof globalThis!=='undefined'?globalThis:this);
