'use strict';
(function(root){
let current='dashboard';
const tabs=[['dashboard','داشبورد'],['people','اشخاص'],['products','کالاها'],['prices','تاریخچه قیمت'],['sales','فروش'],['receipts','دریافت و چک'],['inventory','موجودی'],['production','تولید'],['purchases','خرید'],['payments','پرداخت'],['expenses','هزینه‌ها'],['capital','سرمایه و شرکا'],['reports','حساب جاری'],['settings','تنظیمات']];
const roles=[['customer','مشتری'],['supplier','تأمین‌کننده'],['partner','شریک'],['worker','کارگر'],['bank','بانک/مؤسسه'],['other','سایر']];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=x=>Number(x)||0,fmt=x=>Math.round(n(x)).toLocaleString('en-US');
const today=()=>DB.todayJ(),people=()=>DB.state.people||[],customers=()=>people().filter(p=>(p.roles||[]).includes('customer')),suppliers=()=>people().filter(p=>(p.roles||[]).includes('supplier')),partners=()=>people().filter(p=>(p.roles||[]).includes('partner'));
const pname=id=>(DB.getPerson(id)||{}).name||'—',prname=id=>(DB.getProduct(id)||{}).name||'—';
const options=a=>(a||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.code||x.id)}</option>`).join('');
const val=id=>document.getElementById(id)?.value||'';
const field=(l,id,t='text',v='',ex='')=>`<div><label>${l}</label><input id="${id}" type="${t}" value="${esc(v)}" ${ex}></div>`;
const select=(l,id,o)=>`<div><label>${l}</label><select id="${id}">${o}</select></div>`;
function box(t,b){return `<section class="bx"><h3>${t}</h3>${b}</section>`}function table(rows,h,map){if(!rows.length)return '<div class="em">رکوردی وجود ندارد.</div>';return `<div class="tbl-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${map(r).map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function run(f){try{f();DB.save();render()}catch(e){console.error(e);alert(e.message||'خطا')}}
function dashboard(){const k=Reports.dashboard();return `<div class="kpi"><div class="k p"><div class="l">فروش</div><div class="v">${fmt(k.sales)}</div></div><div class="k s"><div class="l">دریافت مؤثر</div><div class="v">${fmt(k.receipts)}</div></div><div class="k"><div class="l">اشخاص</div><div class="v">${people().length}</div></div><div class="k"><div class="l">کالاها</div><div class="v">${DB.state.products.length}</div></div><div class="k v"><div class="l">Operations</div><div class="v">${DB.state.operations.length}</div></div></div>${box('دسترسی سریع','<div class="actions"><button class="btn s" data-go="sales">➕ فروش</button><button class="btn s" data-go="receipts">➕ دریافت</button><button class="btn" data-go="inventory">موجودی</button><button class="btn" data-go="reports">حساب جاری</button></div>')}${box('وضعیت','<div class="info-line"><span>تاریخ محاسبه</span><b>'+today()+'</b></div><div class="info-line"><span>بسته‌های پرداخت</span><b>'+DB.state.paymentPackages.length+'</b></div><div class="info-line"><span>انبارها</span><b>'+DB.state.warehouses.length+'</b></div>')}</div>`}
function peopleView(){const rc=roles.map(r=>`<label class="check"><input type="checkbox" name="role" value="${r[0]}"><span>${r[1]}</span></label>`).join('');return box('اشخاص',`<div class="actions"><button class="btn s" id="addPerson">➕ افزودن شخص</button></div>${table(people(),['نام','شرکت','تلفن','نقش‌ها','بسته پرداخت',''],p=>[esc(p.name),esc(p.company||'—'),esc(p.phone||'—'),esc((p.roles||[]).map(r=>(roles.find(z=>z[0]===r)||['',r])[1]).join('، ')),esc(p.paymentPackageId||'—'),`<button class="btn" data-edit="${esc(p.id)}">ویرایش</button>`])}<dialog id="pd"><form method="dialog"><h3>افزودن/ویرایش شخص</h3><div class="row">${field('نام *','pn')}${field('شرکت','pc')}${field('تلفن','pp')}</div><div class="row">${field('آدرس','pa')}${select('بسته پرداخت','pkg','<option value="">هیچکدام</option>'+options(DB.state.paymentPackages))}</div><label>نقش‌ها</label><div class="checks">${rc}</div>${field('یادداشت','pnote')}<div class="actions"><button type="button" class="btn g" data-close>انصراف</button><button type="button" class="btn s" id="savePerson">ذخیره</button></div></form></dialog>`)}
function productsView(){return box('کالاها',`<div class="row">${field('کد','pcd')}${field('نام *','pna')}${field('واحد پایه','pbu','text','عدد')}${field('واحد بسته','ppu','text','کارتن')}</div><div class="row">${field('تعداد پایه/بسته','upp','number','1')}${select('واحد قیمت‌گذاری','priunit','<option>عدد</option><option>کیلوگرم</option><option>کارتن</option><option>بسته</option>')}${select('انبار','pwh',options(DB.state.warehouses))}</div><div class="actions"><button class="btn s" id="saveProduct">ثبت کالا</button></div>${table(DB.state.products,['کد','نام','پایه','بسته','تعداد/بسته','قیمت‌گذاری','انبار'],p=>[esc(p.code),esc(p.name),esc(p.baseUnit),esc(p.packageUnit),n(p.unitsPerPackage),esc(p.pricingUnit),esc((DB.state.warehouses.find(w=>w.id===p.warehouseId)||{}).name||'—')])}`)}
function pricesView(){return box('تاریخچه قیمت',`<div class="row">${select('کالا','prp',options(DB.state.products))}${select('مشتری','prc','<option value="">عمومی</option>'+options(customers()))}${field('قیمت','prv','number','0')}${field('شروع اعتبار','prd','text',today())}</div>${field('یادداشت','prn')}<div class="actions"><button class="btn s" id="savePrice">ثبت قیمت</button></div>${table(DB.state.prices.slice().reverse(),['کالا','مشتری','قیمت','از تاریخ'],x=>[esc(prname(x.productId)),esc(x.customerId?pname(x.customerId):'عمومی'),fmt(x.price),esc(x.effectiveDate)])}`)}
function salesView(){return box('فروش و فاکتور',`<div class="row">${select('مشتری','sc',options(customers()))}${select('کالا','sp',options(DB.state.products))}${select('واحد','su','')}${field('مقدار','sq','number','1')}${field('تاریخ','sd','text',today())}</div><div class="row">${field('قیمت پیشنهادی','ss','number','0','readonly')}${field('قیمت نهایی','sup','number','0')}${select('شرایط پرداخت','spp','<option value="">از شخص</option>'+options(DB.state.paymentPackages))}${field('مبلغ کل','st','number','0','readonly')}</div><div class="actions"><button class="btn" id="srp">↺ قیمت تاریخچه</button><button class="btn s" id="saveSale">ثبت فروش</button></div>${table(DB.state.sales.slice().reverse(),['تاریخ','مشتری','کالا','واحد','مقدار','قیمت','مبلغ'],x=>[esc(x.jDate),esc(pname(x.customerId)),esc(prname(x.productId)),esc(x.salesUnit),n(x.quantity),fmt(x.unitPrice),fmt(x.amount)])}`)}
function receiptsView(){return box('دریافت و چک',`<div class="row">${select('مشتری','rc',options(customers()))}${select('نوع','rt','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')}${field('مبلغ','ra','number','0')}${field('تاریخ','rd','text',today())}${select('وضعیت','rs','<option>وصول شده</option><option>نزد ما</option><option>تودیع‌شده</option><option>برگشتی</option><option>باطل</option>')}</div><div id="cf" class="row" style="display:none">${field('شماره چک','rno')}${field('بانک','rb')}${field('سررسید','rdu','text',today())}</div><div class="actions"><button class="btn s" id="saveReceipt">ثبت دریافت</button></div>${table(DB.state.receipts.slice().reverse(),['تاریخ','مشتری','نوع','مبلغ','شماره','سررسید','وضعیت'],x=>[esc(x.jDate),esc(pname(x.customerId)),esc(x.type),fmt(x.amount),esc(x.checkNo||'—'),esc(x.dueDate||'—'),esc(x.status||'—')])}`)}
function inventoryView(){const m=DB.state.inventoryMovements;return box('موجودی',`<div class="row">${select('کالا','ap',options(DB.state.products))}${select('انبار','aw',options(DB.state.warehouses))}${field('تعدیل مقدار پایه','aq','number','0')}${field('تاریخ','ad','text',today())}</div>${field('علت','ar')}<div class="actions"><button class="btn s" id="saveAdj">ثبت تعدیل</button></div>${table(DB.state.products,['کالا','انبار','واحد پایه','موجودی'],p=>{const w=DB.state.warehouses.find(x=>x.id===p.warehouseId)||DB.state.warehouses[0];return[esc(p.name),esc(w?.name),esc(p.baseUnit),n(w?AccountingModules.stock(m,p.id,w.id):0).toLocaleString('en-US')]})}`)}
function productionView(){return box('تولید',`<div class="row">${select('محصول','pp',options(DB.state.products))}${select('فرمول','pf',options(DB.state.formulas))}${field('Actual Qty','paq','number','1')}${field('Waste Qty','pwq','number','0')}${field('تاریخ','pdt','text',today())}</div><div class="row">${select('انبار خروجی','pwo',options(DB.state.warehouses))}${field('Historical Cost','phc','number','0')}${field('هزینه دستی واحد','pmc','number','0')}</div><div class="actions"><button class="btn s" id="saveProd">ثبت تولید</button></div>${table(DB.state.productions.slice().reverse(),['تاریخ','محصول','فرمول','GoodQty','WasteQty'],x=>[esc(x.jDate),esc(prname(x.productId)),esc(x.formulaId),n(x.goodQty),n(x.wasteQty)])}`)}
function purchasesView(){return box('خرید',`<div class="row">${select('تأمین‌کننده','pus',options(suppliers()))}${select('کالا','pup',options(DB.state.products))}${select('انبار','puw',options(DB.state.warehouses))}${field('مقدار','puq','number','1')}${field('قیمت خرید','pupx','number','0')}${field('کرایه','puf','number','0')}${field('تخلیه','puu','number','0')}${field('تاریخ','pud','text',today())}</div>${field('Cost Basis','puc','number','0')}<div class="actions"><button class="btn s" id="savePurchase">ثبت خرید</button></div>${table(DB.state.purchases.slice().reverse(),['تاریخ','تأمین‌کننده','کالا','مقدار','قیمت','Cost Basis'],x=>[esc(x.jDate),esc(pname(x.supplierId)),esc(prname(x.productId)),n(x.quantity),fmt(x.unitPrice),fmt(x.costBasis)])}`)}
function paymentsView(){return box('پرداخت و خزانه',`<div class="row">${select('طرف حساب','payee',options(people()))}${field('مبلغ','payam','number','0')}${select('نوع','paytype','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')}${field('تاریخ','payd','text',today())}</div><div class="actions"><button class="btn s" id="savePay">ثبت پرداخت</button></div>${table(DB.state.payments.slice().reverse(),['تاریخ','طرف حساب','نوع','مبلغ'],x=>[esc(x.jDate),esc(pname(x.payeeId)),esc(x.type),fmt(x.amount)])}`)}
function expensesView(){return box('هزینه‌ها و درآمد',`<div class="row">${field('دسته','ec','text','عمومی')}${field('مبلغ هزینه','ea','number','0')}${field('تاریخ','ed','text',today())}${field('شرح','ex')}</div><div class="actions"><button class="btn s" id="saveExp">ثبت هزینه</button></div><hr><div class="row">${field('شرح درآمد','idc')}${field('مبلغ درآمد','ida','number','0')}${field('تاریخ درآمد','idd','text',today())}</div><div class="actions"><button class="btn s" id="saveInc">ثبت درآمد</button></div>${table(DB.state.expenses.slice().reverse(),['تاریخ','دسته','مبلغ','شرح'],x=>[esc(x.jDate),esc(x.category),fmt(x.amount),esc(x.description||'—')])}`)}
function capitalView(){const ps=partners().length?partners():people();return box('سرمایه و شرکا',`<div class="row">${select('شخص','capP',options(ps))}${select('نوع','capT','<option value="CONTRIBUTION">افزایش سرمایه</option><option value="WITHDRAWAL">برداشت</option>')}${field('مبلغ','capA','number','0')}${field('تاریخ','capD','text',today())}</div><div class="actions"><button class="btn s" id="saveCap">ثبت رویداد</button></div><div class="row">${select('شریک','ownP',options(ps))}${field('درصد مالکیت','ownPct','number','0')}${field('تاریخ اثر','ownD','text',today())}</div><div class="actions"><button class="btn" id="saveOwn">ثبت مالکیت</button></div>${table(DB.state.ownershipHistory,['شریک','درصد','تاریخ'],x=>[esc(pname(x.partnerId)),n(x.ownershipPercent).toFixed(4)+'%',esc(x.effectiveDate)])}`)}
function reportsView(){const rows=Reports.customerBalances(today());return box('حساب جاری مشتریان',`<div class="row">${select('مشتری','stc','<option value="">همه</option>'+options(customers()))}${field('تاریخ محاسبه','std','text',today())}</div><div class="actions"><button class="btn" id="calcStmt">محاسبه</button></div><div id="stmt">${statement(rows)}</div>`)}
function statement(rows){return table(rows,['مشتری','مانده اصل','اعتبار','سود اطلاعاتی','وضعیت'],x=>[esc(x.customer.name),fmt(x.balance),fmt(x.credit),fmt(x.interest),x.balance>0?'<span class="tag d">بدهکار</span>':x.credit>0?'<span class="tag s">بستانکار</span>':'تسویه'])}
function settingsView(){return box('تنظیمات',`<div class="row">${field('مبنای روز','sdb','number',DB.state.settings.dayBasis)}${field('روز مهلت','sgd','number',DB.state.settings.graceDays)}${field('واحد پول','scu','text',DB.state.settings.currency)}</div><div class="actions"><button class="btn s" id="saveSet">ذخیره تنظیمات</button></div>${box('بسته‌های پرداخت',`<div class="row">${field('شناسه','pkgid')}${field('نام','pkgn')}</div><div class="row">${field('Tier1 روز','t1d','number','30')}${field('Tier1 نرخ','t1r','number','0')}${field('Tier2 روز','t2d','number','60')}${field('Tier2 نرخ','t2r','number','0.06')}</div><div class="row">${field('Tier3 روز','t3d','number','120')}${field('Tier3 نرخ','t3r','number','0.10')}${field('Tier4 روز','t4d','number','9999')}${field('Tier4 نرخ','t4r','number','0.15')}</div><div class="actions"><button class="btn s" id="savePkg">ثبت بسته</button></div>${table(DB.state.paymentPackages,['شناسه','نام','Tierها'],x=>[esc(x.id),esc(x.name),esc((x.tiers||[]).map(t=>t.maxDays+' روز / '+(n(t.rate)*100).toFixed(2)+'%').join(' | '))])}`)}${box('انبارها',table(DB.state.warehouses,['شناسه','نام'],x=>[esc(x.id),esc(x.name)]))}`)}
const views={dashboard,people:peopleView,products:productsView,prices:pricesView,sales:salesView,receipts:receiptsView,inventory:inventoryView,production:productionView,purchases:purchasesView,payments:paymentsView,expenses:expensesView,capital:capitalView,reports:reportsView,settings:settingsView};
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab;render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{current=b.dataset.go;render()});document.getElementById('addPerson')?.addEventListener('click',()=>document.getElementById('pd').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=DB.getPerson(b.dataset.edit);document.getElementById('pd').showModal();[['pn',p.name],['pc',p.company],['pp',p.phone],['pa',p.address],['pkg',p.paymentPackageId||''],['pnote',p.notes||'']].forEach(([i,x])=>{const z=document.getElementById(i);if(z)z.value=x});document.querySelectorAll('input[name="role"]').forEach(z=>z.checked=(p.roles||[]).includes(z.value));document.getElementById('savePerson').dataset.id=p.id});document.getElementById('savePerson')?.addEventListener('click',()=>run(()=>{const x={name:val('pn').trim(),company:val('pc'),phone:val('pp'),address:val('pa'),paymentPackageId:val('pkg')||null,notes:val('pnote'),roles:[...document.querySelectorAll('input[name="role"]:checked')].map(z=>z.value)};if(!x.name)throw Error('نام شخص الزامی است');const id=document.getElementById('savePerson').dataset.id;if(id)Transactions.updatePerson(id,x);else Transactions.addPerson(x);document.getElementById('pd').close()}));
document.getElementById('saveProduct')?.addEventListener('click',()=>run(()=>Transactions.addProduct({code:val('pcd'),name:val('pna').trim(),baseUnit:val('pbu'),packageUnit:val('ppu'),unitsPerPackage:n(val('upp')),pricingUnit:val('priunit'),warehouseId:val('pwh')})));
document.getElementById('savePrice')?.addEventListener('click',()=>run(()=>Transactions.addPrice({productId:val('prp'),customerId:val('prc')||null,price:n(val('prv')),effectiveDate:val('prd'),notes:val('prn')})));
const refreshSale=()=>{const p=DB.getProduct(val('sp')),u=document.getElementById('su');if(!p||!u)return;u.innerHTML=[p.baseUnit,p.packageUnit,p.pricingUnit].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).map(x=>`<option>${esc(x)}</option>`).join('');try{const q=Transactions.suggestedSalePrice(p.id,val('sc'),val('sd')||today(),u.value);document.getElementById('ss').value=q.unitPrice;document.getElementById('sup').value=q.unitPrice}catch(_){}};['sp','sc','sd','su'].forEach(i=>document.getElementById(i)?.addEventListener('change',refreshSale));['sq','sup'].forEach(i=>document.getElementById(i)?.addEventListener('input',()=>document.getElementById('st').value=n(val('sq'))*n(val('sup'))));refreshSale();document.getElementById('srp')?.addEventListener('click',refreshSale);document.getElementById('saveSale')?.addEventListener('click',()=>run(()=>Transactions.addSale({customerId:val('sc'),productId:val('sp'),salesUnit:val('su'),quantity:n(val('sq')),unitPrice:n(val('sup')),jDate:val('sd'),paymentPackageId:val('spp')||null})));
const rt=document.getElementById('rt'),toggle=()=>{const z=document.getElementById('cf');if(z)z.style.display=rt?.value==='چک'?'grid':'none'};rt?.addEventListener('change',toggle);toggle();document.getElementById('saveReceipt')?.addEventListener('click',()=>run(()=>Transactions.addReceipt({customerId:val('rc'),type:val('rt'),amount:n(val('ra')),jDate:val('rd'),status:val('rs'),checkNo:val('rno'),bank:val('rb'),dueDate:val('rdu')})));
document.getElementById('saveAdj')?.addEventListener('click',()=>run(()=>Transactions.addInventoryAdjustment({productId:val('ap'),warehouseId:val('aw'),baseQty:n(val('aq')),jDate:val('ad'),reason:val('ar')})));
document.getElementById('saveProd')?.addEventListener('click',()=>run(()=>Transactions.addProduction({id:DB.next('PROD'),productId:val('pp'),formulaId:val('pf'),actualQty:n(val('paq')),wasteQty:n(val('pwq')),jDate:val('pdt'),outputWarehouseId:val('pwo'),historicalCostBasis:n(val('phc')),manualUnitCost:n(val('pmc'))})));
document.getElementById('savePurchase')?.addEventListener('click',()=>run(()=>Transactions.addPurchase({supplierId:val('pus'),productId:val('pup'),warehouseId:val('puw'),quantity:n(val('puq')),unitPrice:n(val('pupx')),freight:n(val('puf')),unloading:n(val('puu')),costBasis:n(val('puc')),jDate:val('pud')})));
document.getElementById('savePay')?.addEventListener('click',()=>run(()=>Transactions.addPayment({payeeId:val('payee'),amount:n(val('payam')),type:val('paytype'),jDate:val('payd')})));
document.getElementById('saveExp')?.addEventListener('click',()=>run(()=>Transactions.addExpense({category:val('ec'),amount:n(val('ea')),jDate:val('ed'),description:val('ex')})));document.getElementById('saveInc')?.addEventListener('click',()=>run(()=>Transactions.addIncome({id:DB.next('INC'),description:val('idc'),amount:n(val('ida')),jDate:val('idd')})));
document.getElementById('saveCap')?.addEventListener('click',()=>run(()=>Transactions.addCapitalEvent({personId:val('capP'),eventType:val('capT'),amount:n(val('capA')),jDate:val('capD')})));document.getElementById('saveOwn')?.addEventListener('click',()=>run(()=>Transactions.setOwnership({partnerId:val('ownP'),ownershipPercent:n(val('ownPct')),effectiveDate:val('ownD')})));
document.getElementById('calcStmt')?.addEventListener('click',()=>{const d=val('std')||today(),id=val('stc'),r=id?Reports.customerBalances(d).filter(x=>x.customer.id===id):Reports.customerBalances(d);document.getElementById('stmt').innerHTML=statement(r)});
document.getElementById('saveSet')?.addEventListener('click',()=>run(()=>{DB.state.settings.dayBasis=n(val('sdb'))||30;DB.state.settings.graceDays=n(val('sgd'));DB.state.settings.currency=val('scu')||'ریال'}));document.getElementById('savePkg')?.addEventListener('click',()=>run(()=>{const id=val('pkgid').trim(),name=val('pkgn').trim()||id;if(!id)throw Error('شناسه بسته الزامی است');const tiers=[['t1','t1d','t1r'],['t2','t2d','t2r'],['t3','t3d','t3r'],['t4','t4d','t4r']].map(a=>({id:a[0],maxDays:n(val(a[1])),rate:n(val(a[2])),active:true}));const old=DB.getPaymentPackage(id);if(old)DB.updatePaymentPackage(id,{name,tiers,active:true});else DB.addPaymentPackage({id,name,tiers,active:true})}));}
function render(){const nav=document.getElementById('nav'),main=document.getElementById('main');nav.innerHTML=tabs.map(t=>`<button class="${t[0]===current?'on':''}" data-tab="${t[0]}">${t[1]}</button>`).join('');main.innerHTML=views[current]();bind()}
root.ProjectUI={render,setPage:p=>{if(views[p]){current=p;render()}}};
})(typeof globalThis!=='undefined'?globalThis:this);
