'use strict';
(function(root){
function op(type,payload,apply){const e=new AccountingOperations.OperationEngine({operations:DB.state.operations,effects:DB.state.effects,audit:DB.state.audit});const r=e.execute({operationType:type,idempotencyKey:payload.idempotencyKey||DB.next('IDEMP'),actorId:'WEB_USER',occurredDate:payload.jDate||DB.todayJ(),source:'WEB',payload},apply);DB.state.operations=e.operations;DB.state.effects=e.effects;DB.state.audit=e.audit;DB.save();return r;}
function addCustomer(x){if(!x.name)throw Error('نام مشتری الزامی است');return DB.add('customers',{id:DB.next('CUS'),name:x.name,company:x.company||'',phone:x.phone||'',active:true});}
function addProduct(x){if(!x.name)throw Error('نام کالا الزامی است');return DB.add('products',{id:DB.next('PRD'),name:x.name,baseUnit:x.baseUnit||'عدد',packUnit:x.packUnit||'کارتن',unitsPerPack:Number(x.unitsPerPack)||1,active:true});}
function addPrice(x){if(!x.productId||Number(x.price)<=0||!x.effectiveDate)throw Error('کالا، قیمت، تاریخ و مبلغ معتبر الزامی است');return DB.add('prices',{id:DB.next('PRICE'),productId:x.productId,customerId:x.customerId||'',price:Number(x.price),effectiveDate:x.effectiveDate,notes:x.notes||''});}
function addSale(x){if(!x.customerId||!x.productId||Number(x.quantity)<=0)throw Error('مشتری، کالا و تعداد الزامی است');const p=DB.currentPrice(x.productId,x.jDate||DB.todayJ(),x.customerId),unit=Number(x.unitPrice)||Number(p&&p.price);if(unit<=0)throw Error('قیمت معتبر یافت نشد');const row={id:DB.next('SALE'),customerId:x.customerId,productId:x.productId,quantity:Number(x.quantity),unitPrice:unit,amount:Number(x.quantity)*unit,jDate:x.jDate||DB.todayJ(),priceId:p&&p.id||'',status:'POSTED'};op('SALE',row,()=>[{EffectType:'SALE',RecordID:row.id,Value:row.amount}]);return DB.add('sales',row);}
function addReceipt(x){if(!x.customerId||Number(x.amount)<=0)throw Error('مشتری و مبلغ معتبر الزامی است');const row={id:DB.next('REC'),customerId:x.customerId,amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),type:x.type||'نقد',status:x.status||'وصول شده',dueDate:x.dueDate||'',originalReceiptId:x.originalReceiptId||''};op('RECEIPT',row,()=>[{EffectType:'RECEIPT',RecordID:row.id,Value:-row.amount}]);return DB.add('receipts',row);}
function addPurchase(x){if(!x.supplierId||!x.productId||Number(x.quantity)<=0)throw Error('تأمین‌کننده، کالا و تعداد الزامی است');const row={id:DB.next('PUR'),supplierId:x.supplierId,productId:x.productId,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice)||0,amount:Number(x.amount)||Number(x.quantity)*Number(x.unitPrice||0),jDate:x.jDate||DB.todayJ(),status:'POSTED'};op('PURCHASE',row,()=>[{EffectType:'PURCHASE',RecordID:row.id,Value:row.amount}]);return DB.add('purchases',row);}
function addPayment(x){if(!x.payeeId||Number(x.amount)<=0)throw Error('طرف حساب و مبلغ معتبر الزامی است');const row={id:DB.next('PAY'),payeeId:x.payeeId,amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),type:x.type||'نقد'};op('PAYMENT',row,()=>[{EffectType:'PAYMENT',RecordID:row.id,Value:-row.amount}]);return DB.add('payments',row);}
function addExpense(x){if(Number(x.amount)<=0)throw Error('مبلغ هزینه باید مثبت باشد');const row={id:DB.next('EXP'),category:x.category||'عمومی',amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),description:x.description||''};op('EXPENSE',row,()=>[{EffectType:'EXPENSE',RecordID:row.id,Value:row.amount}]);return DB.add('expenses',row);}
function customerStatement(customerId,calcDate){return AccountingDomain.Finance.fifo({customerId,calcDate:calcDate||DB.todayJ(),settings:DB.state.settings,sales:DB.state.sales,receipts:DB.state.receipts});}
root.Transactions={addCustomer,addProduct,addPrice,addSale,addReceipt,addPurchase,addPayment,addExpense,customerStatement};
})(typeof globalThis!=='undefined'?globalThis:this);
