'use strict';
(function(root){
function op(type,payload,apply){const e=new AccountingOperations.OperationEngine({operations:DB.state.operations,effects:DB.state.effects,audit:DB.state.audit});const r=e.execute({operationType:type,idempotencyKey:payload.idempotencyKey||DB.next('IDEMP'),actorId:'WEB_USER',occurredDate:payload.jDate||DB.todayJ(),source:'WEB',payload},apply);DB.state.operations=e.operations;DB.state.effects=e.effects;DB.state.audit=e.audit;DB.save();return r;}
function addPerson(x){if(!x.name)throw Error('نام شخص الزامی است');return DB.addPerson({id:x.id||DB.next('PER'),name:x.name,company:x.company||'',phone:x.phone||'',address:x.address||'',roles:Array.isArray(x.roles)?x.roles:[],paymentPackageId:x.paymentPackageId||null,notes:x.notes||'',active:x.active!==false});}
function addCustomer(x){return addPerson(Object.assign({},x,{roles:Array.from(new Set([...(x.roles||[]),'customer']))}));}
function updatePerson(id,x){return DB.updatePerson(id,{name:x.name,company:x.company,phone:x.phone,address:x.address,roles:x.roles,paymentPackageId:x.paymentPackageId||null,notes:x.notes||'',active:x.active!==false});}
function addProduct(x){if(!x.name)throw Error('نام کالا الزامی است');const baseUnit=x.baseUnit||'عدد',packageUnit=x.packageUnit||x.packUnit||'کارتن',unitsPerPackage=Number(x.unitsPerPackage||x.unitsPerPack)||1;return DB.addProduct({id:x.id||DB.next('PRD'),code:x.code||'',name:x.name,baseUnit,packageUnit,unitsPerPackage,pricingUnit:x.pricingUnit||baseUnit,warehouseId:x.warehouseId||'FG',active:x.active!==false,notes:x.notes||''});}
function addPrice(x){if(!x.productId||Number(x.price)<=0||!x.effectiveDate)throw Error('کالا، قیمت، تاریخ و مبلغ معتبر الزامی است');return DB.addPrice({id:x.id||DB.next('PRICE'),productId:x.productId,customerId:x.customerId||null,price:Number(x.price),effectiveDate:x.effectiveDate,notes:x.notes||''});}
function unitFactor(product,salesUnit){if(salesUnit===product.baseUnit)return 1;if(salesUnit===product.packageUnit)return Number(product.unitsPerPackage)||1;throw Error('واحد فروش برای این کالا تعریف نشده است');}
function suggestedSalePrice(productId,customerId,date,salesUnit){const p=DB.getProduct(productId);if(!p)throw Error('کالا یافت نشد');const price=DB.currentPrice(productId,date,customerId);if(!price)throw Error('قیمت معتبر برای این مشتری/تاریخ یافت نشد');const factor=unitFactor(p,salesUnit||p.pricingUnit||p.baseUnit);return{priceRecord:price,baseUnitPrice:Number(price.price),unitPrice:Number(price.price)*factor,factor};}
function addSale(x){if(!x.customerId||!x.productId||Number(x.quantity)<=0)throw Error('شخص، کالا و تعداد الزامی است');const p=DB.getProduct(x.productId);if(!p)throw Error('کالا یافت نشد');const salesUnit=x.salesUnit||p.pricingUnit||p.baseUnit,suggestion=suggestedSalePrice(x.productId,x.customerId,x.jDate||DB.todayJ(),salesUnit),manual=Number(x.unitPrice)>0,unitPrice=manual?Number(x.unitPrice):suggestion.unitPrice,baseQuantity=Number(x.quantity)*suggestion.factor,row={id:DB.next('SALE'),customerId:x.customerId,productId:x.productId,salesUnit,quantity:Number(x.quantity),baseQuantity,unitPrice,baseUnitPrice:suggestion.baseUnitPrice,amount:Number(x.quantity)*unitPrice,jDate:x.jDate||DB.todayJ(),priceId:suggestion.priceRecord.id,manualPrice:manual,status:'POSTED',paymentPackageId:x.paymentPackageId??((DB.getCustomer(x.customerId)||{}).paymentPackageId||null),notes:x.notes||''};const result=op('SALE',row,()=>[{EffectType:'SALE',RecordID:row.id,Value:row.amount,Quantity:row.baseQuantity}]);row.operationId=result.operation.OperationID;return DB.add('sales',row);}
function addReceipt(x){if(!x.customerId||Number(x.amount)<=0)throw Error('شخص و مبلغ معتبر الزامی است');const type=x.type||'نقد',isCheck=type==='چک',status=x.status||'وصول شده',row={id:DB.next('REC'),customerId:x.customerId,amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),type,status,dueDate:isCheck?(x.dueDate||''):'',checkNo:isCheck?(x.checkNo||''):'',bank:isCheck?(x.bank||''):'',originalReceiptId:x.originalReceiptId||'',notes:x.notes||''};const result=op('RECEIPT',row,()=>[{EffectType:'RECEIPT',RecordID:row.id,Value:-row.amount}]);row.operationId=result.operation.OperationID;const saved=DB.add('receipts',row);if(isCheck){DB.add('checks',{id:row.id,receiptId:row.id,customerId:row.customerId,amount:row.amount,jDate:row.jDate,dueDate:row.dueDate,checkNo:row.checkNo,bank:row.bank,status:row.status,originalReceiptId:row.originalReceiptId,notes:row.notes});DB.addCheckEvent({receiptId:row.id,fromStatus:null,toStatus:row.status,eventDate:row.jDate,notes:'ثبت اولیه چک'});}return saved;}
function changeReceiptStatus(receiptId,toStatus,opts){const row=DB.state.receipts.find(x=>x.id===receiptId);if(!row)throw Error('RECEIPT_NOT_FOUND');if(row.type!=='چک')throw Error('CHECK_EVENT_ONLY_FOR_CHECKS');const fromStatus=row.status||null;if(fromStatus===toStatus)return row;const patchDate=(opts&&opts.actualDate)||DB.todayJ();op('CHECK_STATUS_CHANGE',{receiptId,fromStatus,toStatus,jDate:patchDate},()=>[{EffectType:'CHECK_STATUS_CHANGE',RecordID:receiptId,Value:0}]);row.status=toStatus;if(opts&&opts.actualDate)row.actualDate=opts.actualDate;DB.addCheckEvent({receiptId,fromStatus,toStatus,eventDate:patchDate,notes:(opts&&opts.notes)||''});const check=DB.state.checks.find(x=>x.receiptId===receiptId||x.id===receiptId);if(check){check.status=toStatus;if(opts&&opts.actualDate)check.actualDate=opts.actualDate;DB.save();}return row;}
function addPurchase(x){if(!x.supplierId||!x.productId||Number(x.quantity)<=0)throw Error('تأمین‌کننده، کالا و تعداد الزامی است');const row={id:DB.next('PUR'),supplierId:x.supplierId,productId:x.productId,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice)||0,amount:Number(x.amount)||Number(x.quantity)*Number(x.unitPrice||0),jDate:x.jDate||DB.todayJ(),status:'POSTED'};const result=op('PURCHASE',row,()=>[{EffectType:'PURCHASE',RecordID:row.id,Value:row.amount,Quantity:row.quantity}]);row.operationId=result.operation.OperationID;return DB.add('purchases',row);}
function addPayment(x){if(!x.payeeId||Number(x.amount)<=0)throw Error('طرف حساب و مبلغ معتبر الزامی است');const row={id:DB.next('PAY'),payeeId:x.payeeId,amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),type:x.type||'نقد'};const result=op('PAYMENT',row,()=>[{EffectType:'PAYMENT',RecordID:row.id,Value:-row.amount}]);row.operationId=result.operation.OperationID;return DB.add('payments',row);}
function addExpense(x){if(Number(x.amount)<=0)throw Error('مبلغ هزینه باید مثبت باشد');const row={id:DB.next('EXP'),category:x.category||'عمومی',amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),description:x.description||''};const result=op('EXPENSE',row,()=>[{EffectType:'EXPENSE',RecordID:row.id,Value:row.amount}]);row.operationId=result.operation.OperationID;return DB.add('expenses',row);}
function customerStatement(customerId,calcDate){return AccountingDomain.Finance.fifo({customerId,calcDate:calcDate||DB.todayJ(),settings:{dayBasis:DB.state.settings.dayBasis,tiers:DB.state.settings.tiers,paymentPackages:DB.state.paymentPackages},sales:DB.state.sales,receipts:DB.state.receipts});}
root.Transactions={addPerson,addCustomer,updatePerson,addProduct,addPrice,unitFactor,suggestedSalePrice,addSale,addReceipt,changeReceiptStatus,addPurchase,addPayment,addExpense,customerStatement};
})(typeof globalThis!=='undefined'?globalThis:this);
