'use strict';
(function(root){
const M=root.AccountingModules,DB=root.DB,T=root.Transactions;
if(!M||!DB||!T)throw new Error('MODULE_DEPENDENCY_NOT_READY');
function commit(type,row,effects){const e=new AccountingOperations.OperationEngine({operations:DB.state.operations,effects:DB.state.effects,audit:DB.state.audit});const r=e.execute({operationType:type,idempotencyKey:row.idempotencyKey||DB.next('IDEMP'),actorId:'WEB_USER',occurredDate:row.jDate||DB.todayJ(),source:'WEB',payload:row},()=>effects||[]);DB.state.operations=e.operations;DB.state.effects=e.effects;DB.save();return r;}
function addMovement(row){return DB.add('inventoryMovements',row);}
function addPurchase(x){const row=M.purchase({...x,id:x.id||DB.next('PUR'),jDate:x.jDate||DB.todayJ()});commit('PURCHASE',row,M.purchaseEffects(row));addMovement({id:DB.next('MOV'),productId:row.productId,warehouseId:row.warehouseId,jDate:row.jDate,type:'purchase',baseQty:row.baseQuantity,source:'PURCHASE',sourceId:row.id});return DB.add('purchases',row);}
function addInventoryAdjustment(x){if(!x.productId||!x.warehouseId||Number(x.baseQty)===0)throw Error('INVALID_INVENTORY_ADJUSTMENT');const row={id:x.id||DB.next('ADJ'),productId:x.productId,warehouseId:x.warehouseId,baseQty:Number(x.baseQty),jDate:x.jDate||DB.todayJ(),reason:x.reason||'',status:'POSTED'};commit('INVENTORY_ADJUSTMENT',row,[{EffectType:'INVENTORY_ADJUSTMENT',RecordID:row.id,Quantity:row.baseQty}]);addMovement({...row,type:row.baseQty>0?'adjustmentIn':'adjustmentOut',source:'INVENTORY_ADJUSTMENT',sourceId:row.id});return row;}
function transferWarehouse(x){const date=x.jDate||DB.todayJ(),id=x.id||DB.next('TRN'),stock=M.stock(DB.state.inventoryMovements,x.productId,x.fromWarehouseId,date);const rows=M.transferWarehouse({...x,transferId:id,jDate:date},stock);commit('WAREHOUSE_TRANSFER',{...x,id,jDate:date},rows.map(r=>({EffectType:r.type==='transferOut'?'INVENTORY_OUT':'INVENTORY_IN',RecordID:r.id,Quantity:r.baseQty})));rows.forEach(addMovement);return rows;}
function reconcileInventory(counts){return M.reconcileInventory(DB.state.inventoryMovements,counts);}
function addConversion(x){const row=M.normalizeConversion({...x,id:x.id||DB.next('CV'),effectiveDate:x.effectiveDate||DB.todayJ()});return DB.add('conversions',row);}
function addIncome(x){const row=M.income({id:x.id||DB.next('INC'),...x,jDate:x.jDate||DB.todayJ()});commit('INCOME',row,[{EffectType:'INCOME',RecordID:row.id,Amount:row.amount}]);return DB.add('incomes',row);}
function addSaleReturn(x){const row=M.returnSale({id:x.id||DB.next('SR'),...x,jDate:x.jDate||DB.todayJ()});commit('RETURN',row,[{EffectType:'SALE_RETURN',RecordID:row.id,Quantity:-Number(row.quantity)}]);return DB.add('saleReturns',row);}
function addPurchaseReturn(x){const row=M.returnPurchase({id:x.id||DB.next('PRR'),...x,jDate:x.jDate||DB.todayJ()});commit('RETURN',row,[{EffectType:'PURCHASE_RETURN',RecordID:row.id,Quantity:-Number(row.quantity)}]);return DB.add('purchaseReturns',row);}
function addTreasuryAccount(x){if(!x.name)throw Error('ACCOUNT_NAME_REQUIRED');return DB.add('treasuryAccounts',{id:x.id||DB.next('ACC'),name:x.name,type:x.type||'bank',openingBalance:Number(x.openingBalance)||0,active:x.active!==false,notes:x.notes||''});}
function addTreasuryTransfer(x){const row={id:x.id||DB.next('TRF'),sourceAccountId:x.sourceAccountId,destinationAccountId:x.destinationAccountId,amount:Number(x.amount),jDate:x.jDate||DB.todayJ(),notes:x.notes||'',status:'POSTED'};commit('TRANSFER',row,M.accountTransfer(row));return DB.add('treasuryTransfers',row);}
function changeCheckStatus(id,toStatus,opts){const r=DB.state.receipts.find(x=>x.id===id);if(!r)throw Error('RECEIPT_NOT_FOUND');M.checkStatusTransition(r.status,toStatus);return T.changeReceiptStatus(id,toStatus,opts||{});}
function replaceCheck(originalId,x){const original=DB.state.receipts.find(r=>r.id===originalId);if(!original)throw Error('RECEIPT_NOT_FOUND');const row=M.replaceCheck(original,{...x,id:x.id||DB.next('REC'),customerId:original.customerId,amount:Number(x.amount||original.amount),type:'چک',jDate:x.jDate||DB.todayJ()},DB.state.receipts);commit('CHECK_REPLACEMENT',row,[{EffectType:'CHECK_REPLACEMENT',RecordID:row.id,Amount:row.amount}]);DB.add('receipts',row);DB.add('checks',{id:row.id,receiptId:row.id,customerId:row.customerId,amount:row.amount,jDate:row.jDate,dueDate:row.dueDate||'',checkNo:row.checkNo||'',bank:row.bank||'',status:row.status,originalReceiptId:original.id});DB.addCheckEvent({receiptId:row.id,fromStatus:null,toStatus:row.status,eventDate:row.jDate,notes:'جایگزینی چک'});return row;}
function addFormula(x){if(!x.productId||!x.effectiveDate)throw Error('INVALID_FORMULA');M.validateFormulaGraph([...DB.state.formulas,x]);const row={id:x.id||DB.next('FORM'),productId:x.productId,effectiveDate:x.effectiveDate,version:Number(x.version||1),inputs:Array.isArray(x.inputs)?x.inputs:[],outputs:Array.isArray(x.outputs)?x.outputs:[],notes:x.notes||'',active:x.active!==false};return DB.add('formulas',row);}
function addProduction(x){const row=M.production({...x,id:x.id||DB.next('PROD'),jDate:x.jDate||DB.todayJ()},DB.state.formulas);commit('PRODUCTION',row,M.productionEffects(row));if(row.goodQty>0)addMovement({id:DB.next('MOV'),productId:row.productId,warehouseId:x.outputWarehouseId||'FG',jDate:row.jDate,type:'productionIn',baseQty:row.goodQty,source:'PRODUCTION',sourceId:row.id});return DB.add('productions',row);}
function addCostSnapshot(x){const row={id:x.id||DB.next('COST'),productId:x.productId,effectiveDate:x.effectiveDate||DB.todayJ(),costBasis:Number(x.costBasis)||0,source:x.source||'MANUAL',notes:x.notes||''};return DB.add('costSnapshots',row);}
function addCapitalEvent(x){const row=M.capitalEvent({id:x.id||DB.next('CAP'),...x,jDate:x.jDate||DB.todayJ()});commit('CAPITAL_EVENT',row,[{EffectType:'CAPITAL',RecordID:row.id,Amount:row.eventType==='WITHDRAWAL'?-row.amount:row.amount}]);return DB.add('capitalEvents',row);}
function setOwnership(x){const row={id:x.id||DB.next('OWN'),partnerId:x.partnerId,ownershipPercent:Number(x.ownershipPercent),effectiveDate:x.effectiveDate||DB.todayJ(),active:true};const rows=[...(DB.state.ownershipHistory||[]).filter(r=>r.effectiveDate!==row.effectiveDate),row];M.validateOwnership(rows);DB.state.ownershipHistory=rows;DB.save();return row;}
function transferShare(x){const current=(DB.state.ownershipHistory||[]).filter(r=>r.effectiveDate===x.effectiveDate||!x.effectiveDate);const rows=M.transferShare(x,current);const row={...x,id:x.id||DB.next('SHARE'),jDate:x.jDate||DB.todayJ(),status:'POSTED'};commit('SHARE_TRANSFER',row,[{EffectType:'SHARE_TRANSFER',RecordID:row.id,Amount:0}]);DB.state.ownershipHistory=rows.map(r=>({...r,effectiveDate:row.jDate}));DB.state.shareTransfers.push(row);DB.save();return row;}
function addEmployee(x){if(!x.name)throw Error('EMPLOYEE_NAME_REQUIRED');return DB.add('employees',{id:x.id||DB.next('EMP'),name:x.name,role:x.role||'',startDate:x.startDate||DB.todayJ(),active:x.active!==false,notes:x.notes||''});}
function addPayroll(x){const row=M.payroll({id:x.id||DB.next('PAY'),...x});commit('PAYROLL',row,[{EffectType:'PAYROLL',RecordID:row.id,Amount:row.employerCost}]);return DB.add('payrolls',row);}
root.Transactions=Object.assign({},T,{addPurchase,addInventoryAdjustment,transferWarehouse,reconcileInventory,addConversion,addIncome,addSaleReturn,addPurchaseReturn,addTreasuryAccount,addTreasuryTransfer,changeCheckStatus,replaceCheck,addFormula,addProduction,addCostSnapshot,addCapitalEvent,setOwnership,transferShare,addEmployee,addPayroll});
})(typeof globalThis!=='undefined'?globalThis:this);
