'use strict';
(function(){
  const E=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const N=v=>Number.isFinite(Number(v))?Number(v):0;
  const F=v=>Math.round(N(v)).toLocaleString('en-US');
  const S=()=>DB.state;
  const arr=k=>S()[k]||[];
  const person=id=>arr('people').find(x=>x.id===id)||{};
  const product=id=>arr('products').find(x=>x.id===id)||{};
  const people=()=>arr('people').filter(x=>x.active!==false);
  const customers=()=>people().filter(x=>(Array.isArray(x.roles)?x.roles:[x.role]).includes('customer'));
  const accounts=()=>arr('treasuryAccounts').length?arr('treasuryAccounts'):arr('accounts');
  const opts=(a,ph='انتخاب کنید')=>'<option value="">'+ph+'</option>'+a.map(x=>'<option value="'+E(x.id)+'">'+E(x.name||x.title||x.code||x.id)+'</option>').join('');
  const btn=(t,a,c='')=>'<button class="u-btn '+c+'" data-u="'+E(a)+'">'+t+'</button>';
  const inp=(l,id,type='text',v='',x='')=>'<label class="u-field"><span>'+l+'</span><input id="'+id+'" type="'+type+'" value="'+E(v)+'" '+x+'></label>';
  const sel=(l,id,h)=>'<label class="u-field"><span>'+l+'</span><select id="'+id+'">'+h+'</select></label>';
  function modal(id,title,body){return '<div class="u-modal" id="'+id+'"><div class="u-card"><div class="u-head"><b>'+title+'</b><button class="u-close" data-u="close:'+id+'">×</button></div><div class="u-body">'+body+'</div></div></div>'}
  function open(id){document.getElementById(id)?.classList.add('open')}
  function close(id){document.getElementById(id)?.classList.remove('open')}
  function actions(t,id){return '<span class="u-actions">'+btn('ویرایش','edit:'+t+':'+id,'icon')+' '+btn('حذف','delete:'+t+':'+id,'icon danger')+'</span>'}
  function table(h,rows){return rows.length?'<div class="u-table"><table><thead><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>':'<div class="u-empty">رکوردی ثبت نشده است.</div>'}
  function page(t,a,b){return '<section class="u-page"><div class="u-title"><h2>'+t+'</h2>'+(a?btn('＋ افزودن',a,'primary'):'')+'</div>'+b+'</section>'}
  function val(id){return document.getElementById(id)?.value||''}
  function save(){DB.save();render()}
  const T=[['dashboard','داشبورد','📊'],['people','اشخاص','👥'],['products','کالاها','📦'],['warehouses','انبارها','🏭'],['inventory','موجودی','📋'],['prices','قیمت‌ها','💰'],['sales','فروش','🧾'],['transactions','دریافت/پرداخت/چک','💳'],['accounts','حساب‌های مالی','🏦'],['packages','بسته و پله سود','📈'],['statement','حساب جاری','📒'],['reports','گزارش‌ها','📊'],['settings','تنظیمات','⚙️']];
  let tab=sessionStorage.getItem('u-tab')||'dashboard';
  function nav(){document.getElementById('nav').innerHTML='<div class="u-nav">'+T.map(x=>'<button class="'+(tab===x[0]?'on':'')+'" data-tab="'+x[0]+'">'+x[2]+' '+x[1]+'</button>').join('')+'</div>'}
  function dashboard(){const st=S(),sales=arr('sales').reduce((n,x)=>n+N(x.netAmount??x.amount),0),rec=arr('receipts').filter(x=>x.status!=='برگشتی'&&x.status!=='باطل').reduce((n,x)=>n+N(x.amount),0);return page('داشبورد',null,'<div class="u-kpis"><div><small>فروش</small><b>'+F(sales)+'</b></div><div><small>دریافت</small><b>'+F(rec)+'</b></div><div><small>مانده پایه</small><b>'+F(sales-rec)+'</b></div><div><small>انبار</small><b>'+arr('warehouses').filter(x=>x.active!==false).length+'</b></div></div><div class="u-cardbox"><h3>وضعیت</h3><div class="u-summary">'+st.people.length+' شخص · '+st.products.length+' کالا · '+arr('warehouses').length+' انبار · '+st.sales.length+' فروش · '+st.receipts.length+' دریافت · '+st.checks.length+' چک</div></div>')}
  function peoplePage(){const rows=arr('people').map(x=>'<tr><td>'+E(x.name)+'</td><td>'+E(x.company||'—')+'</td><td>'+E(x.phone||'—')+'</td><td>'+E(Array.isArray(x.roles)?x.roles.join('، '):(x.role||'—'))+'</td><td>'+ (x.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('person',x.id)+'</td></tr>');return page('اشخاص','new:person',table(['نام','شرکت','تلفن','نقش','وضعیت','عملیات'],rows)+modal('m-person','شخص جدید / ویرایش',inp('نام *','p-name')+inp('شرکت','p-company')+inp('تلفن','p-phone')+inp('آدرس','p-address')+sel('نقش','p-role','<option value="customer">مشتری</option><option value="supplier">تأمین‌کننده</option><option value="partner">شریک</option><option value="worker">کارگر</option><option value="other">سایر</option>')+sel('وضعیت','p-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+`<div class="u-save">${btn('ذخیره','save:person','success')} ${btn('انصراف','close:m-person')}</div>`))}
  function productsPage(){const rows=arr('products').map(x=>'<tr><td>'+E(x.code||x.id)+'</td><td>'+E(x.name)+'</td><td>'+E(x.baseUnit||'عدد')+'</td><td>'+E(x.packageUnit||'کارتن')+'</td><td>'+N(x.unitsPerPackage||36)+'</td><td>'+E(x.pricingUnit||x.baseUnit||'عدد')+'</td><td>'+ (x.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('product',x.id)+'</td></tr>');return page('کالاها','new:product',table(['کد','نام','واحد پایه','واحد دوم','ضریب تبدیل','قیمت‌گذاری','وضعیت','عملیات'],rows)+modal('m-product','کالا جدید / ویرایش',inp('کد کالا','p-code')+inp('نام *','p-name')+inp('واحد پایه','p-base','text','عدد')+inp('واحد دوم','p-pack','text','کارتن')+inp('تعداد پایه در واحد دوم','p-mult','number','36')+sel('واحد قیمت‌گذاری','p-priceunit','<option>عدد</option><option>کیلوگرم</option><option>بسته</option>')+sel('انبار پیش‌فرض','p-wh',opts(arr('warehouses'),'بدون انبار'))+sel('وضعیت','p-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+`<div class="u-save">${btn('ذخیره','save:product','success')} ${btn('انصراف','close:m-product')}</div>`))}
  function warehousesPage(){const rows=arr('warehouses').map(x=>'<tr><td>'+E(x.id)+'</td><td>'+E(x.name)+'</td><td>'+E(x.type||'سایر')+'</td><td>'+ (x.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('warehouse',x.id)+'</td></tr>');return page('انبارها','new:warehouse',table(['کد','نام','نوع','وضعیت','عملیات'],rows)+modal('m-warehouse','انبار جدید / ویرایش',inp('کد انبار *','w-id')+inp('نام انبار *','w-name')+sel('نوع','w-type','<option>مواد اولیه</option><option>محصول تولیدی</option><option>بازرگانی</option><option>سایر</option>')+sel('وضعیت','w-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+inp('توضیحات','w-note')+`<div class="u-save">${btn('ذخیره','save:warehouse','success')} ${btn('انصراف','close:m-warehouse')}</div>`))}
  function inventoryPage(){const ws=arr('warehouses'),cur=sessionStorage.getItem('u-wh')||ws.find(x=>x.active!==false)?.id||'';const rows=arr('inventoryMovements').filter(x=>x.warehouseId===cur).map(x=>'<tr><td>'+E(x.jDate||x.date||'—')+'</td><td>'+E(product(x.productId).name||'—')+'</td><td>'+E(x.type||'—')+'</td><td>'+N(x.quantity??x.qty)+'</td><td>'+E(x.unit||'عدد')+'</td><td>'+actions('inventory',x.id)+'</td></tr>');return page('موجودی','new:inventory','<div class="u-tabs">'+ws.map(w=>'<button class="'+(cur===w.id?'on':'')+'" data-u="wh-tab:'+w.id+'">'+E(w.name)+'</button>').join('')+'</div>'+table(['تاریخ','کالا','نوع حرکت','مقدار','واحد','عملیات'],rows)+modal('m-inventory','ثبت / اصلاح موجودی',sel('انبار','i-wh',opts(ws))+sel('کالا','i-product',opts(arr('products')))+sel('نوع حرکت','i-type','<option>ورود</option><option>خروج</option><option>موجودی اولیه بدون بار مالی</option><option>اصلاح دستی</option><option>انتقال</option>')+inp('مقدار','i-qty','number','0')+inp('واحد','i-unit','text','عدد')+inp('تاریخ','i-date','text',DB.todayJ?.()||'')+inp('توضیحات','i-note')+`<div class="u-save">${btn('ذخیره','save:inventory','success')} ${btn('انصراف','close:m-inventory')}</div>`))}
  function priceFor(pid,unit){const p=product(pid),d=DB.todayJ?.()||'',a=arr('prices').filter(x=>x.productId===pid&&(x.unit||x.pricingUnit||p.baseUnit||'عدد')===unit&&String(x.effectiveDate||'')<=d).sort((x,y)=>String(y.effectiveDate).localeCompare(String(x.effectiveDate)));return N(a[0]?.price??a[0]?.unitPrice)}
  function pricesPage(){const rows=arr('prices').slice().sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate))).map(x=>'<tr><td>'+E(product(x.productId).name||'—')+'</td><td>'+E(x.unit||x.pricingUnit||'عدد')+'</td><td>'+F(x.price??x.unitPrice)+'</td><td>'+E(x.effectiveDate||'—')+'</td><td>'+actions('price',x.id)+'</td></tr>');return page('تاریخچه قیمت','new:price',table(['کالا','واحد','قیمت','تاریخ اعتبار','عملیات'],rows)+modal('m-price','قیمت جدید / ویرایش',sel('کالا','pr-product',opts(arr('products')))+sel('واحد','pr-unit','<option>عدد</option><option>کیلوگرم</option><option>کارتن</option><option>بسته</option>')+inp('قیمت واحد','pr-price','number','0')+inp('تاریخ اعتبار','pr-date','text',DB.todayJ?.()||'')+inp('یادداشت','pr-note')+`<div class="u-save">${btn('ذخیره','save:price','success')} ${btn('انصراف','close:m-price')}</div>`))}
  function salesPage(){const rows=arr('sales').slice().reverse().filter(x=>!x.isDiscountDocument).map(x=>'<tr><td>'+E(x.invoiceNo||'—')+'</td><td>'+E(x.jDate||'')+'</td><td>'+E(person(x.customerId).name||'—')+'</td><td>'+E(product(x.productId).name||'—')+'</td><td>'+E(x.salesUnit||x.unit||'عدد')+'</td><td>'+N(x.quantity)+'</td><td>'+F(x.unitPrice)+'</td><td>'+F(x.grossAmount??x.amount)+'</td><td>'+F(x.discount||0)+'</td><td>'+F(x.netAmount??x.amount)+'</td><td>'+actions('sale',x.id)+'</td></tr>');return page('فروش و فاکتور','new:sale',table(['فاکتور','تاریخ','مشتری','کالا','واحد','مقدار','قیمت واحد','ناخالص','تخفیف','نهایی','عملیات'],rows)+modal('m-sale','ثبت فروش',sel('مشتری','s-customer',opts(customers()))+sel('کالا','s-product',opts(arr('products')))+sel('واحد فروش','s-unit','<option value="base">واحد پایه</option><option value="package">واحد دوم / کارتن</option>')+inp('مقدار','s-qty','number','1')+inp('قیمت واحد منتخب','s-price','number','0','readonly')+inp('تخفیف فاکتور','s-discount','number','0')+'<div id="s-calc" class="u-calc">جمع: ۰</div>'+inp('شماره فاکتور','s-invoice')+inp('تاریخ','s-date','text',DB.todayJ?.()||'')+`<div class="u-save">${btn('ثبت فروش','save:sale','success')} ${btn('تخفیف مستقل','open:m-discount','warning')} ${btn('انصراف','close:m-sale')}</div>`)+modal('m-discount','تخفیف مستقل',sel('مشتری','d-customer',opts(customers()))+inp('مبلغ تخفیف','d-amount','number','0')+inp('شماره مرجع','d-invoice')+inp('تاریخ','d-date','text',DB.todayJ?.()||'')+inp('توضیح','d-note')+`<div class="u-save">${btn('ثبت تخفیف','save:discount','success')} ${btn('انصراف','close:m-discount')}</div>`))}
  function transactionsPage(){const r=arr('receipts').map(x=>Object.assign({kind:'دریافت',who:x.customerId},x)).concat(arr('payments').map(x=>Object.assign({kind:'پرداخت',who:x.payeeId},x))).sort((a,b)=>String(b.jDate||'').localeCompare(String(a.jDate||'')));const rows=r.map(x=>{const returned=x.returned||x.status==='برگشتی',paid=x.kind==='پرداخت';const cls=returned?'returned':paid?'paid':'received';return '<tr class="u-row '+cls+'"><td>'+E(x.jDate||'')+'</td><td><b>'+E(x.kind)+'</b></td><td>'+E(person(x.who).name||'—')+'</td><td>'+E(x.method||x.receiptType||'نقد')+'</td><td>'+F(x.amount)+'</td><td><select class="inline-status" data-kind="'+(paid?'payment':'receipt')+'" data-id="'+E(x.id)+'"><option '+(x.status==='نزد ما'||!x.status?'selected':'')+'>نزد ما</option><option '+(x.status==='تودیع شده'?'selected':'')+'>تودیع شده</option><option '+(x.status==='وصول شده'?'selected':'')+'>وصول شده</option><option '+(x.status==='برگشتی'?'selected':'')+'>برگشتی</option></select></td><td>'+E(x.accountId||'—')+'</td><td><label class="u-check"><input type="checkbox" data-ret="'+E(x.id)+'" '+(returned?'checked':'')+'>برگشتی</label></td><td>'+actions(paid?'payment':'receipt',x.id)+(paid?'':btn('جایگزین','replace:'+x.id,'icon'))+'</td></tr>'});const st=S();return page('دریافت / پرداخت / چک','new:transaction','<div class="u-legend"><span class="received">دریافت</span><span class="paid">پرداخت</span><span class="returned">برگشتی</span><span class="collected">وصول شده</span></div>'+table(['تاریخ','نوع','طرف حساب','روش','مبلغ','وضعیت','نزد / حساب','برگشتی','عملیات'],rows)+modal('m-transaction','ثبت تراکنش',sel('نوع تراکنش','t-kind','<option>دریافت</option><option>پرداخت</option>')+sel('طرف حساب','t-person',opts(people()))+sel('روش','t-method','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')+inp('مبلغ','t-amount','number','0')+inp('تاریخ','t-date','text',DB.todayJ?.()||'')+inp('سررسید چک','t-due')+sel('وضعیت','t-status','<option>نزد ما</option><option>تودیع شده</option><option>وصول شده</option><option>برگشتی</option>')+sel('حساب','t-account',opts(accounts()))+`<div class="u-save">${btn('ثبت تراکنش','save:transaction','success')} ${btn('انصراف','close:m-transaction')}</div>`)+modal('m-replace','جایگزینی',sel('روش جایگزین','r-method','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک جدید</option>')+sel('حساب جایگزین','r-account',opts(accounts()))+inp('مبلغ','r-amount','number','0')+inp('تاریخ','r-date','text',DB.todayJ?.()||'')+inp('مرجع/شماره چک جدید','r-ref')+`<div class="u-save">${btn('ثبت جایگزینی','save:replacement','success')} ${btn('انصراف','close:m-replace')}</div>`))}
  function accountsPage(){const rows=accounts().map(x=>'<tr><td>'+E(x.id)+'</td><td>'+E(x.name||x.title)+'</td><td>'+E(x.type||'حساب مالی')+'</td><td>'+ (x.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('account',x.id)+'</td></tr>');return page('حساب‌های مالی','new:account',table(['کد','نام','نوع','وضعیت','عملیات'],rows)+modal('m-account','حساب مالی جدید / ویرایش',inp('کد حساب *','a-id')+inp('نام حساب *','a-name')+sel('نوع','a-type','<option>بانک</option><option>صندوق</option><option>کارت</option><option>حساب جاری</option><option>سایر</option>')+sel('وضعیت','a-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+`<div class="u-save">${btn('ذخیره','save:account','success')} ${btn('انصراف','close:m-account')}</div>`))}
  function packagesPage(){const rows=arr('paymentPackages').map(p=>'<tr><td>'+E(p.id)+'</td><td>'+E(p.name||p.id)+'</td><td>'+ (p.active===false?'غیرفعال':'فعال')+'</td><td>'+((p.tiers||[]).filter(t=>t.active!==false).map(t=>N(t.maxDays)+' روز / '+(N(t.rate)*100).toFixed(2)+'%').join(' | ')||'—')+'</td><td>'+actions('package',p.id)+' '+btn('پله‌ها','tiers:'+p.id,'icon')+'</td></tr>');return page('بسته پرداخت و پله سود','new:package',table(['شناسه','نام','وضعیت','پله‌های فعال','عملیات'],rows)+modal('m-package','بسته پرداخت',inp('شناسه بسته *','g-id')+inp('نام بسته *','g-name')+sel('وضعیت','g-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+`<div class="u-save">${btn('ذخیره','save:package','success')} ${btn('انصراف','close:m-package')}</div>`)+modal('m-tiers','مدیریت پله‌ها','<div id="tiers-list"></div>'+`<div class="u-save">${btn('＋ پله جدید','add-tier','primary')} ${btn('ذخیره پله‌ها','save:tiers','success')} ${btn('انصراف','close:m-tiers')}</div>`))}
  function renderTiers(id){const p=arr('paymentPackages').find(x=>x.id===id),z=document.getElementById('tiers-list'),m=document.getElementById('m-tiers');if(!p||!z||!m)return;m.dataset.pkg=id;z.innerHTML=(p.tiers||[]).map((t,i)=>'<div class="u-tier"><b>پله '+(i+1)+'</b>'+inp('حداکثر روز','td'+i,'number',t.maxDays)+inp('درصد ماهانه','tr'+i,'number',N(t.rate)*100)+sel('وضعیت','ta'+i,t.active===false?'<option value="0" selected>غیرفعال</option><option value="1">فعال</option>':'<option value="1" selected>فعال</option><option value="0">غیرفعال</option>')+btn('حذف پله','del-tier:'+i,'icon danger')+'</div>').join('')||'<div class="u-empty">پله‌ای وجود ندارد.</div>'}
  function statementPage(){const cs=customers(),id=sessionStorage.getItem('u-person')||cs[0]?.id||'',sum=id?customerSummary(id):{totalSales:0,totalReceipts:0,balance:0,credit:0};return page('حساب جاری',null,sel('مشتری','st-person',opts(cs))+`<div class="u-kpis"><div><small>فروش</small><b>${F(sum.totalSales)}</b></div><div><small>دریافت</small><b>${F(sum.totalReceipts)}</b></div><div><small>مانده</small><b>${F(sum.balance)}</b></div><div><small>اعتبار</small><b>${F(sum.credit)}</b></div></div>`)}
  function settingsPage(){const s=S().settings||{};return page('تنظیمات',null,'<div class="u-cardbox">'+inp('مبنای روز','set-basis','number',s.dayBasis||30)+inp('مهلت پایه','set-grace','number',s.graceDays||30)+inp('واحد پول','set-currency','text',s.currency||'ریال')+`<div class="u-save">${btn('ذخیره','save:settings','success')}</div></div>`)}
  function reportsPage(){return page('گزارش‌ها',null,'<div class="u-cardbox"><h3>گزارش‌های سامانه</h3><p class="u-note">نمایش گزارش‌ها از همان داده و موتور محاسباتی مشترک انجام می‌شود؛ در این مرحله رابط یکپارچه و بدون فرم جانبی شده است.</p></div>')}
  const P={dashboard,people:peoplePage,products:productsPage,warehouses:warehousesPage,inventory:inventoryPage,prices:pricesPage,sales:salesPage,transactions:transactionsPage,accounts:accountsPage,packages:packagesPage,statement:statementPage,reports:reportsPage,settings:settingsPage};
  function render(){nav();document.getElementById('main').innerHTML=P[tab]()} 
  function fillEdit(type,id){const a=arr(type==='warehouse'?'warehouses':type==='person'?'people':type==='product'?'products':type==='price'?'prices':type==='account'?'treasuryAccounts':type==='package'?'paymentPackages':'sales'),r=a.find(x=>x.id===id);if(!r)return;window.__edit={type,id};const m={person:'m-person',product:'m-product',warehouse:'m-warehouse',price:'m-price',account:'m-account',package:'m-package'}[type];if(!m)return;open(m);if(type==='person'){valEl('p-name',r.name);valEl('p-company',r.company);valEl('p-phone',r.phone);valEl('p-address',r.address);valEl('p-role',Array.isArray(r.roles)?r.roles[0]:r.role||'customer');valEl('p-active',r.active===false?'0':'1')}if(type==='product'){valEl('p-code',r.code);valEl('p-name',r.name);valEl('p-base',r.baseUnit||'عدد');valEl('p-pack',r.packageUnit||'کارتن');valEl('p-mult',r.unitsPerPackage||36);valEl('p-priceunit',r.pricingUnit||r.baseUnit||'عدد');valEl('p-wh',r.warehouseId||'');valEl('p-active',r.active===false?'0':'1')}if(type==='warehouse'){valEl('w-id',r.id);valEl('w-id',r.id);document.getElementById('w-id').readOnly=true;valEl('w-name',r.name);valEl('w-type',r.type||'سایر');valEl('w-active',r.active===false?'0':'1');valEl('w-note',r.notes)}if(type==='price'){valEl('pr-product',r.productId);valEl('pr-unit',r.unit||r.pricingUnit||'عدد');valEl('pr-price',r.price??r.unitPrice);valEl('pr-date',r.effectiveDate)}if(type==='account'){valEl('a-id',r.id);document.getElementById('a-id').readOnly=true;valEl('a-name',r.name||r.title);valEl('a-type',r.type||'بانک');valEl('a-active',r.active===false?'0':'1')}if(type==='package'){valEl('g-id',r.id);document.getElementById('g-id').readOnly=true;valEl('g-name',r.name);valEl('g-active',r.active===false?'0':'1')}}
  function valEl(id,v){const x=document.getElementById(id);if(x)x.value=v??''}
  function del(type,id){if(!confirm('این مورد حذف/غیرفعال شود؟'))return;const map={person:'people',product:'products',warehouse:'warehouses',price:'prices',account:'treasuryAccounts',package:'paymentPackages',sale:'sales',receipt:'receipts',payment:'payments',inventory:'inventoryMovements'};const a=arr(map[type]||type),i=a.findIndex(x=>x.id===id);if(i<0)return;if(type==='warehouse'&&arr('inventoryMovements').some(x=>x.warehouseId===id))a[i].active=false;else a.splice(i,1);save()}
  function saveForm(kind){const st=S(),ed=window.__edit||{};if(kind==='person'){let r=ed.type==='person'?st.people.find(x=>x.id===ed.id):{id:uid('P')};Object.assign(r,{name:val('p-name'),company:val('p-company'),phone:val('p-phone'),address:val('p-address'),role:val('p-role'),roles:[val('p-role')||'customer'],active:val('p-active')!=='0'});if(!ed.id)st.people.push(r)}
    if(kind==='product'){let r=ed.type==='product'?st.products.find(x=>x.id===ed.id):{id:uid('PRD')};Object.assign(r,{code:val('p-code')||r.id,name:val('p-name'),baseUnit:val('p-base'),packageUnit:val('p-pack'),unitsPerPackage:N(val('p-mult'))||36,pricingUnit:val('p-priceunit'),warehouseId:val('p-wh'),active:val('p-active')!=='0'});if(!ed.id)st.products.push(r)}
    if(kind==='warehouse'){const id=val('w-id')||uid('WH');let r=st.warehouses.find(x=>x.id===id);if(!r){r={id};st.warehouses.push(r)}Object.assign(r,{name:val('w-name'),type:val('w-type'),active:val('w-active')!=='0',notes:val('w-note')})}
    if(kind==='price'){const id=ed.type==='price'?ed.id:uid('PRC');let r=st.prices.find(x=>x.id===id);if(!r){r={id};st.prices.push(r)}Object.assign(r,{productId:val('pr-product'),unit:val('pr-unit'),pricingUnit:val('pr-unit'),price:N(val('pr-price')),unitPrice:N(val('pr-price')),effectiveDate:val('pr-date')})}
    if(kind==='account'){const a=accounts(),id=val('a-id')||uid('AC');let r=a.find(x=>x.id===id);if(!r){r={id};(st.treasuryAccounts||st.accounts).push(r)}Object.assign(r,{name:val('a-name'),type:val('a-type'),active:val('a-active')!=='0'})}
    if(kind==='package'){const id=val('g-id')||uid('PKG');let r=st.paymentPackages.find(x=>x.id===id);if(!r){r={id,tiers:[]};st.paymentPackages.push(r)}Object.assign(r,{name:val('g-name'),active:val('g-active')!=='0'})}
    if(kind==='inventory'){st.inventoryMovements.push({id:uid('IM'),warehouseId:val('i-wh'),productId:val('i-product'),type:val('i-type'),quantity:N(val('i-qty')),qty:N(val('i-qty')),unit:val('i-unit'),jDate:val('i-date'),notes:val('i-note')})}
    if(kind==='sale'){const p=product(val('s-product')),pack=val('s-unit')==='package',unit=pack?(p.packageUnit||'کارتن'):(p.baseUnit||'عدد'),price=priceFor(val('s-product'),unit),qty=N(val('s-qty')),mult=pack?(N(p.unitsPerPackage)||36):1,gross=price*qty*mult,disc=N(val('s-discount'));st.sales.push({id:uid('S'),invoiceNo:val('s-invoice'),customerId:val('s-customer'),productId:val('s-product'),salesUnit:unit,quantity:qty,unitPrice:price,grossAmount:gross,discount:disc,netAmount:gross-disc,amount:gross-disc,jDate:val('s-date'),createdAt:todayISO()})}
    if(kind==='discount'){const a=N(val('d-amount'));st.sales.push({id:uid('SD'),invoiceNo:val('d-invoice'),customerId:val('d-customer'),productId:null,quantity:0,unitPrice:0,grossAmount:-a,discount:a,netAmount:-a,amount:-a,jDate:val('d-date'),isDiscountDocument:true,note:val('d-note'),createdAt:todayISO()})}
    if(kind==='transaction'){const x={id:uid('TX'),type:val('t-kind'),personId:val('t-person'),method:val('t-method'),amount:N(val('t-amount')),jDate:val('t-date'),status:val('t-status'),accountId:val('t-account'),dueDate:val('t-due')};if(x.type==='دریافت'){st.receipts.push({...x,customerId:x.personId,receiptType:x.method});if(x.method==='چک')st.checks.push({id:uid('CH'),customerId:x.personId,amount:x.amount,jDate:x.jDate,dueDate:x.dueDate,status:x.status,accountId:x.accountId,returned:x.status==='برگشتی',originalTransactionId:x.id})}else st.payments.push({...x,payeeId:x.personId})}
    if(kind==='settings'){st.settings.dayBasis=N(val('set-basis'))||30;st.settings.graceDays=N(val('set-grace'));st.settings.currency=val('set-currency')}
    window.__edit=null;DB.save();document.querySelectorAll('.u-modal.open').forEach(x=>x.classList.remove('open'));render()}
  function bind(){document.addEventListener('click',e=>{const z=e.target.closest('[data-tab],[data-u]');if(!z)return;if(z.dataset.tab){tab=z.dataset.tab;sessionStorage.setItem('u-tab',tab);render();return}const a=z.dataset.u;if(a.startsWith('close:'))return close(a.slice(6));if(a.startsWith('new:')){window.__edit=null;const m={person:'m-person',product:'m-product',warehouse:'m-warehouse',inventory:'m-inventory',price:'m-price',sale:'m-sale',transaction:'m-transaction',account:'m-account',package:'m-package'}[a.slice(4)];if(m)open(m);return}if(a.startsWith('edit:'))return fillEdit.apply(null,a.split(':').slice(1));if(a.startsWith('delete:'))return del.apply(null,a.split(':').slice(1));if(a.startsWith('wh-tab:')){sessionStorage.setItem('u-wh',a.slice(7));render();return}if(a.startsWith('tiers:')){open('m-tiers');renderTiers(a.slice(6));return}if(a==='add-tier'){const id=document.getElementById('m-tiers').dataset.pkg,p=arr('paymentPackages').find(x=>x.id===id);p.tiers=p.tiers||[];p.tiers.push({id:uid('T'),maxDays:30,rate:0,active:true});renderTiers(id);return}if(a.startsWith('del-tier:')){const id=document.getElementById('m-tiers').dataset.pkg,p=arr('paymentPackages').find(x=>x.id===id),i=N(a.slice(9));if(p?.tiers?.[i])p.tiers.splice(i,1);renderTiers(id);return}if(a==='save:tiers'){const id=document.getElementById('m-tiers').dataset.pkg,p=arr('paymentPackages').find(x=>x.id===id);p.tiers=(p.tiers||[]).map((t,i)=>({...t,maxDays:N(val('td'+i)),rate:N(val('tr'+i))/100,active:val('ta'+i)==='1'}));DB.save();close('m-tiers');render();return}if(a==='open:m-discount')return open('m-discount');if(a.startsWith('replace:')){window.__replace=a.slice(8);return open('m-replace')}if(a==='save:replacement'){const r=stRec(window.__replace);if(r){r.returned=true;r.status='برگشتی';r.replacedBy={method:val('r-method'),accountId:val('r-account'),amount:N(val('r-amount')),jDate:val('r-date'),reference:val('r-ref')};DB.save();close('m-replace');render()}return}if(a.startsWith('save:'))return saveForm(a.slice(5))});document.addEventListener('change',e=>{if(e.target.matches('.inline-status')){const id=e.target.dataset.id,kind=e.target.dataset.kind,r=(kind==='receipt'?arr('receipts'):arr('payments')).find(x=>x.id===id);if(r){r.status=e.target.value;DB.save();render()}}if(e.target.matches('[data-ret]')){const r=stRec(e.target.dataset.ret);if(r){r.returned=e.target.checked;if(r.returned)r.status='برگشتی';DB.save();render()}}if(['s-product','s-unit','s-qty','s-discount'].includes(e.target.id)){const p=product(val('s-product')),pack=val('s-unit')==='package',unit=pack?(p.packageUnit||'کارتن'):(p.baseUnit||'عدد'),price=priceFor(val('s-product'),unit),qty=N(val('s-qty')),mult=pack?(N(p.unitsPerPackage)||36):1;valEl('s-price',price);const c=document.getElementById('s-calc');if(c)c.textContent='جمع: '+F(price*qty*mult-N(val('s-discount')))}})}
  function stRec(id){return arr('receipts').find(x=>x.id===id)}
  window.render=render;window.UnifiedMainUI={version:'2026.09.14'};document.addEventListener('DOMContentLoaded',()=>{bind();render()});
})();
