"use strict";
(function(){
  var esc=function(x){return String(x==null?'':x).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})};
  var n=function(x){var v=Number(x);return Number.isFinite(v)?v:0};
  var fmt=function(x){return Math.round(n(x)).toLocaleString('en-US')};
  var val=function(id){var e=document.getElementById(id);return e?e.value:''};
  var today=function(){return DB.todayJ?DB.todayJ():''};
  var state=function(){return DB.state};
  var active=function(a){return (a||[]).filter(function(x){return x&&x.active!==false})};
  var people=function(){return state().people||[]};
  var customers=function(){return people().filter(function(x){return (x.roles||[]).indexOf('customer')>=0})};
  var productName=function(id){var p=DB.getProduct(id);return p&&p.name||'—'};
  var personName=function(id){var p=DB.getPerson?DB.getPerson(id):DB.getCustomer(id);return p&&p.name||'—'};
  var options=function(arr,ph){return (ph||'')+active(arr).map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name||x.code||x.id)+'</option>'}).join('')};
  var B=function(text,action,cls){return '<button type="button" class="ac-btn '+(cls||'')+'" data-ac="'+esc(action)+'">'+text+'</button>'};
  var F=function(label,id,type,value,extra){return '<div class="ac-field"><label>'+label+'</label><input id="'+id+'" type="'+(type||'text')+'" value="'+esc(value==null?'':value)+'" '+(extra||'')+'></div>'};
  var S=function(label,id,html){return '<div class="ac-field"><label>'+label+'</label><select id="'+id+'">'+html+'</select></div>'};
  var T=function(rows,headers,map){if(!rows.length)return '<div class="ac-empty">رکوردی ثبت نشده است.</div>';return '<div class="ac-table-wrap"><table class="ac-table"><thead><tr>'+headers.map(function(h){return '<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return '<tr>'+map(r).map(function(c){return '<td>'+(c==null?'—':c)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'};
  var modal=function(id,title,body){return '<div class="ac-modal" id="'+id+'" aria-hidden="true"><div class="ac-modal-card"><div class="ac-modal-head"><h3>'+title+'</h3><button type="button" class="ac-close" data-close="'+id+'">×</button></div><div class="ac-modal-body">'+body+'</div><div class="ac-modal-foot">'+B('انصراف','close:'+id,'ghost')+'</div></div></div>'};
  var open=function(id){var e=document.getElementById(id);if(e){e.classList.add('open');e.setAttribute('aria-hidden','false');setTimeout(function(){var x=e.querySelector('input,select');if(x)x.focus()},20)}};
  var close=function(id){var e=document.getElementById(id);if(e)e.classList.remove('open')};
  var save=function(){DB.save();if(window.App&&App.render)App.render()};
  if(!window.toast)window.toast=function(m,c){var t=document.getElementById('toast');if(t)t.innerHTML='<div class="t '+(c||'')+'">'+esc(m)+'</div>';setTimeout(function(){if(t)t.innerHTML=''},2600)};
  var tabs=[['dashboard','داشبورد'],['people','اشخاص'],['products','کالاها'],['prices','تاریخچه قیمت'],['sales','فروش'],['receipts','دریافت / پرداخت / چک'],['inventory','انبار و موجودی'],['production','تولید'],['purchases','خرید'],['expenses','هزینه و درآمد'],['capital','بسته‌های پرداخت / پله‌ها'],['accounts','حساب‌های بانکی'],['reports','حساب جاری'],['settings','انبارها']];
  var tab=sessionStorage.getItem('ac-tab')||'dashboard';
  function head(title,action){return '<div class="ac-page-head"><h2>'+title+'</h2>'+B('＋ افزودن',action,'primary')+'</div>'}
  function fill(id,v){var e=document.getElementById(id);if(e)e.value=v==null?'':v}
  function rolesHtml(){return [['customer','مشتری'],['supplier','تأمین‌کننده'],['partner','شریک'],['worker','کارگر'],['bank','بانک/مؤسسه'],['other','سایر']].map(function(r){return '<label class="ac-check"><input type="checkbox" name="ac-role" value="'+r[0]+'"><span>'+r[1]+'</span></label>'}).join('')}

  function peoplePage(){var rows=T(people(),['نام','شرکت','تلفن','نقش‌ها','بسته پرداخت','وضعیت','عملیات'],function(p){return [esc(p.name),esc(p.company||'—'),esc(p.phone||'—'),esc((p.roles||[]).join('، ')),esc(p.paymentPackageId||'—'),p.active===false?'غیرفعال':'فعال',B('ویرایش','edit-person:'+p.id,'small')]});return head('اشخاص','new-person')+rows+modal('m-person','شخص جدید / ویرایش','<div class="ac-grid3">'+F('نام *','m-pn')+F('شرکت','m-pc')+F('تلفن','m-pp')+'</div><div class="ac-grid2">'+F('آدرس','m-pa')+S('بسته پرداخت','m-person-pkg','<option value="">بدون بسته</option>'+options(state().paymentPackages))+'</div><label class="ac-label">نقش‌ها</label><div class="ac-checks">'+rolesHtml()+'</div>'+S('وضعیت','m-pactive','<option value="1">فعال</option><option value="0">غیرفعال</option>')+F('یادداشت','m-pnote')+'<div class="ac-modal-save">'+B('ذخیره','save-person','success')+'</div>')}

  function productsPage(){var rows=T(state().products||[],['کد','نام','واحد پایه','واحد بسته','تعداد/بسته','واحد قیمت','انبار','وضعیت','عملیات'],function(p){var w=(state().warehouses||[]).find(function(x){return x.id===p.warehouseId});return [esc(p.code),esc(p.name),esc(p.baseUnit||'عدد'),esc(p.packageUnit||'کارتن'),n(p.unitsPerPackage||36),esc(p.pricingUnit||p.baseUnit||'عدد'),esc(w&&w.name||'—'),p.active===false?'غیرفعال':'فعال',B('ویرایش','edit-product:'+p.id,'small')]});return head('کالاها','new-product')+rows+modal('m-product','کالا جدید / ویرایش','<div class="ac-grid2">'+F('کد','m-pcode')+F('نام *','m-pname')+'</div><div class="ac-grid3">'+F('واحد پایه','m-pbase','text','عدد')+F('واحد بسته','m-ppack','text','کارتن')+F('تعداد پایه در بسته','m-pupp','number','36')+'</div><div class="ac-grid2">'+S('واحد قیمت‌گذاری','m-punit','<option>عدد</option><option>کیلوگرم</option><option>کارتن</option><option>بسته</option>')+S('انبار پیش‌فرض','m-pwh','<option value="">بدون انبار</option>'+options(state().warehouses))+'</div>'+S('وضعیت','m-pactive','<option value="1">فعال</option><option value="0">غیرفعال</option>')+F('یادداشت','m-pnote')+'<div class="ac-modal-save">'+B('ذخیره','save-product','success')+'</div>')}

  function warehousesPage(){var rows=T(state().warehouses||[],['کد','نام','نوع','وضعیت','تعداد حرکت','عملیات'],function(w){return [esc(w.id),esc(w.name),esc(w.type||'سایر'),w.active===false?'غیرفعال':'فعال',n((state().inventoryMovements||[]).filter(function(m){return m.warehouseId===w.id}).length),B('ویرایش','edit-wh:'+w.id,'small')+' '+B('حذف','delete-wh:'+w.id,'small danger')]});return head('انبارها','new-wh')+rows+modal('m-wh','انبار جدید / ویرایش',F('کد انبار *','m-wid')+F('نام انبار *','m-wname')+S('نوع','m-wtype','<option>مواد اولیه</option><option>محصول تولیدی</option><option>بازرگانی</option><option>سایر</option>')+S('وضعیت','m-wactive','<option value="1">فعال</option><option value="0">غیرفعال</option>')+F('توضیحات','m-wnote')+'<div class="ac-modal-save">'+B('ذخیره','save-wh','success')+'</div>')}

  function packagesPage(){var rows=T(state().paymentPackages||[],['بسته','وضعیت','پله‌های فعال','عملیات'],function(p){var tiers=(p.tiers||[]).filter(function(t){return t.active!==false}).sort(function(a,b){return n(a.maxDays)-n(b.maxDays)});return [esc(p.name||p.id),p.active===false?'غیرفعال':'فعال',tiers.map(function(t){return n(t.maxDays)+' روز / '+(n(t.rate)*100).toFixed(2)+'%'}).join(' | ')||'—',B('ویرایش','edit-pkg:'+p.id,'small')+' '+B('پله‌ها','edit-tiers:'+p.id,'small')]});return head('بسته‌های پرداخت / پله‌ها','new-pkg')+rows+modal('m-pkg','بسته پرداخت',F('شناسه بسته *','m-pid')+F('نام بسته *','m-pname')+S('وضعیت بسته','m-pactive','<option value="1">فعال</option><option value="0">غیرفعال</option>')+'<div class="ac-help">پله‌ها از دکمه «پله‌ها» جداگانه مدیریت می‌شوند.</div><div class="ac-modal-save">'+B('ذخیره بسته','save-pkg','success')+' '+B('مدیریت پله‌ها','edit-tiers:__new__','ghost')+'</div>')+modal('m-tiers','مدیریت پله‌های بسته','<div id="m-tier-list"></div><div class="ac-modal-save">'+B('افزودن پله','add-tier','primary')+' '+B('ذخیره پله‌ها','save-tiers','success')+'</div>'))}

  function renderTiers(){var p=state().paymentPackages.find(function(x){return x.id===document.getElementById('m-tiers').dataset.pkg});var list=document.getElementById('m-tier-list');if(!list)return;var tiers=(p&&p.tiers)||[];if(!tiers.length){list.innerHTML='<div class="ac-empty">پله‌ای وجود ندارد. افزودن پله را بزنید.</div>';return}list.innerHTML=tiers.map(function(t,i){return '<div class="ac-tier" data-tier-index="'+i+'"><b>پله '+(i+1)+'</b>'+F('حداکثر روز','tier-d-'+i,'number',t.maxDays)+F('درصد ماهانه','tier-r-'+i,'number',n(t.rate)*100)+S('وضعیت','tier-a-'+i,(t.active===false?'<option value="0" selected>غیرفعال</option><option value="1">فعال</option>':'<option value="1" selected>فعال</option><option value="0">غیرفعال</option>'))+B('حذف پله','delete-tier:'+i,'small danger')+'</div>'}).join('')}

  function pricesPage(){var rows=T(state().prices||[],['کالا','واحد','قیمت','تاریخ اعتبار','عملیات'],function(p){return [esc(productName(p.productId)),esc(p.unit||p.pricingUnit||'عدد'),fmt(p.price||p.unitPrice),esc(p.effectiveDate||'—'),B('ویرایش','edit-price:'+p.id,'small')]});return head('تاریخچه قیمت','new-price')+rows+modal('m-price','قیمت جدید / ویرایش',S('کالا','m-prd',options(state().products,'<option value="">انتخاب کالا</option>'))+'<div class="ac-grid3">'+S('واحد','m-pru','<option>عدد</option><option>کیلوگرم</option><option>کارتن</option><option>بسته</option>')+F('قیمت','m-prc','number','0')+F('تاریخ اعتبار','m-prdte','text',today())+'</div>'+F('یادداشت','m-prnote')+'<div class="ac-modal-save">'+B('ذخیره قیمت','save-price','success')+'</div>')}

  function saleUnitOptions(p){if(!p)return '<option value="">ابتدا کالا</option>';return '<option value="base">'+esc(p.baseUnit||'عدد')+'</option><option value="package">'+esc(p.packageUnit||'کارتن')+'</option>'}
  function unitPrice(p,unit){if(!p)return 0;var rows=(state().prices||[]).filter(function(x){return x.productId===p.id}).slice().sort(function(a,b){return String(b.effectiveDate||'').localeCompare(String(a.effectiveDate||''))});var base=p.baseUnit||'عدد',pack=p.packageUnit||'کارتن',label=unit==='package'?pack:base;var exact=rows.filter(function(x){return (x.unit||x.pricingUnit||'عدد')===label})[0];if(exact)return n(exact.price||exact.unitPrice);if(unit==='package'){var bp=rows.filter(function(x){return (x.unit||x.pricingUnit||'عدد')===base})[0];return n(bp&&(bp.price||bp.unitPrice))*n(p.unitsPerPackage||36)}return 0}
  function salesPage(){var rows=T((state().sales||[]).slice().reverse().filter(function(x){return !x.isDiscountDocument}),['تاریخ','مشتری','کالا','واحد','مقدار','قیمت واحد','ناخالص','تخفیف','نهایی'],function(x){return [esc(x.jDate),esc(personName(x.customerId)),esc(productName(x.productId)),esc(x.salesUnit||x.unit||'—'),n(x.quantity),fmt(x.unitPrice),fmt(x.grossAmount||x.amount),fmt(x.discount||0),fmt(x.netAmount==null?x.amount:x.netAmount)]});return head('فروش و فاکتور','new-sale')+rows+modal('m-sale','ثبت فروش / فاکتور',S('مشتری','m-sc',options(customers(),'<option value="">انتخاب مشتری</option>'))+S('کالا','m-sp',options(state().products,'<option value="">انتخاب کالا</option>'))+'<div class="ac-grid3">'+S('واحد فروش','m-su','<option value="">ابتدا کالا</option>')+F('مقدار','m-sq','number','1')+F('تاریخ','m-sd','text',today())+'</div><div class="ac-grid3">'+F('قیمت واحد','m-sprice','number','0','readonly')+F('مبلغ ناخالص','m-sgross','number','0','readonly')+F('تخفیف همین فاکتور','m-sdisc','number','0')+'</div>'+S('شرایط پرداخت','m-spp','<option value="">از مشتری</option>'+options(state().paymentPackages))+'<div class="ac-total"><span>مبلغ نهایی</span><b id="m-snet">0</b></div><div class="ac-modal-save">'+B('ثبت فروش','save-sale','success')+' '+B('ثبت تخفیف مستقل ۰ محصول','save-discount','warning')+'</div><div class="ac-help">برای تخفیف تجمیعی چند فاکتور، سند مستقل با ۰ محصول ثبت می‌شود و مبلغ آن مستقیماً از حساب مشتری کسر می‌گردد.</div>')}

  function destinationHtml(r){var st=r.status||'نزد ما';if(st==='تودیع‌شده')return options(customers(),'<option value="">محل تودیع</option>');return options(state().treasuryAccounts||[],'<option value="">حساب / خزانه</option>')}
  function receiptRows(){var rows=(state().receipts||[]).slice().reverse().map(function(x){return Object.assign({_kind:'receipt'},x)}).concat((state().payments||[]).slice().reverse().map(function(x){return Object.assign({_kind:'payment'},x)}));rows.sort(function(a,b){return String(b.jDate||'').localeCompare(String(a.jDate||''))});return rows}
  function receiptClass(x){if(x._kind==='payment')return 'ac-row-paid';if(x.returned)return 'ac-legend returned';if(x.status==='وصول شده')return 'ac-row-received';return ''}
  function receiptsPage(){var list=T(receiptRows(),['تاریخ','طرف حساب','جهت','روش','مبلغ','شماره چک','سررسید','وضعیت','حساب/محل','برگشتی','عملیات'],function(x){if(x._kind==='payment')return [esc(x.jDate),esc(personName(x.payeeId)), '<span class="ac-row-paid">پرداخت</span>',esc(x.type||'نقد'),fmt(x.amount),'—','—','پرداخت','<select class="ac-inline-dest" data-payd="'+esc(x.id)+'">'+options(state().treasuryAccounts||[],'<option value="">حساب</option>')+'</select>','—','—'];var st=x.status||'نزد ما';var rowMark=x.returned?' style="background:#fff1f2"':(st==='وصول شده'?' style="background:#f0fdf4"':'');return [esc(x.jDate),esc(personName(x.customerId)), '<span class="ac-row-received">دریافت</span>',esc(x.type||'نقد'),fmt(x.amount),esc(x.checkNo||'—'),esc(x.dueDate||'—'),'<select class="ac-inline-status" data-status="'+esc(x.id)+'">'+['نزد ما','تودیع‌شده','وصول شده','خرج‌شده','باطل'].map(function(s){return '<option '+(st===s?'selected':'')+'>'+s+'</option>'}).join('')+'</select>','<select class="ac-inline-dest" data-dest="'+esc(x.id)+'">'+destinationHtml(x)+'</select>','<input class="ac-inline-return" type="checkbox" data-return="'+esc(x.id)+'" '+(x.returned?'checked':'')+'>',x.type==='چک'&&x.returned?B('جایگزینی','replace:'+x.id,'small'):'—'];});
    return head('دریافت / پرداخت / چک','new-receipt')+'<div class="ac-legend"><span class="received">دریافت / وصول</span><span class="paid">پرداخت</span><span class="returned">برگشتی</span></div>'+list+modal('m-receipt','دریافت / پرداخت / چک',S('جهت تراکنش','m-dir','<option value="receipt">دریافت</option><option value="payment">پرداخت</option>')+S('طرف حساب','m-rc',options(people(),'<option value="">انتخاب طرف حساب</option>'))+'<div class="ac-grid3">'+S('روش','m-rt','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')+F('مبلغ','m-ra','number','0')+F('تاریخ','m-rd','text',today())+'</div><div id="m-check-fields" class="ac-check-fields">'+F('شماره چک','m-rno')+F('بانک صادرکننده','m-rbank')+F('سررسید','m-rdue','text',today())+'</div><div class="ac-modal-save">'+B('ثبت تراکنش','save-receipt','success')+'</div>')+modal('m-replace','جایگزینی چک','<div class="ac-help">چک برگشتی حذف نمی‌شود. هر تعداد جایگزین می‌توان ثبت کرد؛ جایگزین می‌تواند چک جدید یا نقدی باشد و به چک اصلی لینک می‌شود.</div>'+S('نوع جایگزین','m-repltype','<option value="check">چک جدید</option><option value="cash">نقد</option>')+F('مبلغ جایگزین','m-replamount','number','0')+F('شماره چک جدید','m-replno')+F('سررسید چک جدید','m-repldue','text',today())+S('حساب نقدی جایگزین','m-replacct',options(state().treasuryAccounts||[],'<option value="">انتخاب حساب</option>'))+'<div class="ac-modal-save">'+B('ثبت جایگزینی','save-replacement','success')+'</div>');}

  function accountsPage(){var rows=T(state().treasuryAccounts||[],['کد','نام حساب','نوع','وضعیت','عملیات'],function(a){return [esc(a.id),esc(a.name),esc(a.type||'بانک'),a.active===false?'غیرفعال':'فعال',B('ویرایش','edit-account:'+a.id,'small')+' '+B('حذف','delete-account:'+a.id,'small danger')]});return head('حساب‌های بانکی و خزانه','new-account')+rows+modal('m-account','حساب بانکی / خزانه',F('کد *','m-aid')+F('نام حساب *','m-aname')+S('نوع','m-atype','<option>بانک</option><option>صندوق</option><option>کارت</option><option>سایر</option>')+S('وضعیت','m-aactive','<option value="1">فعال</option><option value="0">غیرفعال</option>')+'<div class="ac-modal-save">'+B('ذخیره','save-account','success')+'</div>')}
  function inventoryPage(){var rows=T(state().inventoryMovements||[],['تاریخ','کالا','انبار','نوع حرکت','مقدار پایه','شرح'],function(x){var w=(state().warehouses||[]).find(function(z){return z.id===x.warehouseId});return [esc(x.jDate),esc(productName(x.productId)),esc(w&&w.name||x.warehouseId),esc(x.type||'—'),fmt(x.baseQty),esc(x.note||'—')]});return head('انبار و موجودی','new-inventory')+rows+modal('m-inv','ثبت حرکت انبار',S('کالا','m-invp',options(state().products,'<option value="">انتخاب کالا</option>'))+S('انبار','m-invw',options(state().warehouses,'<option value="">انتخاب انبار</option>'))+S('نوع حرکت','m-invt','<option value="IN">ورود</option><option value="OUT">خروج</option><option value="ADJ">اصلاح موجودی</option>')+'<div class="ac-grid2">'+F('مقدار پایه','m-invq','number','0')+F('تاریخ','m-invd','text',today())+'</div>'+F('شرح','m-invn')+'<div class="ac-modal-save">'+B('ثبت حرکت','save-inventory','success')+'</div>')}
  function simplePage(title,col,label,action){var rows=T(state()[col]||[],['تاریخ','موضوع','مبلغ','وضعیت','عملیات'],function(x){return [esc(x.jDate||x.date||'—'),esc(x.name||x.description||personName(x.customerId||x.supplierId||x.payeeId)),fmt(x.amount),esc(x.status||'ثبت شده'),B('ویرایش',action+':'+x.id,'small')]});return head(title,action)+rows+modal('m-generic',label,F('تاریخ','m-gdate','text',today())+F('شرح','m-gdesc')+F('مبلغ','m-gamount','number','0')+'<div class="ac-modal-save">'+B('ذخیره','save-generic','success')+'</div>')}
  function dashboard(){var sales=(state().sales||[]).reduce(function(s,x){return s+n(x.netAmount==null?x.amount:x.netAmount)},0),rec=(state().receipts||[]).reduce(function(s,x){return s+n(x.amount)},0),checks=(state().receipts||[]).filter(function(x){return x.type==='چک'&&!x.returned&&x.status!=='وصول شده'&&x.status!=='باطل'}).length;return '<div class="kpi"><div class="k"><div>فروش خالص</div><div class="v">'+fmt(sales)+'</div></div><div class="k"><div>دریافت</div><div class="v">'+fmt(rec)+'</div></div><div class="k"><div>چک باز</div><div class="v">'+checks+'</div></div><div class="k"><div>انبارها</div><div class="v">'+(state().warehouses||[]).length+'</div></div></div><div class="bx"><h3>کنترل سریع</h3><div class="actions">'+B('فروش جدید','new-sale','primary')+B('دریافت / چک','new-receipt','success')+B('انبار جدید','new-wh','ghost')+B('بسته پرداخت','new-pkg','ghost')+'</div></div>'}

  function renderPage(){var main=document.getElementById('main');if(!main)return;var html='';switch(tab){case'dashboard':html=dashboard();break;case'people':html=peoplePage();break;case'products':html=productsPage();break;case'prices':html=pricesPage();break;case'sales':html=salesPage();break;case'receipts':html=receiptsPage();break;case'inventory':html=inventoryPage();break;case'production':html=simplePage('تولید','productions','ثبت تولید','new-production');break;case'purchases':html=simplePage('خرید','purchases','ثبت خرید','new-purchase');break;case'expenses':html=simplePage('هزینه و درآمد','expenses','ثبت هزینه','new-expense');break;case'capital':html=packagesPage();break;case'accounts':html=accountsPage();break;case'reports':html='<div class="bx"><h3>حساب جاری</h3><div class="ac-empty">گزارش حساب جاری اینجا متصل می‌شود.</div></div>';break;case'settings':html=warehousesPage();break;default:html=dashboard()}main.innerHTML=html;bindPage()}
  function render(){var nav=document.getElementById('nav');if(nav)nav.innerHTML=tabs.map(function(t){return '<button class="'+(t[0]===tab?'on':'')+'" data-tab="'+t[0]+'">'+t[1]+'</button>'}).join('');renderPage()}

  function editPerson(id){var p=people().find(function(x){return x.id===id});if(!p)return;fill('m-pn',p.name);fill('m-pc',p.company);fill('m-pp',p.phone);fill('m-pa',p.address);fill('m-person-pkg',p.paymentPackageId);fill('m-pactive',p.active===false?'0':'1');fill('m-pnote',p.notes);document.querySelectorAll('[name="ac-role"]').forEach(function(x){x.checked=(p.roles||[]).indexOf(x.value)>=0});document.getElementById('m-person').dataset.edit=id;open('m-person')}
  function savePerson(){var m=document.getElementById('m-person'),id=m.dataset.edit||('P-'+Date.now().toString(36)),p=people().find(function(x){return x.id===id});if(!p){p={id:id};state().people.push(p)}p.name=val('m-pn').trim();if(!p.name)throw Error('نام شخص الزامی است');p.company=val('m-pc').trim();p.phone=val('m-pp').trim();p.address=val('m-pa').trim();p.paymentPackageId=val('m-person-pkg');p.active=val('m-pactive')!=='0';p.notes=val('m-pnote');p.roles=[].slice.call(document.querySelectorAll('[name="ac-role"]:checked')).map(function(x){return x.value});save();close('m-person')}
  function editProduct(id){var p=state().products.find(function(x){return x.id===id});if(!p)return;fill('m-pcode',p.code);fill('m-pname',p.name);fill('m-pbase',p.baseUnit);fill('m-ppack',p.packageUnit);fill('m-pupp',p.unitsPerPackage||36);fill('m-punit',p.pricingUnit);fill('m-pwh',p.warehouseId);fill('m-pactive',p.active===false?'0':'1');fill('m-pnote',p.notes);document.getElementById('m-product').dataset.edit=id;open('m-product')}
  function saveProduct(){var m=document.getElementById('m-product'),id=m.dataset.edit||('P-'+Date.now().toString(36)),p=state().products.find(function(x){return x.id===id});if(!p){p={id:id};state().products.push(p)}p.code=val('m-pcode').trim();p.name=val('m-pname').trim();if(!p.name)throw Error('نام کالا الزامی است');p.baseUnit=val('m-pbase')||'عدد';p.packageUnit=val('m-ppack')||'کارتن';p.unitsPerPackage=n(val('m-pupp'))||36;p.pricingUnit=val('m-punit')||p.baseUnit;p.warehouseId=val('m-pwh');p.active=val('m-pactive')!=='0';p.notes=val('m-pnote');save();close('m-product')}
  function editWarehouse(id){var w=(state().warehouses||[]).find(function(x){return x.id===id});if(!w)return;fill('m-wid',w.id);fill('m-wname',w.name);fill('m-wtype',w.type);fill('m-wactive',w.active===false?'0':'1');fill('m-wnote',w.notes);document.getElementById('m-wh').dataset.edit=id;open('m-wh')}
  function saveWarehouse(){var m=document.getElementById('m-wh'),id=val('m-wid').trim(),name=val('m-wname').trim(),old=m.dataset.edit;if(!id||!name)throw Error('کد و نام انبار الزامی است');var w=(state().warehouses||[]).find(function(x){return x.id===(old||id)});if(!w){if(state().warehouses.some(function(x){return x.id===id}))throw Error('کد انبار تکراری است');w={id:id};state().warehouses.push(w)}Object.assign(w,{id:id,name:name,type:val('m-wtype'),active:val('m-wactive')!=='0',notes:val('m-wnote')});save();close('m-wh')}
  function deleteWarehouse(id){var used=(state().inventoryMovements||[]).some(function(x){return x.warehouseId===id})||(state().products||[]).some(function(x){return x.warehouseId===id});if(used){toast('انبار دارای سابقه است؛ حذف فیزیکی مجاز نیست، آن را غیرفعال کنید.','w');return}state().warehouses=state().warehouses.filter(function(x){return x.id!==id});DB.warehouses=state().warehouses;save()}
  function editPackage(id){var p=state().paymentPackages.find(function(x){return x.id===id});if(!p)return;fill('m-pid',p.id);fill('m-pname',p.name);fill('m-pactive',p.active===false?'0':'1');document.getElementById('m-pkg').dataset.edit=id;open('m-pkg')}
  function savePackage(){var m=document.getElementById('m-pkg'),id=val('m-pid').trim(),name=val('m-pname').trim(),old=m.dataset.edit,p=state().paymentPackages.find(function(x){return x.id===(old||id)});if(!id||!name)throw Error('شناسه و نام بسته الزامی است');if(!p){p={id:id,tiers:[]};state().paymentPackages.push(p)}p.id=id;p.name=name;p.active=val('m-pactive')!=='0';save();close('m-pkg')}
  function openTiers(id){var m=document.getElementById('m-tiers');m.dataset.pkg=id==='__new__'?((state().paymentPackages||[])[0]||{}).id:id;renderTiers();open('m-tiers')}
  function addTier(){var m=document.getElementById('m-tiers'),p=state().paymentPackages.find(function(x){return x.id===m.dataset.pkg});if(!p)throw Error('ابتدا بسته را ذخیره کنید');p.tiers=p.tiers||[];p.tiers.push({id:'T-'+Date.now().toString(36),maxDays:30,rate:0,active:true});renderTiers()}
  function deleteTier(i){var m=document.getElementById('m-tiers'),p=state().paymentPackages.find(function(x){return x.id===m.dataset.pkg});if(!p)return;p.tiers.splice(i,1);renderTiers()}
  function saveTiers(){var m=document.getElementById('m-tiers'),p=state().paymentPackages.find(function(x){return x.id===m.dataset.pkg});if(!p)throw Error('بسته پیدا نشد');var out=[];(p.tiers||[]).forEach(function(t,i){var md=n(val('tier-d-'+i));if(md<=0)return;out.push({id:t.id||('T'+(i+1)),maxDays:md,rate:n(val('tier-r-'+i))/100,active:val('tier-a-'+i)!=='0'})});out.sort(function(a,b){return a.maxDays-b.maxDays});p.tiers=out;save();close('m-tiers')}
  function priceEdit(id){var p=(state().prices||[]).find(function(x){return x.id===id});if(!p)return;fill('m-prd',p.productId);fill('m-pru',p.unit||p.pricingUnit||'عدد');fill('m-prc',p.price||p.unitPrice);fill('m-prdte',p.effectiveDate);fill('m-prnote',p.notes);document.getElementById('m-price').dataset.edit=id;open('m-price')}
  function savePrice(){var m=document.getElementById('m-price'),id=m.dataset.edit,p=(state().prices||[]).find(function(x){return x.id===id});if(!p){p={id:'PR-'+Date.now().toString(36)};state().prices.push(p)}Object.assign(p,{productId:val('m-prd'),unit:val('m-pru'),pricingUnit:val('m-pru'),price:n(val('m-prc')),unitPrice:n(val('m-prc')),effectiveDate:val('m-prdte')||today(),notes:val('m-prnote')});if(!p.productId||p.price<0)throw Error('کالا و قیمت الزامی است');save();close('m-price')}
  function updateSalePreview(){var p=state().products.find(function(x){return x.id===val('m-sp')}),u=val('m-su'),price=unitPrice(p,u),q=n(val('m-sq')),gross=price*q,disc=n(val('m-sdisc'));fill('m-sprice',price);fill('m-sgross',gross);var e=document.getElementById('m-snet');if(e)e.textContent=fmt(Math.max(0,gross-disc))}
  function saveSale(){var p=state().products.find(function(x){return x.id===val('m-sp')}),c=val('m-sc'),u=val('m-su'),q=n(val('m-sq'));if(!p||!c||!u||q<=0)throw Error('مشتری، کالا، واحد و مقدار الزامی است');var price=unitPrice(p,u),gross=price*q*(u==='package'?n(p.unitsPerPackage||36):1),disc=n(val('m-sdisc'));state().sales.push({id:'S-'+Date.now().toString(36),jDate:val('m-sd')||today(),customerId:c,productId:p.id,salesUnit:u==='package'?(p.packageUnit||'کارتن'):(p.baseUnit||'عدد'),quantity:q,unitPrice:price,grossAmount:gross,discount:disc,netAmount:Math.max(0,gross-disc),amount:Math.max(0,gross-disc),paymentPackageId:val('m-spp')||null,status:'POSTED'});save();close('m-sale')}
  function saveDiscount(){var c=val('m-sc'),d=n(val('m-sdisc'));if(!c||d<=0)throw Error('مشتری و مبلغ تخفیف الزامی است');state().sales.push({id:'SD-'+Date.now().toString(36),jDate:val('m-sd')||today(),customerId:c,productId:null,salesUnit:'سند تخفیف',quantity:0,unitPrice:0,grossAmount:0,discount:d,netAmount:-d,amount:-d,isDiscountDocument:true,status:'POSTED'});save();close('m-sale')}
  function saveReceipt(){var dir=val('m-dir'),type=val('m-rt'),amt=n(val('m-ra')),person=val('m-rc');if(!person||amt<=0)throw Error('طرف حساب و مبلغ الزامی است');if(dir==='payment'){state().payments.push({id:'PAY-'+Date.now().toString(36),payeeId:person,type:type,jDate:val('m-rd')||today(),amount:amt,status:'POSTED',accountId:val('m-racct')});save();close('m-receipt');return}var row={id:'R-'+Date.now().toString(36),customerId:person,type:type,jDate:val('m-rd')||today(),amount:amt,status:type==='چک'?'نزد ما':'وصول شده',returned:false,destinationId:val('m-racct')||''};if(type==='چک'){row.checkNo=val('m-rno');row.bank=val('m-rbank');row.dueDate=val('m-rdue');if(!row.checkNo||!row.dueDate)throw Error('شماره چک و سررسید الزامی است')}state().receipts.push(row);save();close('m-receipt')}
  function saveReplacement(){var m=document.getElementById('m-replace'),old=state().receipts.find(function(x){return x.id===m.dataset.original});if(!old||old.type!=='چک'||!old.returned)throw Error('فقط چک برگشتی قابل جایگزینی است');var type=val('m-repltype'),amt=n(val('m-replamount'));if(amt<=0)throw Error('مبلغ جایگزین الزامی است');var r={id:'R-'+Date.now().toString(36),customerId:old.customerId,type:type==='check'?'چک':'نقد',jDate:today(),amount:amt,status:type==='check'?'نزد ما':'وصول شده',returned:false,originalReceiptId:old.id,replacementOfReceiptId:old.id,replacementAccountId:val('m-replacct')||''};if(type==='check'){r.checkNo=val('m-replno');r.dueDate=val('m-repldue')}state().receipts.push(r);old.replacementIds=old.replacementIds||[];old.replacementIds.push(r.id);save();close('m-replace')}
  function editAccount(id){var a=(state().treasuryAccounts||[]).find(function(x){return x.id===id});if(!a)return;fill('m-aid',a.id);fill('m-aname',a.name);fill('m-atype',a.type);fill('m-aactive',a.active===false?'0':'1');document.getElementById('m-account').dataset.edit=id;open('m-account')}
  function saveAccount(){var m=document.getElementById('m-account'),id=val('m-aid').trim(),name=val('m-aname').trim(),old=m.dataset.edit,a=(state().treasuryAccounts||[]).find(function(x){return x.id===(old||id)});if(!id||!name)throw Error('کد و نام حساب الزامی است');if(!a){a={id:id};state().treasuryAccounts.push(a)}Object.assign(a,{id:id,name:name,type:val('m-atype'),active:val('m-aactive')!=='0'});save();close('m-account')}
  function deleteAccount(id){var used=(state().receipts||[]).some(function(x){return x.destinationId===id})||(state().payments||[]).some(function(x){return x.accountId===id});if(used){toast('این حساب سابقه تراکنش دارد؛ غیرفعال کنید.','w');return}state().treasuryAccounts=state().treasuryAccounts.filter(function(x){return x.id!==id});DB.treasuryAccounts=state().treasuryAccounts;save()}
  function saveInventory(){var p=val('m-invp'),w=val('m-invw'),q=n(val('m-invq'));if(!p||!w||q<=0)throw Error('کالا، انبار و مقدار الزامی است');var type=val('m-invt');state().inventoryMovements.push({id:'IM-'+Date.now().toString(36),jDate:val('m-invd')||today(),productId:p,warehouseId:w,type:type,baseQty:type==='OUT'?-q:q,note:val('m-invn')});save();close('m-inv')}
  function genericSave(){var m=document.getElementById('m-generic'),kind=m.dataset.kind||'expense',amount=n(val('m-gamount'));if(amount<=0)throw Error('مبلغ الزامی است');var r={id:'G-'+Date.now().toString(36),jDate:val('m-gdate')||today(),amount:amount,description:val('m-gdesc'),status:'POSTED'};(state()[kind+'s']||state().expenses).push(r);save();close('m-generic')}
  function bindPage(){
    document.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){tab=b.dataset.tab;sessionStorage.setItem('ac-tab',tab);render()}});
    document.querySelectorAll('[data-close]').forEach(function(b){b.onclick=function(){close(b.dataset.close)}});
    document.querySelectorAll('.ac-modal').forEach(function(m){m.onclick=function(e){if(e.target===m)close(m.id)}});
    document.querySelectorAll('[data-ac]').forEach(function(b){b.onclick=function(){var a=b.dataset.ac;try{
      if(a.indexOf('close:')===0)close(a.slice(6));
      else if(a==='new-person'){delete document.getElementById('m-person').dataset.edit;open('m-person')}
      else if(a.indexOf('edit-person:')===0)editPerson(a.split(':')[1]);
      else if(a==='save-person')savePerson();
      else if(a==='new-product'){delete document.getElementById('m-product').dataset.edit;open('m-product')}
      else if(a.indexOf('edit-product:')===0)editProduct(a.split(':')[1]);
      else if(a==='save-product')saveProduct();
      else if(a==='new-wh'){delete document.getElementById('m-wh').dataset.edit;open('m-wh')}
      else if(a.indexOf('edit-wh:')===0)editWarehouse(a.split(':')[1]);
      else if(a.indexOf('delete-wh:')===0)deleteWarehouse(a.split(':')[1]);
      else if(a==='save-wh')saveWarehouse();
      else if(a==='new-pkg'){delete document.getElementById('m-pkg').dataset.edit;open('m-pkg')}
      else if(a.indexOf('edit-pkg:')===0)editPackage(a.split(':')[1]);
      else if(a==='save-pkg')savePackage();
      else if(a.indexOf('edit-tiers:')===0)openTiers(a.split(':')[1]);
      else if(a==='add-tier')addTier();
      else if(a.indexOf('delete-tier:')===0)deleteTier(n(a.split(':')[1]));
      else if(a==='save-tiers')saveTiers();
      else if(a==='new-price'){delete document.getElementById('m-price').dataset.edit;open('m-price')}
      else if(a.indexOf('edit-price:')===0)priceEdit(a.split(':')[1]);
      else if(a==='save-price')savePrice();
      else if(a==='new-sale'){delete document.getElementById('m-sale').dataset.edit;open('m-sale')}
      else if(a==='save-sale')saveSale();
      else if(a==='save-discount')saveDiscount();
      else if(a==='new-receipt')open('m-receipt');
      else if(a==='save-receipt')saveReceipt();
      else if(a.indexOf('replace:')===0){var rm=document.getElementById('m-replace');rm.dataset.original=a.split(':')[1];open('m-replace')}
      else if(a==='save-replacement')saveReplacement();
      else if(a==='new-account'){delete document.getElementById('m-account').dataset.edit;open('m-account')}
      else if(a.indexOf('edit-account:')===0)editAccount(a.split(':')[1]);
      else if(a.indexOf('delete-account:')===0)deleteAccount(a.split(':')[1]);
      else if(a==='save-account')saveAccount();
      else if(a==='new-inventory')open('m-inv');
      else if(a==='save-inventory')saveInventory();
      else if(a==='new-production'){document.getElementById('m-generic').dataset.kind='production';open('m-generic')}
      else if(a==='new-purchase'){document.getElementById('m-generic').dataset.kind='purchase';open('m-generic')}
      else if(a==='new-expense'){document.getElementById('m-generic').dataset.kind='expense';open('m-generic')}
      else if(a==='save-generic')genericSave();
    }catch(err){toast(err.message||String(err),'d')}}};});
    var sp=document.getElementById('m-sp');if(sp)sp.onchange=function(){var p=state().products.find(function(x){return x.id===sp.value}),su=document.getElementById('m-su');if(su)su.innerHTML=saleUnitOptions(p);updateSalePreview()};
    var su=document.getElementById('m-su');if(su)su.onchange=updateSalePreview;var sq=document.getElementById('m-sq');if(sq)sq.oninput=updateSalePreview;var sd=document.getElementById('m-sdisc');if(sd)sd.oninput=updateSalePreview;
    var rt=document.getElementById('m-rt');if(rt)rt.onchange=function(){var f=document.getElementById('m-check-fields');if(f)f.style.display=rt.value==='چک'?'grid':'none';var acct=document.getElementById('m-racct');if(acct)acct.innerHTML=options(state().treasuryAccounts||[],'<option value="">حساب</option>')};
    document.querySelectorAll('[data-status]').forEach(function(e){e.onchange=function(){var r=state().receipts.find(function(x){return x.id===e.dataset.status});if(!r)return;r.status=e.value;save()}});
    document.querySelectorAll('[data-return]').forEach(function(e){e.onchange=function(){var r=state().receipts.find(function(x){return x.id===e.dataset.return});if(r){r.returned=e.checked;save()}}});
    document.querySelectorAll('[data-dest]').forEach(function(e){e.onchange=function(){var r=state().receipts.find(function(x){return x.id===e.dataset.dest});if(r){r.destinationId=e.value;r.destinationType=r.status==='تودیع‌شده'?'customer':'treasury';save()}}});
    document.querySelectorAll('[data-payd]').forEach(function(e){e.onchange=function(){var r=state().payments.find(function(x){return x.id===e.dataset.payd});if(r){r.accountId=e.value;save()}}});
  }
  window.ProjectUI={render:render};window.render=render;
})();
