'use strict';
(function(){
  const E=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const N=v=>{const n=Number(String(v??'').replace(/[,٬\s]/g,''));return Number.isFinite(n)?n:0};
  const F=v=>Math.round(N(v)).toLocaleString('fa-IR');
  const S=()=>DB.state;
  const A=k=>(S()[k]||[]);
  const today=()=>DB.todayJ?DB.todayJ():'';
  const id=p=>(p||'ID-')+Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const active=a=>A(a).filter(x=>x&&x.active!==false);
  const person=i=>A('people').find(x=>x.id===i)||{};
  const product=i=>A('products').find(x=>x.id===i)||{};
  const account=i=>A('treasuryAccounts').find(x=>x.id===i)||A('accounts').find(x=>x.id===i)||{};
  const pkg=i=>A('paymentPackages').find(x=>x.id===i)||{};
  const save=()=>DB.save();
  const val=i=>document.getElementById(i)?.value||'';
  const set=(i,v)=>{const e=document.getElementById(i);if(e)e.value=v??''};
  const opts=(arr,ph='انتخاب کنید',sel='')=>'<option value="">'+ph+'</option>'+arr.map(x=>'<option value="'+E(x.id)+'" '+(String(x.id)===String(sel)?'selected':'')+'>'+E(x.name||x.title||x.code||x.id)+'</option>').join('');
  const btn=(t,a,c='')=>'<button type="button" class="v3-btn '+c+'" data-v3="'+E(a)+'">'+t+'</button>';
  const inp=(l,i,t='text',v='',x='')=>'<label class="v3-field"><span>'+l+'</span><input id="'+i+'" type="'+t+'" value="'+E(v)+'" '+x+'></label>';
  const sel=(l,i,h)=>'<label class="v3-field"><span>'+l+'</span><select id="'+i+'">'+h+'</select></label>';
  const modal=(i,t,b)=>'<div class="v3-modal" id="'+i+'"><div class="v3-modal-card"><div class="v3-modal-head"><h3>'+t+'</h3><button type="button" class="v3-x" data-v3="close:'+i+'">×</button></div><div class="v3-modal-body">'+b+'</div></div></div>';
  const page=(t,a,b)=>'<section class="v3-page"><div class="v3-page-head"><h2>'+t+'</h2>'+(a?btn('＋ افزودن',a,'primary'):'')+'</div>'+b+'</section>';
  const table=(h,r)=>r.length?'<div class="v3-table"><table><thead><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+r.join('')+'</tbody></table></div>':'<div class="v3-empty">رکوردی ثبت نشده است.</div>';
  const actions=(k,i)=>btn('ویرایش','edit:'+k+':'+i,'small')+' '+btn('حذف','delete:'+k+':'+i,'small danger');
  const footer=(m)=>'<div class="v3-foot">'+btn('ذخیره','save:'+m,'success')+btn('انصراف','close:m-'+m)+'</div>';
  const units=['عدد','بسته','کارتن','گرم','کیلوگرم','تن','لیتر','سانتیمتر','متر'];
  const unitOpts=(selv)=>units.map(u=>'<option '+(u===selv?'selected':'')+'>'+u+'</option>').join('');
  const open=i=>document.getElementById(i)?.classList.add('open');
  const close=i=>document.getElementById(i)?.classList.remove('open');
  let tab=sessionStorage.getItem('v3-tab')||'dashboard', editing=null;
  const NAV=[['dashboard','داشبورد','◈'],['people','اشخاص','👥'],['products','کالاها','▦'],['warehouses','انبارها','⌂'],['inventory','موجودی','▤'],['prices','قیمت‌ها','◆'],['sales','فروش','▣'],['transactions','دریافت / پرداخت / چک','↔'],['packages','پله‌های پرداخت','%'],['accounts','حساب‌ها','₿'],['purchases','خرید','↓'],['production','تولید','⚙'],['reports','گزارش‌ها','▥'],['settings','تنظیمات','⚙']];
  function nav(){document.getElementById('nav').innerHTML='<div class="v3-nav">'+NAV.map(x=>'<button class="'+(tab===x[0]?'on':'')+'" data-tab="'+x[0]+'">'+x[2]+' '+x[1]+'</button>').join('')+'</div>'}
  function Dashboard(){const sales=A('sales').filter(x=>!x.isDiscountDocument).reduce((s,x)=>s+N(x.netAmount??x.amount),0),rec=A('receipts').filter(x=>x.status!=='برگشتی'&&x.status!=='باطل').reduce((s,x)=>s+N(x.amount),0),pay=A('payments').reduce((s,x)=>s+N(x.amount),0);return page('داشبورد',null,'<div class="v3-kpis"><div><span>فروش خالص</span><b>'+F(sales)+'</b></div><div><span>دریافت</span><b>'+F(rec)+'</b></div><div><span>پرداخت</span><b>'+F(pay)+'</b></div><div><span>مانده پایه</span><b>'+F(sales-rec)+'</b></div></div><div class="v3-card"><h3>خلاصه</h3><p>'+A('people').length+' شخص · '+A('products').length+' کالا · '+A('warehouses').length+' انبار · '+A('sales').length+' فروش · '+A('checks').length+' چک</p></div>')}
  function People(){const rows=A('people').map(p=>'<tr><td>'+E(p.name)+'</td><td>'+E(p.company||'—')+'</td><td>'+E(p.phone||'—')+'</td><td>'+E((p.roles||[p.role]).filter(Boolean).join('، '))+'</td><td>'+E(pkg(p.paymentPackageId).name||'—')+'</td><td>'+(p.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('person',p.id)+'</td></tr>');const roles=[['customer','مشتری'],['supplier','تأمین‌کننده'],['partner','شریک'],['worker','کارگر'],['other','سایر']];return page('اشخاص','new:person',table(['نام','شرکت','تلفن','نقش','پله پرداخت','وضعیت','عملیات'],rows)+modal('m-person','شخص جدید / ویرایش','<div class="v3-grid3">'+inp('نام *','p-name')+inp('شرکت','p-company')+inp('تلفن','p-phone')+'</div>'+inp('آدرس','p-address')+'<div class="v3-checks">'+roles.map(r=>'<label><input type="checkbox" name="p-role" value="'+r[0]+'">'+r[1]+'</label>').join('')+'</div>'+sel('پله پرداخت','p-package',opts(A('paymentPackages'),'بدون پله'))+sel('وضعیت','p-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+inp('یادداشت','p-note')+footer('person'))}
  function Products(){const rows=A('products').map(p=>'<tr><td>'+E(p.code||p.id)+'</td><td>'+E(p.name)+'</td><td>'+E(p.baseUnit||'عدد')+'</td><td>'+E(p.packageUnit||p.secondUnit||'کارتن')+'</td><td>'+F(p.unitsPerPackage||p.conversionFactor||1)+'</td><td>'+E(p.pricingUnit||p.baseUnit||'عدد')+'</td><td>'+E((A('warehouses').find(w=>w.id===p.warehouseId)||{}).name||'—')+'</td><td>'+(p.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('product',p.id)+'</td></tr>');const wh=active('warehouses');return page('کالاها','new:product',table(['کد','نام','واحد پایه','واحد دوم','ضریب تبدیل','واحد قیمت','انبار پیش‌فرض','وضعیت','عملیات'],rows)+modal('m-product','کالا جدید / ویرایش','<div class="v3-grid2">'+inp('کد کالا','pr-code')+inp('نام *','pr-name')+'</div><div class="v3-grid2">'+sel('واحد پایه','pr-base',unitOpts('عدد'))+sel('واحد دوم','pr-second',unitOpts('کارتن'))+'</div>'+inp('تعداد واحد پایه در واحد دوم','pr-factor','number','36')+sel('واحد قیمت‌گذاری','pr-priceunit',unitOpts('عدد'))+sel('انبار پیش‌فرض','pr-wh',opts(wh,'بدون انبار'))+sel('وضعیت','pr-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+inp('یادداشت','pr-note')+footer('product'))}
  function Warehouses(){const rows=A('warehouses').map(w=>'<tr><td>'+E(w.id)+'</td><td>'+E(w.name)+'</td><td>'+E(w.type||'سایر')+'</td><td>'+(w.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('warehouse',w.id)+'</td></tr>');return page('انبارها','new:warehouse',table(['کد','نام','نوع','وضعیت','عملیات'],rows)+modal('m-warehouse','انبار جدید / ویرایش',inp('کد انبار *','w-id')+inp('نام انبار *','w-name')+sel('نوع انبار','w-type','<option>مواد اولیه</option><option>محصول تولیدی</option><option>بازرگانی</option><option>سایر</option>')+sel('وضعیت','w-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+inp('توضیحات','w-note')+footer('warehouse'))}
  function Inventory(){const ws=A('warehouses'),cur=sessionStorage.getItem('v3-wh')||ws.find(w=>w.active!==false)?.id||'',rows=A('inventoryMovements').filter(m=>m.warehouseId===cur).map(m=>'<tr><td>'+E(m.jDate||m.date||'—')+'</td><td>'+E(product(m.productId).name||'—')+'</td><td>'+E(m.type||'—')+'</td><td>'+F(m.quantity??m.qty)+'</td><td>'+E(m.unit||'عدد')+'</td><td>'+actions('inventory',m.id)+'</td></tr>');return page('موجودی انبار','new:inventory','<div class="v3-tabs">'+ws.map(w=>'<button class="'+(w.id===cur?'on':'')+'" data-v3="wh-tab:'+w.id+'">'+E(w.name)+'</button>').join('')+'</div>'+table(['تاریخ','کالا','نوع حرکت','مقدار','واحد','عملیات'],rows)+modal('m-inventory','ثبت / اصلاح موجودی',sel('انبار','i-wh',opts(ws,'انتخاب انبار',cur))+sel('کالا','i-product',opts(A('products'),'انتخاب کالا'))+sel('نوع حرکت','i-type','<option>ورود</option><option>خروج</option><option>موجودی اولیه بدون بار مالی</option><option>اصلاح دستی</option><option>انتقال</option>')+inp('مقدار','i-qty','number','0')+sel('واحد','i-unit',unitOpts('عدد'))+inp('تاریخ','i-date','text',today())+inp('توضیحات','i-note')+footer('inventory'))}
  function Prices(){const rows=A('prices').slice().sort((a,b)=>String(b.effectiveDate||'').localeCompare(String(a.effectiveDate||''))).map(p=>'<tr><td>'+E(product(p.productId).name||'—')+'</td><td>'+E(p.unit||p.pricingUnit||'عدد')+'</td><td>'+F(p.price??p.unitPrice)+'</td><td>'+E(p.effectiveDate||'—')+'</td><td>'+actions('price',p.id)+'</td></tr>');return page('تاریخچه قیمت','new:price',table(['کالا','واحد','قیمت','تاریخ اعتبار','عملیات'],rows)+modal('m-price','قیمت جدید / ویرایش',sel('کالا','price-product',opts(A('products'),'انتخاب کالا'))+sel('واحد قیمت','price-unit',unitOpts('عدد'))+inp('قیمت','price-value','number','0')+inp('تاریخ اعتبار','price-date','text',today())+inp('یادداشت','price-note')+footer('price'))}
  function price(productId,unit){const p=product(productId),u=unit==='second'?(p.packageUnit||p.secondUnit||'کارتن'):(p.baseUnit||'عدد'),r=A('prices').filter(x=>x.productId===productId&&(x.unit||x.pricingUnit||'عدد')===u&&String(x.effectiveDate||'')<=String(today())).sort((a,b)=>String(b.effectiveDate||'').localeCompare(String(a.effectiveDate||'')));if(r[0])return N(r[0].price??r[0].unitPrice);const base=(p.baseUnit||'عدد')===u?1:N(p.unitsPerPackage||p.conversionFactor||1);const b=A('prices').filter(x=>x.productId===productId&&(x.unit||x.pricingUnit||'')===p.baseUnit).sort((a,c)=>String(c.effectiveDate||'').localeCompare(String(a.effectiveDate||'')))[0];return b?N(b.price??b.unitPrice)*base:0}
  function Sales(){const rows=A('sales').slice().reverse().map(s=>'<tr><td>'+E(s.invoiceNo||'—')+'</td><td>'+E(s.jDate||'')+'</td><td>'+E(person(s.customerId).name||'—')+'</td><td>'+E(product(s.productId).name||'تخفیف مستقل')+'</td><td>'+E(s.salesUnit==='second'?(product(s.productId).packageUnit||'واحد دوم'):(product(s.productId).baseUnit||s.unit||'عدد'))+'</td><td>'+F(s.quantity)+'</td><td>'+F(s.unitPrice)+'</td><td>'+F(s.grossAmount??s.amount)+'</td><td>'+F(s.discount||0)+'</td><td>'+F(s.netAmount??s.amount)+'</td><td>'+actions('sale',s.id)+'</td></tr>');return page('فروش و فاکتور','new:sale',table(['فاکتور','تاریخ','مشتری','کالا','واحد','مقدار','قیمت واحد','ناخالص','تخفیف','نهایی','عملیات'],rows)+modal('m-sale','ثبت / ویرایش فروش',sel('مشتری','s-customer',opts(active('people').filter(p=>(p.roles||[p.role]).includes('customer')),'انتخاب مشتری'))+sel('کالا','s-product',opts(A('products'),'انتخاب کالا'))+sel('واحد فروش','s-unit','<option value="base">واحد پایه</option><option value="second">واحد دوم</option>')+inp('مقدار','s-qty','number','1')+inp('قیمت واحد منتخب','s-price','number','0','readonly')+inp('تخفیف همین فاکتور','s-discount','number','0')+'<div id="s-calc" class="v3-total">جمع نهایی: ۰</div>'+inp('شماره فاکتور','s-invoice')+inp('تاریخ','s-date','text',today())+footer('sale'))+modal('m-discount','تخفیف مستقل','تخفیف مستقل به‌عنوان یک سند بدون کالا ثبت می‌شود و در گزارش فروش به‌صورت کاهنده فروش نمایش داده می‌شود.'+sel('مشتری','d-customer',opts(active('people').filter(p=>(p.roles||[p.role]).includes('customer')),'انتخاب مشتری'))+inp('مبلغ تخفیف','d-amount','number','0')+inp('شماره مرجع','d-invoice')+inp('تاریخ','d-date','text',today())+footer('discount'))}
  function Transactions(){const rows=A('receipts').concat(A('payments').map(x=>Object.assign({type:'پرداخت'},x))).slice().reverse().map(x=>'<tr class="'+(x.type==='پرداخت'?'v3-pay':x.status==='برگشتی'?'v3-return':x.status==='وصول شده'?'v3-collected':'v3-receive')+'"><td>'+E(x.type||'دریافت')+'</td><td>'+E(person(x.customerId||x.personId).name||'—')+'</td><td>'+E(x.method||x.receiptType||'نقد')+'</td><td>'+F(x.amount)+'</td><td>'+E(x.status||'—')+'</td><td>'+E(account(x.accountId).name||'—')+'</td><td>'+((x.type!=='پرداخت'&&x.id)?selInlineStatus(x):'')+'</td><td>'+actions(x.type==='پرداخت'?'payment':'receipt',x.id)+'</td></tr>');return page('دریافت / پرداخت / چک','new:transaction', '<div class="v3-legend"><span class="receive">دریافت</span><span class="pay">پرداخت</span><span class="collected">وصول شده</span><span class="returned">برگشتی</span></div>'+table(['نوع','طرف حساب','روش','مبلغ','وضعیت','حساب','تغییر سریع وضعیت','عملیات'],rows)+modal('m-transaction','ثبت دریافت / پرداخت / چک',sel('نوع تراکنش','t-kind','<option value="receipt">دریافت</option><option value="payment">پرداخت</option><option value="check">چک دریافتی</option>')+sel('طرف حساب','t-person',opts(active('people'),'انتخاب شخص'))+sel('روش','t-method','<option>نقد</option><option>کارت</option><option>حواله</option><option>چک</option>')+inp('مبلغ','t-amount','number','0')+inp('تاریخ','t-date','text',today())+sel('حساب','t-account',opts(active('treasuryAccounts'),'انتخاب حساب'))+sel('وضعیت','t-status','<option>وصول شده</option><option>نزد ما</option><option>تودیع شده</option><option>برگشتی</option><option>باطل</option>')+inp('شماره چک / رسید','t-no')+inp('تاریخ سررسید','t-due','text','')+'<label class="v3-check"><input id="t-returned" type="checkbox"> برگشتی</label><div class="v3-note">وضعیت برگشتی مستقل است؛ در صورت تیک برگشتی، ردیف چک قرمز می‌شود. حساب وصول‌شده از فهرست حساب‌های مالی انتخاب می‌شود و برای تودیع می‌توان طرف حساب مقصد را تعیین کرد.</div>'+footer('transaction'))}
  function selInlineStatus(x){const id='st-'+x.id;return '<select class="v3-inline-status" data-status-id="'+E(x.id)+'"><option '+(x.status==='نزد ما'?'selected':'')+'>نزد ما</option><option '+(x.status==='وصول شده'?'selected':'')+'>وصول شده</option><option '+(x.status==='تودیع شده'?'selected':'')+'>تودیع شده</option><option '+(x.status==='برگشتی'?'selected':'')+'>برگشتی</option><option '+(x.status==='باطل'?'selected':'')+'>باطل</option></select>'}
  function Packages(){const rows=A('paymentPackages').map(p=>'<tr><td>'+E(p.name)+'</td><td>'+E(p.id)+'</td><td>'+E((p.tiers||[]).filter(t=>t.active!==false).map(t=>t.maxDays+' روز / '+(N(t.rate)*100)+'٪').join(' | '))+'</td><td>'+(p.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('package',p.id)+'</td></tr>');return page('پله‌های پرداخت','new:package',table(['نام پله','کد','سطوح','وضعیت','عملیات'],rows)+modal('m-package','پله پرداخت جدید / ویرایش',inp('نام پله *','pk-name')+inp('حداکثر روز پله ۱','pk-d1','number','30')+inp('نرخ پله ۱ (مثلاً 0.06)','pk-r1','number','0')+inp('حداکثر روز پله ۲','pk-d2','number','60')+inp('نرخ پله ۲','pk-r2','number','0.06')+inp('حداکثر روز پله ۳','pk-d3','number','120')+inp('نرخ پله ۳','pk-r3','number','0.10')+inp('حداکثر روز پله ۴','pk-d4','number','9999')+inp('نرخ پله ۴','pk-r4','number','0.15')+sel('وضعیت','pk-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+footer('package'))}
  function Accounts(){const rows=A('treasuryAccounts').map(a=>'<tr><td>'+E(a.name)+'</td><td>'+E(a.type||'حساب')+'</td><td>'+(a.active===false?'غیرفعال':'فعال')+'</td><td>'+actions('account',a.id)+'</td></tr>');return page('حساب‌های مالی','new:account',table(['نام حساب','نوع','وضعیت','عملیات'],rows)+modal('m-account','حساب مالی جدید / ویرایش',inp('نام حساب *','a-name')+sel('نوع','a-type','<option>بانک</option><option>صندوق</option><option>کارتخوان</option><option>سایر</option>')+inp('شماره / توضیح','a-note')+sel('وضعیت','a-active','<option value="1">فعال</option><option value="0">غیرفعال</option>')+footer('account'))}
  function Simple(kind,title,key){const rows=A(key).map(x=>'<tr><td>'+E(x.name||x.code||x.id)+'</td><td>'+E(x.jDate||x.date||'—')+'</td><td>'+E(x.status||'—')+'</td><td>'+actions(kind,x.id)+'</td></tr>');return page(title,'new:'+kind,table(['عنوان','تاریخ','وضعیت','عملیات'],rows)+modal('m-'+kind,title+' جدید / ویرایش',inp('عنوان','x-name')+inp('تاریخ','x-date','text',today())+inp('یادداشت','x-note')+footer(kind)))}
  function render(){nav();let b=tab==='dashboard'?Dashboard():tab==='people'?People():tab==='products'?Products():tab==='warehouses'?Warehouses():tab==='inventory'?Inventory():tab==='prices'?Prices():tab==='sales'?Sales():tab==='transactions'?Transactions():tab==='packages'?Packages():tab==='accounts'?Accounts():tab==='purchases'?Simple('purchase','خرید','purchases'):tab==='production'?Simple('production','تولید','productions'):tab==='reports'?Simple('report','گزارش‌ها','reports'):Simple('setting','تنظیمات','settings');document.getElementById('main').innerHTML=b;bind()}
  function editForm(k,i){editing={k,i};const x=A(k==='warehouse'?'warehouses':k==='person'?'people':k==='product'?'products':k==='price'?'prices':k==='sale'?'sales':k==='receipt'?'receipts':k==='payment'?'payments':k==='package'?'paymentPackages':k==='account'?'treasuryAccounts':k==='inventory'?'inventoryMovements':k+'s'} .find(r=>r.id===i);if(!x)return;open('m-'+(k==='warehouse'?'warehouse':k));setTimeout(()=>{
    const m={person:{name:x.name,company:x.company,phone:x.phone,address:x.address,package:x.paymentPackageId,active:x.active===false?'0':'1'},product:{code:x.code,name:x.name,base:x.baseUnit||'عدد',second:x.packageUnit||x.secondUnit||'کارتن',factor:x.unitsPerPackage||x.conversionFactor||36,priceunit:x.pricingUnit||x.baseUnit||'عدد',wh:x.warehouseId,active:x.active===false?'0':'1'},warehouse:{id:x.id,name:x.name,type:x.type||'سایر',active:x.active===false?'0':'1',note:x.notes},price:{product:x.productId,unit:x.unit||x.pricingUnit||'عدد',value:x.price??x.unitPrice,date:x.effectiveDate,note:x.note},sale:{customer:x.customerId,product:x.productId,unit:x.salesUnit||'base',qty:x.quantity,price:x.unitPrice,discount:x.discount,invoice:x.invoiceNo,date:x.jDate},package:{name:x.name,d1:x.tiers?.[0]?.maxDays||30,r1:x.tiers?.[0]?.rate||0,d2:x.tiers?.[1]?.maxDays||60,r2:x.tiers?.[1]?.rate||.06,d3:x.tiers?.[2]?.maxDays||120,r3:x.tiers?.[2]?.rate||.1,d4:x.tiers?.[3]?.maxDays||9999,r4:x.tiers?.[3]?.rate||.15,active:x.active===false?'0':'1'},account:{name:x.name,type:x.type||'بانک',note:x.note,active:x.active===false?'0':'1'},inventory:{wh:x.warehouseId,product:x.productId,type:x.type,qty:x.quantity??x.qty,unit:x.unit||'عدد',date:x.jDate||x.date,note:x.note}}[k];if(!m)return;Object.keys(m).forEach(q=>set(({person:{name:'p-name',company:'p-company',phone:'p-phone',address:'p-address',package:'p-package',active:'p-active'},product:{code:'pr-code',name:'pr-name',base:'pr-base',second:'pr-second',factor:'pr-factor',priceunit:'pr-priceunit',wh:'pr-wh',active:'pr-active'},warehouse:{id:'w-id',name:'w-name',type:'w-type',active:'w-active',note:'w-note'},price:{product:'price-product',unit:'price-unit',value:'price-value',date:'price-date',note:'price-note'},sale:{customer:'s-customer',product:'s-product',unit:'s-unit',qty:'s-qty',price:'s-price',discount:'s-discount',invoice:'s-invoice',date:'s-date'},package:{name:'pk-name',d1:'pk-d1',r1:'pk-r1',d2:'pk-d2',r2:'pk-r2',d3:'pk-d3',r3:'pk-r3',d4:'pk-d4',r4:'pk-r4',active:'pk-active'},account:{name:'a-name',type:'a-type',note:'a-note',active:'a-active'},inventory:{wh:'i-wh',product:'i-product',type:'i-type',qty:'i-qty',unit:'i-unit',date:'i-date',note:'i-note'}}[k]||{})[q],m[q]));
  },20)}
  function saveForm(k){let target=k==='warehouse'?'warehouses':k==='person'?'people':k==='product'?'products':k==='price'?'prices':k==='sale'?'sales':k==='package'?'paymentPackages':k==='account'?'treasuryAccounts':k==='inventory'?'inventoryMovements':k+'s', x=editing?A(target).find(r=>r.id===editing.i):null; x=x||{id:id(k.toUpperCase()+'-')};
    if(k==='person'){x.name=val('p-name').trim();if(!x.name)return alert('نام شخص الزامی است');x.company=val('p-company');x.phone=val('p-phone');x.address=val('p-address');x.roles=[...document.querySelectorAll('input[name="p-role"]:checked')].map(e=>e.value);x.paymentPackageId=val('p-package');x.active=val('p-active')!=='0';x.note=val('p-note')}
    if(k==='product'){x.code=val('pr-code');x.name=val('pr-name').trim();if(!x.name)return alert('نام کالا الزامی است');x.baseUnit=val('pr-base');x.packageUnit=val('pr-second');x.secondUnit=x.packageUnit;x.unitsPerPackage=N(val('pr-factor'))||1;x.conversionFactor=x.unitsPerPackage;x.pricingUnit=val('pr-priceunit');x.warehouseId=val('pr-wh');x.active=val('pr-active')!=='0';x.note=val('pr-note')}
    if(k==='warehouse'){x.id=val('w-id').trim()||x.id;if(!x.id||!val('w-name').trim())return alert('کد و نام انبار الزامی است');x.name=val('w-name').trim();x.type=val('w-type');x.active=val('w-active')!=='0';x.notes=val('w-note')}
    if(k==='price'){x.productId=val('price-product');x.unit=val('price-unit');x.pricingUnit=x.unit;x.price=N(val('price-value'));x.effectiveDate=val('price-date');x.note=val('price-note')}
    if(k==='sale'){const p=product(val('s-product')),u=val('s-unit'),q=N(val('s-qty')),up=price(val('s-product'),u),gross=q*up,d=Math.min(Math.max(0,N(val('s-discount'))),gross);x.customerId=val('s-customer');x.productId=val('s-product');x.salesUnit=u;x.quantity=q;x.unitPrice=up;x.grossAmount=gross;x.discount=d;x.netAmount=gross-d;x.invoiceNo=val('s-invoice');x.jDate=val('s-date');x.amount=x.netAmount;x.isDiscountDocument=false;x.productName=p.name}
    if(k==='package'){x.name=val('pk-name').trim();if(!x.name)return alert('نام پله الزامی است');x.tiers=[1,2,3,4].map(n=>({id:'t'+n,maxDays:N(val('pk-d'+n))||9999,rate:N(val('pk-r'+n)),active:true}));x.active=val('pk-active')!=='0'}
    if(k==='account'){x.name=val('a-name').trim();if(!x.name)return alert('نام حساب الزامی است');x.type=val('a-type');x.note=val('a-note');x.active=val('a-active')!=='0'}
    if(k==='inventory'){x.warehouseId=val('i-wh');x.productId=val('i-product');x.type=val('i-type');x.quantity=N(val('i-qty'));x.qty=x.quantity;x.unit=val('i-unit');x.jDate=val('i-date');x.note=val('i-note')}
    if(!editing)A(target).push(x);save();editing=null;close('m-'+(k==='warehouse'?'warehouse':k));render()}
  function newForm(k){editing=null;open('m-'+(k==='warehouse'?'warehouse':k));if(k==='sale'){set('s-date',today());set('s-qty',1);set('s-price',0);set('s-discount',0)}if(k==='inventory')set('i-date',today());if(k==='price')set('price-date',today());if(k==='package'){set('pk-d1',30);set('pk-r1',0);set('pk-d2',60);set('pk-r2',.06);set('pk-d3',120);set('pk-r3',.1);set('pk-d4',9999);set('pk-r4',.15)}}
  function del(k,i){const map={warehouse:'warehouses',person:'people',product:'products',price:'prices',sale:'sales',receipt:'receipts',payment:'payments',package:'paymentPackages',account:'treasuryAccounts',inventory:'inventoryMovements'};const a=A(map[k]);const x=a.find(r=>r.id===i);if(!x)return;if(k==='warehouse'&&A('inventoryMovements').some(m=>m.warehouseId===i))return alert('انبار دارای سابقه حرکت است؛ حذف مستقیم مجاز نیست. آن را غیرفعال کنید.');if(confirm('این رکورد حذف شود؟')){a.splice(a.indexOf(x),1);save();render()}}
  function transactionSave(){const kind=val('t-kind'),p=val('t-person'),amt=N(val('t-amount')),date=val('t-date')||today();if(!p||!amt)return alert('طرف حساب و مبلغ الزامی است');if(kind==='payment'){A('payments').push({id:id('PAY-'),personId:p,customerId:p,amount:amt,jDate:date,date,method:val('t-method'),accountId:val('t-account'),status:'ثبت شده'});save();close('m-transaction');render();return}if(kind==='check'){const r={id:id('CHK-'),customerId:p,personId:p,amount:amt,receiptType:'چک',method:'چک',status:val('t-returned')==='on'?'برگشتی':val('t-status'),accountId:val('t-account'),checkNo:val('t-no'),dueDate:val('t-due'),jDate:date,returned:document.getElementById('t-returned')?.checked||false};A('checks').push(r);A('receipts').push(Object.assign({},r,{id:id('REC-'),checkId:r.id}));save();close('m-transaction');render();return}A('receipts').push({id:id('REC-'),customerId:p,personId:p,amount:amt,method:val('t-method'),accountId:val('t-account'),status:document.getElementById('t-returned')?.checked?'برگشتی':val('t-status'),jDate:date});save();close('m-transaction');render()}
  function bind(){document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>{tab=e.dataset.tab;sessionStorage.setItem('v3-tab',tab);render()});document.querySelectorAll('[data-v3]').forEach(e=>e.onclick=()=>{const a=e.dataset.v3;if(a.startsWith('close:'))close(a.slice(6));else if(a.startsWith('new:'))newForm(a.slice(4));else if(a.startsWith('edit:')){const p=a.split(':');editForm(p[1],p.slice(2).join(':'))}else if(a.startsWith('delete:')){const p=a.split(':');del(p[1],p.slice(2).join(':'))}else if(a.startsWith('save:')){const k=a.slice(5);if(k==='transaction')transactionSave();else if(k==='discount'){const c=val('d-customer'),amt=N(val('d-amount'));if(c&&amt){A('sales').push({id:id('DISC-'),customerId:c,amount:-Math.abs(amt),netAmount:-Math.abs(amt),grossAmount:0,discount:Math.abs(amt),isDiscountDocument:true,invoiceNo:val('d-invoice'),jDate:val('d-date')||today()});save();close('m-discount');render()}}else saveForm(k)}else if(a.startsWith('wh-tab:')){sessionStorage.setItem('v3-wh',a.slice(7));render()}});document.querySelectorAll('.v3-inline-status').forEach(e=>e.onchange=()=>{const r=A('receipts').find(x=>x.id===e.dataset.statusId);if(r){r.status=e.value;r.returned=e.value==='برگشتی';save();render()}});document.getElementById('s-product')?.addEventListener('change',updateSale);document.getElementById('s-unit')?.addEventListener('change',updateSale);document.getElementById('s-qty')?.addEventListener('input',updateSale);document.getElementById('s-discount')?.addEventListener('input',updateSale)}
  function updateSale(){const p=val('s-product'),u=val('s-unit'),q=N(val('s-qty')),up=price(p,u),gross=q*up,d=Math.min(Math.max(0,N(val('s-discount'))),gross);set('s-price',up);const c=document.getElementById('s-calc');if(c)c.textContent='جمع نهایی: '+F(gross-d)}
  window.render=render;
})();