'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {ContractEngine,SENSITIVE_OPERATION_TYPES,STATUS}=require('../phase05.js');

test('all sensitive operation types are accepted',()=>{const e=new ContractEngine();for(const type of SENSITIVE_OPERATION_TYPES){const r=e.execute({operationType:type,idempotencyKey:'K-'+type,payload:{x:1},effects:[{effectType:'TEST',amount:1}]});assert.equal(r.operation.Status,STATUS.POSTED)}});
test('unknown operation type is rejected without creating operation',()=>{const e=new ContractEngine();assert.throws(()=>e.execute({operationType:'UNKNOWN',idempotencyKey:'K1',payload:{x:1}}),/INVALID_OPERATION_TYPE/);assert.equal(e.operations.size,0)});
test('same idempotency key and same payload replays',()=>{const e=new ContractEngine();const a=e.execute({operationType:'RECEIPT',idempotencyKey:'K1',payload:{amount:100},effects:[{amount:100}]});const b=e.execute({operationType:'RECEIPT',idempotencyKey:'K1',payload:{amount:100},effects:[{amount:999}]});assert.equal(b.replayed,true);assert.equal(b.operation.OperationID,a.operation.OperationID);assert.equal(e.operations.size,1)});
test('same idempotency key with different payload conflicts',()=>{const e=new ContractEngine();e.execute({operationType:'RECEIPT',idempotencyKey:'K1',payload:{amount:100}});assert.throws(()=>e.execute({operationType:'RECEIPT',idempotencyKey:'K1',payload:{amount:101}}),/IDEMPOTENCY_CONFLICT/)});
test('multiple effects belong to one operation',()=>{const e=new ContractEngine();const r=e.execute({operationType:'SALE',idempotencyKey:'K1',payload:{sale:'S1'},effects:[{effectType:'AR',amount:100},{effectType:'INVENTORY',quantity:-2}]});assert.equal(r.effects.length,2);assert.ok(r.effects.every(x=>x.OperationID===r.operation.OperationID))});
test('reversal creates a new operation and reverses every effect',()=>{const e=new ContractEngine();const r=e.execute({operationType:'SALE',idempotencyKey:'K1',payload:{sale:'S1'},effects:[{effectType:'AR',amount:100},{effectType:'INVENTORY',quantity:-2}]});const rev=e.reverse(r.operation.OperationID,{idempotencyKey:'REV-K1'});assert.equal(rev.effects.length,2);assert.equal(e.operations.get(r.operation.OperationID).Status,STATUS.REVERSED);assert.deepEqual(rev.effects.map(x=>x.ReversesEffectID),r.effects.map(x=>x.EffectID));assert.equal(rev.effects[0].Amount,-100);assert.equal(rev.effects[1].Quantity,2)});
test('reversal cannot be applied twice',()=>{const e=new ContractEngine();const r=e.execute({operationType:'SALE',idempotencyKey:'K1',payload:{sale:'S1'}});e.reverse(r.operation.OperationID);assert.throws(()=>e.reverse(r.operation.OperationID),/ALREADY_REVERSED/)});
test('receipt allocation is immutable and versioned on reversal',()=>{const e=new ContractEngine();e.addSale({id:'S1',customerId:'C1',jDate:'1405/06/01',amount:100});e.addSale({id:'S2',customerId:'C1',jDate:'1405/06/05',amount:200});e.addReceipt({id:'R1',customerId:'C1',jDate:'1405/06/10',amount:150,status:'وصول شده'});const rows=e.allocateReceipt('R1','1405/06/10');assert.equal(rows.length,2);assert.equal(rows[0].PrincipalReduction,100);assert.equal(rows[1].PrincipalReduction,50);const rev=e.reverseAllocation(rows[0].AllocationID);assert.equal(rows[0].PrincipalReduction,100);assert.equal(rev.PrincipalReduction,-100);assert.equal(rev.Version,2);assert.equal(rev.ReversesAllocationID,rows[0].AllocationID)});
test('returned receipt creates no allocation',()=>{const e=new ContractEngine();e.addSale({id:'S1',customerId:'C1',jDate:'1405/06/01',amount:100});e.addReceipt({id:'R1',customerId:'C1',jDate:'1405/06/10',amount:100,status:'برگشتی'});assert.deepEqual(e.allocateReceipt('R1','1405/06/10'),[])});
test('FIFO is deterministic for same date using id',()=>{const e=new ContractEngine();e.addSale({id:'S2',customerId:'C1',jDate:'1405/06/01',amount:100});e.addSale({id:'S1',customerId:'C1',jDate:'1405/06/01',amount:100});e.addReceipt({id:'R1',customerId:'C1',jDate:'1405/06/02',amount:50,status:'وصول شده'});const rows=e.allocateReceipt('R1','1405/06/02');assert.equal(rows[0].SaleID,'S1')});
test('reconciliation invariant holds after receipt then reversal',()=>{const e=new ContractEngine();const initial=e.reconcile(300,150);assert.equal(initial.totalOutstanding,150);const after=e.reconcile(300,0);assert.equal(after.totalOutstanding,300)});
test('schema registry blocks unknown fields',()=>{const e=new ContractEngine();e.registerSchema({tableName:'Operations',primaryKey:'OperationID',columns:[{name:'OperationID',required:true},{name:'Status',required:true}]});assert.throws(()=>e.validateSchema('Operations',[{OperationID:'OP-1',Status:'POSTED',Extra:1}]),/SCHEMA_INVALID/);assert.equal(e.validateSchema('Operations',[{OperationID:'OP-1',Status:'POSTED'}]),true)});
test('operation identity is required',()=>{const e=new ContractEngine();assert.throws(()=>e.execute({operationType:'SALE',payload:{x:1}}),/INVALID_OPERATION/)});
test('failure after effect preparation marks operation NEEDS_REPAIR',()=>{const e=new ContractEngine();assert.throws(()=>e.execute({operationType:'RECEIPT',idempotencyKey:'FAIL-1',payload:{amount:10},effects:[{amount:10}],failAfterEffects:true}),/INJECTED_FAILURE/);const op=[...e.operations.values()].find(x=>x.IdempotencyKey==='FAIL-1');assert.equal(op.Status,STATUS.NEEDS_REPAIR)});
